<?php

namespace App\Services;

use Illuminate\Support\Facades\Log;

class HomeSzService
{
    protected $con;
    protected $sql;
    public function __construct()
    {
        //更改成读取config/database.php
        $config = config('database.connections.oracle');
        //设置5s超时
        $this->con = oci_connect($config['username'], $config['password'], $config['host'].':'.$config['port'].'/'.$config['database'], "UTF8");
        if (!$this->con) {
            $e = oci_error();
            Log::info('病案首页质控error', ['msg' => 'getFyData：'.htmlentities($e['message'])]);
        }
    }

    /**
     * 获取用户主信息
     * @param $ZYH
     * @return array
     */
    public function getInfoSql()
    {
        $sql = "SELECT NVL(YX_HIS.CI_MR_FP_PAT_CATA.ID_ORG, '') AS hospital_name, NVL(YX_HIS.CI_MR_FP_PAT_CATA.CODE_AMR_IP, '') AS AAA28, NVL(YX_HIS.CI_MR_FP_PAT_CATA.ID_ENT, '') AS ZYH_ID, (NVL(YX_HIS.CI_MR_FP_PAT_CATA.CODE_AMR_IP, '') || '' || NVL(YX_HIS.CI_MR_FP_PAT_CATA.N_TIMES_INHOSPITAL, '')) AS MED_REC_ID, NVL(YX_HIS.CI_MR_FP_PAT_CATA.NAME_PAT, '') AS AAA01, NVL(CASE WHEN YX_HIS.CI_MR_FP_PAT_CATA.ID_SEX = '@@@@Z81000000003NSBP' THEN 0 WHEN YX_HIS.CI_MR_FP_PAT_CATA.ID_SEX = '@@@@Z81000000003NSBQ' THEN 1 WHEN YX_HIS.CI_MR_FP_PAT_CATA.ID_SEX = '@@@@Z81000000003NSBR' THEN 2 WHEN YX_HIS.CI_MR_FP_PAT_CATA.ID_SEX = '' THEN 9 END, '') AS AAA02C, NVL(YX_HIS.CI_MR_FP_PAT_CATA.NAME_SEX, '') AS AAA02C_MC, NVL(EN_ENT.DT_BIRTH_PAT, '') AS AAA03, NVL(YX_HIS.CI_MR_FP_PAT_CATA.AGE, '') AS AAA04_1, NVL(CASE WHEN YX_HIS.CI_MR_FP_PAT_CATA.SD_COUNTRY = '156' THEN 1 WHEN YX_HIS.CI_MR_FP_PAT_CATA.SD_COUNTRY = 'CHN' THEN 1 ELSE 2 END, '') AS AAA05C, NVL(YX_HIS.CI_MR_FP_PAT_CATA.NAME_COUNTRY, '') AS AAA05C_MC, NVL(YX_HIS.CI_MR_FP_PAT_CATA.ADDMISSION_WEIGHT, '') AS AAA42, NVL(YX_HIS.CI_MR_FP_PAT_CATA.BIRTH_WEIGHT, '') AS AEN01, NVL(YX_HIS.CI_MR_FP_PAT_CATA.BIRTH_WEIGHT_ONE, '') AS AEN01_2, NVL(YX_HIS.CI_MR_FP_PAT_CATA.BIRTH_WEIGHT_TWO, '') AS AEN01_3, NVL(YX_HIS.CI_MR_FP_PAT_CATA.BIRTH_WEIGHT_THREE, '') AS AEN01_4, NVL(YX_HIS.CI_MR_FP_PAT_CATA.BIRTH_WEIGHT_FOUR, '') AS AEN01_5, NVL(CASE WHEN YX_HIS.CI_MR_FP_PAT_CATA.SD_NATION = '01' THEN 1 WHEN YX_HIS.CI_MR_FP_PAT_CATA.SD_NATION = '02' THEN 2 WHEN YX_HIS.CI_MR_FP_PAT_CATA.SD_NATION = '03' THEN 3 WHEN YX_HIS.CI_MR_FP_PAT_CATA.SD_NATION = '05' THEN 5 WHEN YX_HIS.CI_MR_FP_PAT_CATA.SD_NATION = '11' THEN 11 WHEN YX_HIS.CI_MR_FP_PAT_CATA.SD_NATION = '97' THEN 66 END, '') AS AAA06C, NVL(YX_HIS.CI_MR_FP_PAT_CATA.NAME_NATION, '') AS AAA06C_MC, NVL(YX_HIS.CI_MR_FP_PAT_CATA.ID_CODE, '') AS AAA07, NVL(YX_HIS.CI_MR_FP_PAT_CATA.SD_MARRY, '') AS AAA08C, NVL(YX_HIS.CI_MR_FP_PAT_CATA.NAME_MARRY, '') AS AAA08C_MC, NVL(CI_MR_FP_OTHER_CATA.OUT_HOS_MODE, '') AS AEM01C, NVL(CI_MR_FP_OTHER_CATA.NAME_OUT_HOS_MODE, '') AS AEM01C_MC, NVL(YX_HIS.CI_MR_FP_PAT_CATA.DT_ACPT, '') AS AAB01, NVL(YX_HIS.CI_MR_FP_PAT_CATA.DT_END, '') AS AAC01, NVL(YX_HIS.CI_MR_FP_PAT_CATA.HOSDAYS, '') AS AAC04, NVL(CI_MR_FP_BL_CATA.AMOUNT, '') AS ADA01, NVL(CI_MR_FP_BL_CATA.CMS_SPAMOUNT, '') AS ADA0101, NVL(YX_HIS.CI_MR_FP_PAT_CATA.N_TIMES_INHOSPITAL, '') AS AAA29, NVL(CASE WHEN YX_HIS.CI_MR_FP_PAT_CATA.SD_REFERALSRC = '1' THEN 2 WHEN YX_HIS.CI_MR_FP_PAT_CATA.SD_REFERALSRC = '2' THEN 1 WHEN YX_HIS.CI_MR_FP_PAT_CATA.SD_REFERALSRC = '3' THEN 3 WHEN YX_HIS.CI_MR_FP_PAT_CATA.SD_REFERALSRC = '9' THEN 9 END, '') AS AAB06C, NVL(YX_HIS.CI_MR_FP_PAT_CATA.NAME_REFERALSRC, '') AS AAB06C_MC, NVL(CASE WHEN YX_HIS.CI_MR_FP_PAT_CATA.SD_PAY_METHOD = '1.1' THEN 1 WHEN YX_HIS.CI_MR_FP_PAT_CATA.SD_PAY_METHOD = '1.2' THEN 1 WHEN YX_HIS.CI_MR_FP_PAT_CATA.SD_PAY_METHOD = '2.1' THEN 2 WHEN YX_HIS.CI_MR_FP_PAT_CATA.SD_PAY_METHOD = '2.2' THEN 2 WHEN YX_HIS.CI_MR_FP_PAT_CATA.SD_PAY_METHOD = '3.1' THEN 3 WHEN YX_HIS.CI_MR_FP_PAT_CATA.SD_PAY_METHOD = '3.2' THEN 3 WHEN YX_HIS.CI_MR_FP_PAT_CATA.SD_PAY_METHOD = '4' THEN 4 WHEN YX_HIS.CI_MR_FP_PAT_CATA.SD_PAY_METHOD = '5' THEN 5 WHEN YX_HIS.CI_MR_FP_PAT_CATA.SD_PAY_METHOD = '6' THEN 6 WHEN YX_HIS.CI_MR_FP_PAT_CATA.SD_PAY_METHOD = '7' THEN 7 WHEN YX_HIS.CI_MR_FP_PAT_CATA.SD_PAY_METHOD = '8' THEN 8 WHEN YX_HIS.CI_MR_FP_PAT_CATA.SD_PAY_METHOD = '9' THEN 99 END, '') AS AAA26C, NVL(YX_HIS.CI_MR_FP_PAT_CATA.NAME_PAY_METHOD, '') AS AAA26C_MC, NVL(CI_MR_FP_OTHER_CATA.NAME_IIOUTREASON, '') AS ABG01N, NVL(CI_MR_FP_OTHER_CATA.SD_IIOUTREASON, '') AS ABG01C, NVL(CASE WHEN YX_HIS.CI_MR_FP_PAT_CATA.ID_ENT IS NULL THEN 2 ELSE 1 END , '') AS is_CATA , NVL(CASE WHEN YX_HIS.EN_ENT_IP.SD_STATUS = '25' THEN 1 ELSE 2 END, '') AS in_hospital FROM YX_HIS.CI_MR_FP_PAT_CATA LEFT JOIN YX_HIS.EN_ENT ON YX_HIS.EN_ENT.ID_ENT = YX_HIS.CI_MR_FP_PAT_CATA.ID_ENT LEFT JOIN YX_HIS.CI_MR_FP_OTHER_CATA ON YX_HIS.CI_MR_FP_OTHER_CATA.ID_ENT= YX_HIS.CI_MR_FP_PAT_CATA.ID_ENT LEFT JOIN YX_HIS.CI_MR_FP_BL_CATA ON YX_HIS.CI_MR_FP_OTHER_CATA.ID_ENT= YX_HIS.CI_MR_FP_BL_CATA.ID_ENT LEFT JOIN YX_HIS.EN_ENT_IP ON YX_HIS.EN_ENT_IP.ID_ENT= YX_HIS.CI_MR_FP_BL_CATA.ID_ENT";
        return $sql;
    }

    /**
     *获取patient_hospital_info表Sql
     */
    public function getHospitalSql()
    {
        $sql = "SELECT NVL(YX_HIS.CI_MR_FP_PAT_CATA.SD_DEP_PHYADM, '') AS AAB02C, NVL(YX_HIS.CI_MR_FP_PAT_CATA.NAME_DEP_PHYADM, '') AS LEFT JOIN YX_HIS.CI_MR_FP_BL_CATA ON YX_HIS.CI_MR_FP_OTHER_CATA.ID_ENT= YX_HIS.CI_MR_FP_BL_CATA.ID_ENT AAB03, NVL(YX_HIS.CI_MR_FP_PAT_CATA.SD_IN_BED, '') AS AAB11C, NVL(YX_HIS.CI_MR_FP_PAT_CATA.NAME_IN_BED, '') AS AAB11N, NVL(YX_HIS.CI_MR_FP_PAT_CATA.SD_DEP_PHYDISC, '') AS AAC02C, NVL(YX_HIS.CI_MR_FP_PAT_CATA.NAME_DEP_PHYDISC, '') AS AAC02C_MC, NVL(YX_HIS.CI_MR_FP_PAT_CATA.NAME_OUT_BED, '') AS AAC03, NVL(YX_HIS.CI_MR_FP_PAT_CATA.SD_OUT_BED, '') AS AAC11C, NVL(YX_HIS.CI_MR_FP_PAT_CATA.SD_DEP_TRANS, '') AS AAD01C, NVL(YX_HIS.CI_MR_FP_PAT_CATA.NAME_DEP_TRANS, '') AS ZKKBMC, NVL(CI_MR_FP_OTHER_CATA.NAME_MED_IN_1, '') AS AEM02, NVL(CI_MR_FP_OTHER_CATA.NAME_IS_HAVE_INHOS_PLAN, '') AS AEM03C, NVL(CI_MR_FP_OTHER_CATA.GOAL_INHOS_PLAN, '') AS AEM04, NVL(CI_MR_FP_OTHER_CATA.NAME_AUT_DEAD_PAT, '') AS AEI01C FROM YX_HIS.CI_MR_FP_PAT_CATA LEFT JOIN YX_HIS.CI_MR_FP_OTHER_CATA ON YX_HIS.CI_MR_FP_OTHER_CATA.ID_ENT= YX_HIS.CI_MR_FP_PAT_CATA.ID_ENT";
        return $sql;
    }

    //patient_doctor_info表Sql
    public function getDoctorSql()
    {
        $sql =" SELECT NVL(CI_MR_FP_OTHER_CATA.SD_QCP_DOC, '') AS ZKYS_BH, NVL(CI_MR_FP_OTHER_CATA.NAME_QCP_DOC, '') AS AED02, NVL(CI_MR_FP_OTHER_CATA.SD_QCP_NUR, '') AS ZKHS_BH, NVL(CI_MR_FP_OTHER_CATA.NAME_QCP_NUR, '') AS AED03, NVL(CI_MR_FP_OTHER_CATA.QC_DATE, '') AS AED04, NVL(CI_MR_FP_OTHER_CATA.DIROFDEPT, '') AS AEE01, NVL(CI_MR_FP_OTHER_CATA.SD_DIROFDEPT, '') AS AEE01_CODE, NVL(CI_MR_FP_OTHER_CATA.NAME_ZR_DOC, '') AS AEE02, NVL(CI_MR_FP_OTHER_CATA.NAME_ZZ_DOC, '') AS AEE03, NVL(CI_MR_FP_OTHER_CATA.NAME_ZY_DOC, '') AS AEE04, NVL(CI_MR_FP_OTHER_CATA.NAME_LEARN_DOC, '') AS AEE05, NVL(CI_MR_FP_OTHER_CATA.NAME_INTERN_DOC, '') AS AEE07, NVL(CI_MR_FP_OTHER_CATA.SD_INTERN_DOC, '') AS SXYS_BH, NVL(CI_MR_FP_OTHER_CATA.NAME_CODER, '') AS AEE08, NVL(CI_MR_FP_OTHER_CATA.SD_CODER, '') AS BMY_BH, NVL(CI_MR_FP_OTHER_CATA.NAME_EMP_NUR, '') AS AEE10, NVL(CI_MR_FP_OTHER_CATA.SD_EMP_NUR, '') AS ZRHS_BH, NVL(CI_MR_FP_OTHER_CATA.NAME_TEAM_DOC, '') AS YLZZ, NVL(CI_MR_FP_OTHER_CATA.SD_TEAM_DOC, '') AS YLZZ_BH, NVL(CI_MR_FP_OTHER_CATA.SD_ZR_DOC, '') AS AEE02_CODE, NVL(CI_MR_FP_OTHER_CATA.SD_ZZ_DOC, '') AS AEE03_CODE, NVL(CI_MR_FP_OTHER_CATA.SD_ZY_DOC, '') AS AEE04_CODE FROM YX_HIS.CI_MR_FP_PAT_CATA LEFT JOIN YX_HIS.CI_MR_FP_OTHER_CATA ON YX_HIS.CI_MR_FP_OTHER_CATA.ID_ENT= YX_HIS.CI_MR_FP_PAT_CATA.ID_ENT ";
        return $sql;
    }

    //patient_contacts_info表sql
    public function getContactsSql()
    {
        $sql = " SELECT NVL(YX_HIS.CI_MR_FP_PAT_CATA.NAME_CONT, '') AS AAA22, NVL(YX_HIS.CI_MR_FP_PAT_CATA.NAME_CONTTP, '') AS GX_MC, NVL(YX_HIS.CI_MR_FP_PAT_CATA.ADDR_CONT, '') AS AAA24, NVL(YX_HIS.CI_MR_FP_PAT_CATA.TEL_CONT, '') AS AAA25 FROM YX_HIS.CI_MR_FP_PAT_CATA ";
        return $sql;
    }

    //patient_address_info表sql
    public function getAddressSql()
    {
        $sql = "SELECT NVL(YX_HIS.CI_MR_FP_PAT_CATA.ADDR_NOW, '') AS AAA15,NVL(YX_HIS.CI_MR_FP_PAT_CATA.TEL_ADDR_NOW, '') AS AAA51,NVL(YX_HIS.CI_MR_FP_PAT_CATA.ADDR_BORN, '') AS CSD, NVL(YX_HIS.CI_MR_FP_PAT_CATA.ADDR_ORIGIN, '') AS GG, NVL(YX_HIS.CI_MR_FP_PAT_CATA.ADDR_CENCUS, '') AS AAA12, NVL(YX_HIS.CI_MR_FP_PAT_CATA.ZIP_ADDR_CENCUS, '') AS AAA14C, NVL(YX_HIS.CI_MR_FP_PAT_CATA.ZIP_ADDR_NOW, '') AS AAA17C FROM YX_HIS.CI_MR_FP_PAT_CATA ";
        return $sql;
    }

    //patient_add表sql
    public function getAddSql()
    {
        $sql = " SELECT NVL(YX_HIS.CI_MR_FP_PAT_CATA.HEALTH_CARD_ID, '') AS JKKH, NVL(YX_HIS.CI_MR_FP_PAT_CATA.NAME_IDTP, '') AS ZJLB_MC, NVL(CI_MR_FP_OTHER_CATA.THREELEV_NUR_DAYS, '') AS SJHL, NVL(CI_MR_FP_OTHER_CATA.TWOLEV_NUR_DAYS, '') AS EJHL, NVL(CI_MR_FP_OTHER_CATA.ONELEV_NUR_DAYS, '') AS YJHL, NVL(CI_MR_FP_OTHER_CATA.SUPERLEV_NUR_DAYS, '') AS TJHL, NVL(CI_MR_FP_OTHER_CATA.NAME_INPATHSTATUS, '') AS LCLJ, NVL(CI_MR_FP_OTHER_CATA.NAME_COMPLETESTATUS, '') AS WCQK, NVL(CI_MR_FP_OTHER_CATA.NAME_VARIATIONSTAUS, '') AS BYQK FROM YX_HIS.CI_MR_FP_PAT_CATA LEFT JOIN YX_HIS.CI_MR_FP_OTHER_CATA ON YX_HIS.CI_MR_FP_OTHER_CATA.ID_ENT= YX_HIS.CI_MR_FP_PAT_CATA.ID_ENT ";
        return $sql;
    }

    //patient_work_info表sql
    public function getWorkSql()
    {
        $sql = " SELECT NVL(YX_HIS.CI_MR_FP_PAT_CATA.SD_OCCU, '') AS AAA18C, NVL(YX_HIS.CI_MR_FP_PAT_CATA.NAME_OCCU, '') AS ZY_MC, NVL(YX_HIS.CI_MR_FP_PAT_CATA.WORKUNIT, '') AS GZDWJ, NVL(YX_HIS.CI_MR_FP_PAT_CATA.ADDR_WORK, '') AS GZDWJDZ, (NVL(YX_HIS.CI_MR_FP_PAT_CATA.WORKUNIT, '') || '' || NVL(YX_HIS.CI_MR_FP_PAT_CATA.ADDR_WORK, '')) AS AAA19, NVL(YX_HIS.CI_MR_FP_PAT_CATA.DEL_ADDR_WORK, '') AS AAA20, NVL(YX_HIS.CI_MR_FP_PAT_CATA.ZIP_ADDR_WORK, '') AS AAA21C FROM YX_HIS.CI_MR_FP_PAT_CATA ";
        return $sql;
    }

    //patient_medical_info表
    public function getMedicalSql()
    {
        $sql="SELECT NVL(YX_HIS.CI_MR_FP_PAT_CATA.SD_OUTP_EMER_DI, '') AS ABA01C, NVL(YX_HIS.CI_MR_FP_PAT_CATA.NAME_OUTP_EMER_DI, '') AS ABA01N, NVL(CI_MR_FP_OTHER_CATA.SD_DIPATHOLOGY, '') AS ABF01C, NVL(CI_MR_FP_OTHER_CATA.NAME_DIPATHOLOGY, '') AS ABF01N, NVL(CI_MR_FP_OTHER_CATA.NUM_PATHO, '') AS ABF04, NVL(CI_MR_FP_OTHER_CATA.REASON_HIGHTESTDI, '') AS ABF02C, NVL(CI_MR_FP_OTHER_CATA.NAME_DRUG_ALLERGY, '') AS AEB02C, NVL(CI_MR_FP_OTHER_CATA.ALLERGIC_DRUGS, '') AS AEB01, NVL(CI_MR_FP_OTHER_CATA.NAME_QOM_RECORD, '') AS AED01C, NVL(CI_MR_FP_OTHER_CATA.NAME_BLOOD_TYPE, '') AS AEG01C, NVL(CI_MR_FP_OTHER_CATA.NAME_RH_TYPE, '') AS AEG02C, NVL(CI_MR_FP_OTHER_CATA.COMA_TIME_BEF_INHOS_DAYS, '') AS AEJ01, NVL(CI_MR_FP_OTHER_CATA.COMA_TIME_BEF_INHOS_HOURS, '') AS AEJ02, NVL(CI_MR_FP_OTHER_CATA.COMA_TIME_BEF_INHOS_MINS, '') AS AEJ03, NVL(CI_MR_FP_OTHER_CATA.COMA_TIME_INHOS_DAYS, '') AS AEJ04, NVL(CI_MR_FP_OTHER_CATA.COMA_TIME_INHOS_HOURS, '') AS AEJ05, NVL(CI_MR_FP_OTHER_CATA.COMA_TIME_INHOS_MINS, '') AS AEJ06, NVL(CI_MR_FP_OTHER_CATA.VENTILATOR_USE_TIME_DAYS, '') AS AEL01_T, NVL(CI_MR_FP_OTHER_CATA.VENTILATOR_USE_TIME_HOURS, '') AS AEL01, NVL(CI_MR_FP_OTHER_CATA.VENTILATOR_USE_TIME_MINUTES, '') AS AEL01_F, NVL(CI_MR_FP_OTHER_CATA.FG_DAY_SURGERY, '') AS SFRJSS FROM YX_HIS.CI_MR_FP_PAT_CATA LEFT JOIN YX_HIS.CI_MR_FP_OTHER_CATA ON YX_HIS.CI_MR_FP_OTHER_CATA.ID_ENT= YX_HIS.CI_MR_FP_PAT_CATA.ID_ENT  ";
        return $sql;
    }

    //patient_cost_info表sql
    public function getCostSql()
    {
        $sql = " SELECT NVL(CI_MR_FP_BL_CATA.CMS_GMSFEE, '') AS D11, NVL(CI_MR_FP_BL_CATA.CMS_GTOFEE, '') AS D12, NVL(CI_MR_FP_BL_CATA.CMS_NURFEE, '') AS D13, NVL(CI_MR_FP_BL_CATA.CMS_OTHERFEE, '') AS D14, NVL(CI_MR_FP_BL_CATA.DI_PDIFEE, '') AS D15, NVL(CI_MR_FP_BL_CATA.DI_LDIFEE, '') AS D16, NVL(CI_MR_FP_BL_CATA.DI_IDIFEE, '') AS D17, NVL(CI_MR_FP_BL_CATA.DI_CDIFEE, '') AS D18, NVL(CI_MR_FP_BL_CATA.TC_NSTPFEE, '') AS D19, NVL(CI_MR_FP_BL_CATA.TC_CPTFEE, '') AS D19X01, NVL(CI_MR_FP_BL_CATA.TC_STFEE, '') AS D20, NVL(CI_MR_FP_BL_CATA.TC_ANFEE, '') AS D20X01, NVL(CI_MR_FP_BL_CATA.TC_OPFEE, '') AS D20X02, NVL(CI_MR_FP_BL_CATA.RC_RCFEE, '') AS D21, NVL(CI_MR_FP_BL_CATA.TCM_CMTFEE, '') AS D22, NVL(CI_MR_FP_BL_CATA.WM_WMFEE, '') AS D23, NVL(CI_MR_FP_BL_CATA.WM_AGFEE, '') AS D23X01, NVL(CI_MR_FP_BL_CATA.TCMT_CPMFEE, '') AS D24, NVL(CI_MR_FP_BL_CATA.TCMT_CHMFEE, '') AS D25, NVL(CI_MR_FP_BL_CATA.BABP_BFEE, '') AS D26, NVL(CI_MR_FP_BL_CATA.BABP_APFEE, '') AS D27, NVL(CI_MR_FP_BL_CATA.BABP_GPFEE, '') AS D28, NVL(CI_MR_FP_BL_CATA.BABP_BCFFEE, '') AS D29, NVL(CI_MR_FP_BL_CATA.BABP_CFLFEE, '') AS D30, NVL(CI_MR_FP_BL_CATA.SC_DMMFIFEE, '') AS D31, NVL(CI_MR_FP_BL_CATA.SC_DMMFTFEE, '') AS D32, NVL(CI_MR_FP_BL_CATA.SC_DMMFSFEE, '') AS D33, NVL(CI_MR_FP_BL_CATA.OC_OCFEE, '') AS D34 FROM YX_HIS.CI_MR_FP_PAT_CATA LEFT JOIN YX_HIS.CI_MR_FP_BL_CATA ON YX_HIS.CI_MR_FP_PAT_CATA.ID_ENT= YX_HIS.CI_MR_FP_BL_CATA.ID_ENT ";
        return $sql;
    }

    //
    public function getDiagnosisSql()
    {
        $sql = " SELECT NVL(CI_MR_FP_XYDI_CATA.SORTNO, '') AS DIA_ORDER, NVL(CASE YX_HIS.CI_MR_FP_XYDI_CATA.FG_MAINDI WHEN 'Y' THEN 1 WHEN 'N' THEN 0 ELSE 2 END, '') AS ZZPB, NVL(CI_MR_FP_XYDI_CATA.NAME_DI_TYPE, '') AS LBMC, NVL(CI_MR_FP_XYDI_CATA.SD_DI, '') AS ICD10_ID1, NVL(CI_MR_FP_XYDI_CATA.NAME_DI, '') AS ICD10_NAME, NVL(CI_MR_FP_XYDI_CATA.ID_DISLVL_INP, '') AS RYQK, NVL(CI_MR_FP_XYDI_CATA.SD_TREATMENT_OUTCOME, '') AS CYQK,NVL ( CI_MR_FP_XYDI_CATA.ID_MRFPXYDI, '' ) AS ZDXH FROM YX_HIS.CI_MR_FP_PAT_CATA LEFT JOIN YX_HIS.CI_MR_FP_DI_CATA ON YX_HIS.CI_MR_FP_DI_CATA.ID_ENT = YX_HIS.CI_MR_FP_PAT_CATA.ID_ENT LEFT JOIN YX_HIS.CI_MR_FP_XYDI_CATA ON YX_HIS.CI_MR_FP_XYDI_CATA.ID_MRFPDI = YX_HIS.CI_MR_FP_DI_CATA.ID_MRFPDI";
        return $sql;
    }

    //operation表sql
    public function getOperationSql()
    {
        $sql = " SELECT (NVL(YX_HIS.CI_MR_FP_PAT_CATA.CODE_AMR_IP, '') || '' || NVL(YX_HIS.CI_MR_FP_PAT_CATA.N_TIMES_INHOSPITAL, '')) AS AAA28, NVL(CI_MR_FP_SUG_CATA.ID_ENT, '') AS ZYH_ID, NVL(CI_MR_FP_SUG_CATA.SD_SUG, '') AS ICD9_ID1, NVL(CI_MR_FP_SUG_CATA.NAME_SUG, '') AS ICD9_NAME, NVL(CI_MR_FP_SUG_CATA.DT_START_SUG, '') AS OPE_DATE, NVL(CI_MR_FP_SUG_CATA.NAME_EMP_SUG, '') AS OPE_MAN_NAME, NVL(CI_MR_FP_SUG_CATA.SD_EMP_SUG, '') AS OPE_MAN_CODE, NVL(CI_MR_FP_SUG_CATA.SD_EMP_ASST1, '') AS FRIST_ASSISTANT_CODE, NVL(CI_MR_FP_SUG_CATA.NAME_EMP_ASST1, '') AS FRIST_ASSISTANT_NAME, NVL(CI_MR_FP_SUG_CATA.SD_EMP_ASST2, '') AS SECOND_ASSISTANT_CODE, NVL(CI_MR_FP_SUG_CATA.NAME_EMP_ASST2, '') AS SECOND_ASSISTANT_NAME, NVL(CI_MR_FP_SUG_CATA.SD_ANESTP, '') AS HOCUS_WAY_ID, NVL(CI_MR_FP_SUG_CATA.NAME_ANESTP, '') AS HOCUS_WAY_MC, NVL(CI_MR_FP_SUG_CATA.ID_INCICONDI, '') AS INCISION_GRADE_ID, NVL(CI_MR_FP_SUG_CATA.NAME_INCICONDI, '') AS INCISION_GRADE_MC, NVL(CI_MR_FP_SUG_CATA.SD_EMP_ANES, '') AS HOCUS_MAN_CODE, NVL(CI_MR_FP_SUG_CATA.NAME_EMP_ANES, '') AS HOCUS_MAN_NAME, NVL(CI_MR_FP_SUG_CATA.DT_START_SUG, '') AS START_TIME, NVL(CI_MR_FP_SUG_CATA.DT_END_SUG, '') AS END_TIME, NVL(CI_MR_FP_SUG_CATA.SORTNO, '') AS OPE_ORDER, NVL(CI_MR_FP_SUG_CATA.SD_LVLSUG, '') AS OPE_LEVEL, NVL(CI_MR_FP_SUG_CATA.NAME_LVLSUG, '') AS OPE_LEVEL_MC, NVL(CI_MR_FP_SUG_CATA.SD_CLASS_SUG, '') AS SSPB, NVL(CI_MR_FP_SUG_CATA.NAME_CLASS_SUG, '') AS SSPB_MC, NVL(CI_MR_FP_SUG_CATA.SORTNO, '') AS SFZYSS, NVL(CI_MR_FP_SUG_CATA.SD_INCITP, '') AS QKDJ, NVL(CI_MR_FP_SUG_CATA.NAME_INCITP, '') AS QKDJ_MC, NVL(CI_MR_FP_SUG_CATA.SD_METHOD_SUG, '') AS SSLX, NVL(CI_MR_FP_SUG_CATA.NAME_METHOD_SUG, '') AS SSLX_MC,NVL ( CI_MR_FP_SUG_CATA.ID_MRFPSUG, '' ) AS SSXH FROM YX_HIS.CI_MR_FP_PAT_CATA LEFT JOIN YX_HIS.CI_MR_FP_SUG_CATA ON YX_HIS.CI_MR_FP_SUG_CATA.ID_ENT = YX_HIS.CI_MR_FP_PAT_CATA.ID_ENT";
        return $sql;
    }

    //feeDetailed表sql
    public function getFeeDetailedSql()
    {
        $sql = "SELECT NVL(BL_CG_IP.ID_CGIP, '') AS FYXH, NVL(BL_CG_IP.NAME_SRV, '') AS FYMC, NVL(BL_CG_IP.DT_ST, '') AS JFRQ, NVL(BL_CG_IP.QUAN, '') AS FYSL, NVL(BL_CG_IP.AMT_STD, '') AS FYDJ, NVL(BL_CG_IP.ID_DEP_OR, '') AS FYKS, NVL(BL_CG_IP.NAME_INCCAITM, '') AS FYGB, NVL(BL_CG_IP.ID_CGIP, '') AS JLXH, NVL(BL_CG_IP.ID_DEP_MP, '') AS ZXKS, NVL(BL_CG_IP.CODE_HPPR, '') AS YBBM, NVL(BL_CG_IP.FG_REFUND, '') AS TKBZ, NVL(BL_CG_IP.NAME_ACCOUNT, '') AS SYGB,(NVL ( BL_CG_IP.ID_CGIP, '' ) || '' || NVL (to_char (BL_CG_IP.\"ods_insert_time\", 'yyyymmddHH24miss'),'')) AS FYXH_NO FROM YX_HIS.BL_CG_IP LEFT JOIN YX_HIS.CI_MR_FP_PAT_CATA ON YX_HIS.BL_CG_IP.ID_ENT = YX_HIS.CI_MR_FP_PAT_CATA.ID_ENT ";
        return $sql;
    }

    //yz表sql
    public function getYzSql()
    {
        $sql =  "SELECT (NVL(CI_MR_FP_PAT_CATA.CODE_AMR_IP, '') || '' || NVL(CI_MR_FP_PAT_CATA.N_TIMES_INHOSPITAL, '')) AS ZYH, NVL(CI_ORDER.ID_EN, '') AS ZYH_ID, NVL(CI_ORDER.ID_OR, '') AS YZBXH, NVL(CI_ORDER.ID_DEP_OR, '') AS BRKS, NVL(CI_ORDER.ID_WG_OR, '') AS BRBQ, NVL(CI_ORDER.SD_SRVTP, '') AS YDYZLB, NVL(CASE CI_ORDER.FG_LONG WHEN 'Y' THEN 1 WHEN 'N' THEN 2 ELSE 3 END, '') AS YZQX, NVL(CI_ORDER.ID_DEP_OR, '') AS KZKS, NVL(CI_ORDER.ID_EMP_OR, '') AS KZYS, NVL(CI_ORDER.DT_ENTRY, '') AS KZSJ, NVL(CI_ORDER.NAME_OR, '') AS YZMC, NVL(CI_ORDER.ID_FREQ, '') AS YPCD, NVL(CI_ORDER.ID_FREQ, '') AS SYPC, NVL(CI_ORDER.ID_ROUTE, '') AS GYTJ, NVL(CI_ORDER.ID_ROUTE, '') AS YCJL, NVL(CASE CI_ORDER.FG_URGENT WHEN 'Y' THEN 1 WHEN 'N' THEN 0 ELSE 9 END, '') AS JJYZ, NVL(CI_ORDER.SD_SU_OR, '') AS YZZT, NVL(CI_ORDER.SD_SU_MP, '') AS ZXZT, NVL(CI_ORDER.ID_EMP_CHK, '') AS XZJDGH, NVL(CI_ORDER.DT_CHK, '') AS XZJDSJ, NVL( CASE CI_ORDER.FG_SKINTEST WHEN 'Y' THEN 1 WHEN 'N' THEN 0 ELSE 9 END, '' ) AS PSBZ,NVL( CASE CI_ORDER.FG_CANC WHEN 'Y' THEN 1 WHEN 'N' THEN 0 ELSE 9 END, '' ) AS ZFBS FROM YX_HIS.CI_ORDER LEFT JOIN YX_HIS.CI_MR_FP_PAT_CATA ON YX_HIS.CI_ORDER.ID_EN = YX_HIS.CI_MR_FP_PAT_CATA.ID_ENT ";
        return $sql;
    }

    //获取所属院区
    public function getYq($ksCode)
    {
        $sql =  "SELECT NVL(BD_UDIDOC.ID_UDIDOC, '') AS YQ_CODE FROM YX_HIS.BD_UDIDOC  WHERE YX_HIS.BD_UDIDOC.ID_UDIDOCLIST = '@@@@LL200000000002GJ' AND YX_HIS.BD_UDIDOC.CODE = （SELECT NVL(BD_DEP.SD_HOSDISTRICT, '') AS SD_HOSDISTRICT FROM YX_HIS.BD_DEP WHERE YX_HIS.BD_DEP.CODE = '{$ksCode}'）";
        $data = oci_parse($this->con, $sql);
        oci_execute($data, OCI_DEFAULT);
        $result = [];
        while ($row = oci_fetch_assoc($data)) {
            $result[] = $row;
        }
        oci_free_statement($data);
        return $result;
    }

    public function getYqV2($ksCode)
    {
        $sql =  "SELECT NVL(BD_UDIDOC.ID_UDIDOC, '') AS YQ_CODE FROM YX_HIS.BD_UDIDOC  WHERE YX_HIS.BD_UDIDOC.ID_UDIDOCLIST = '@@@@LL200000000002GJ' AND YX_HIS.BD_UDIDOC.CODE = （SELECT NVL(BD_DEP.SD_HOSDISTRICT, '') AS SD_HOSDISTRICT FROM YX_HIS.BD_DEP WHERE YX_HIS.BD_DEP.CODE = '{$ksCode}'）";
        $data = oci_parse($this->con, $sql);
        oci_execute($data, OCI_DEFAULT);
        $result = [];
        while ($row = oci_fetch_assoc($data)) {
            $result[] = $row;
        }
        oci_free_statement($data);
        return $result;
    }


    public function getOdsInfo($sql,$ZYH_ID)
    {
        $sql .= " WHERE YX_HIS.CI_MR_FP_PAT_CATA.ID_ENT = '".$ZYH_ID."'";
        $data = oci_parse($this->con, $sql);
        oci_execute($data, OCI_DEFAULT);
        $result = [];
        while ($row = oci_fetch_assoc($data)) {
            $result[] = $row;
        }
       oci_free_statement($data);
        return $result;
    }

    public function getOdsInfoV2($sql,$ZYH_ID)
    {
        $sql .= " WHERE YX_HIS.CI_MR_FP_PAT.ID_ENT = '".$ZYH_ID."'";
        $data = oci_parse($this->con, $sql);
        oci_execute($data, OCI_DEFAULT);
        $result = [];
        while ($row = oci_fetch_assoc($data)) {
            $result[] = $row;
        }
        oci_free_statement($data);
        return $result;
    }

    public function ZY_ZKJL($ZYH) {
        return false;
    }
}
