<?php

namespace App\Services;

use Carbon\Carbon;
use Illuminate\Support\Facades\Log;
use mysql_xdevapi\Exception;
use PhpOffice\PhpSpreadsheet\Reader\Ods;

class OdsService
{

    protected $user_name = 'VS_BAZK'; //ods 用户名

    protected $pass_word = 'vs_bazk#123'; //ods 密码

    protected $ods_ip = '10.32.82.8:1521/ods'; //ods 链接地址

    protected $character = 'UTF8'; //ods 编码

    private static $service;

    private $connect;

    private $sql;

    public function __construct()
    {
        try {
            if (!($this->connect = oci_connect($this->user_name, $this->pass_word, $this->ods_ip, $this->character))) {
                Log::info(__CLASS__.'链接ODS数据库报错::', ['msg' => htmlentities(data_get(oci_error(), 'message'))]);
            }
        }catch (\Exception $exception) {
            Log::info(__CLASS__.'链接ODS数据库报错::'.$exception->getMessage());
        }
    }

    /**
     * 获取当前类实例
     * @return OdsService
     */
    public static function getService() : self
    {
        //判断实例是否属于当前类
        if(!self::$service instanceof OdsService){
            self::$service = new OdsService();
        }
        return self::$service;
    }

    /**
     * 获取需要同步的数据
     * @param int $hours
     * @param false $start
     * @return $this
     */
    public function getSyncData($hours = 1, $start = false) : self
    {
        $start = Carbon::parse($start ?: null)->subHours($hours)->format("Y-m-d 00:00:00");
        $this->sql = "SELECT NVL(HIS.CI_MR_FP_PAT.ID_ENT, '') AS ZYH_ID, NVL( CASE WHEN HIS.CI_MR_FP_PAT_CATA.ID_ENT IS NULL THEN 2 ELSE 1 END,'') AS IS_CATA FROM HIS.CI_MR_FP_PAT LEFT JOIN HIS.EN_ENT ON HIS.EN_ENT.ID_ENT = HIS.CI_MR_FP_PAT.ID_ENT LEFT JOIN HIS.CI_MR_FP_OTHER ON HIS.CI_MR_FP_OTHER.ID_ENT= HIS.CI_MR_FP_PAT.ID_ENT LEFT JOIN HIS.CI_MR_FP_BL ON HIS.CI_MR_FP_OTHER.ID_ENT= HIS.CI_MR_FP_BL.ID_ENT LEFT JOIN HIS.EN_ENT_IP ON HIS.EN_ENT_IP.ID_ENT = HIS.CI_MR_FP_PAT.ID_ENT LEFT JOIN HIS.CI_MR_FP_PAT_CATA ON HIS.CI_MR_FP_PAT_CATA.ID_ENT = HIS.CI_MR_FP_PAT.ID_ENT WHERE (HIS.EN_ENT_IP.SD_STATUS = '25' OR HIS.EN_ENT_IP.SD_STATUS = '28') AND HIS.CI_MR_FP_PAT.\"ods_update_time\" >= TO_DATE('{$start}','yyyy-mm-dd hh24:mi:ss') ORDER BY HIS.CI_MR_FP_PAT.\"ods_update_time\" ASC ";
        return $this;
    }

    /**
     * 获取用户主信息
     * @return self
     */
    public function getInfoSql()
    {
        $this->sql = "SELECT NVL(HIS.CI_MR_FP_PAT_CATA.ID_ORG, '') AS hospital_name, NVL(HIS.CI_MR_FP_PAT_CATA.CODE_AMR_IP, '') AS AAA28, NVL(HIS.CI_MR_FP_PAT_CATA.ID_ENT, '') AS ZYH_ID, (NVL(HIS.CI_MR_FP_PAT_CATA.CODE_AMR_IP, '') || '' || NVL(HIS.CI_MR_FP_PAT_CATA.N_TIMES_INHOSPITAL, '')) AS MED_REC_ID, NVL(HIS.CI_MR_FP_PAT_CATA.NAME_PAT, '') AS AAA01, NVL(CASE WHEN HIS.CI_MR_FP_PAT_CATA.ID_SEX = '@@@@Z81000000003NSBP' THEN 0 WHEN HIS.CI_MR_FP_PAT_CATA.ID_SEX = '@@@@Z81000000003NSBQ' THEN 1 WHEN HIS.CI_MR_FP_PAT_CATA.ID_SEX = '@@@@Z81000000003NSBR' THEN 2 WHEN HIS.CI_MR_FP_PAT_CATA.ID_SEX = '' THEN 9 END, '') AS AAA02C, NVL(HIS.CI_MR_FP_PAT_CATA.NAME_SEX, '') AS AAA02C_MC, NVL(EN_ENT.DT_BIRTH_PAT, '') AS AAA03, NVL(HIS.CI_MR_FP_PAT_CATA.AGE, '') AS AAA04_1, NVL(CASE WHEN HIS.CI_MR_FP_PAT_CATA.SD_COUNTRY = '156' THEN 1 WHEN HIS.CI_MR_FP_PAT_CATA.SD_COUNTRY = 'CHN' THEN 1 ELSE 2 END, '') AS AAA05C, NVL(HIS.CI_MR_FP_PAT_CATA.NAME_COUNTRY, '') AS AAA05C_MC, NVL(HIS.CI_MR_FP_PAT_CATA.ADDMISSION_WEIGHT, '') AS AAA42, NVL(HIS.CI_MR_FP_PAT_CATA.BIRTH_WEIGHT, '') AS AEN01, NVL(HIS.CI_MR_FP_PAT_CATA.BIRTH_WEIGHT_ONE, '') AS AEN01_2, NVL(HIS.CI_MR_FP_PAT_CATA.BIRTH_WEIGHT_TWO, '') AS AEN01_3, NVL(HIS.CI_MR_FP_PAT_CATA.BIRTH_WEIGHT_THREE, '') AS AEN01_4, NVL(HIS.CI_MR_FP_PAT_CATA.BIRTH_WEIGHT_FOUR, '') AS AEN01_5, NVL(CASE WHEN HIS.CI_MR_FP_PAT_CATA.SD_NATION = '01' THEN 1 WHEN HIS.CI_MR_FP_PAT_CATA.SD_NATION = '02' THEN 2 WHEN HIS.CI_MR_FP_PAT_CATA.SD_NATION = '03' THEN 3 WHEN HIS.CI_MR_FP_PAT_CATA.SD_NATION = '05' THEN 5 WHEN HIS.CI_MR_FP_PAT_CATA.SD_NATION = '11' THEN 11 WHEN HIS.CI_MR_FP_PAT_CATA.SD_NATION = '97' THEN 66 END, '') AS AAA06C, NVL(HIS.CI_MR_FP_PAT_CATA.NAME_NATION, '') AS AAA06C_MC, NVL(HIS.CI_MR_FP_PAT_CATA.ID_CODE, '') AS AAA07, NVL(HIS.CI_MR_FP_PAT_CATA.SD_MARRY, '') AS AAA08C, NVL(HIS.CI_MR_FP_PAT_CATA.NAME_MARRY, '') AS AAA08C_MC, NVL(CI_MR_FP_OTHER_CATA.OUT_HOS_MODE, '') AS AEM01C, NVL(CI_MR_FP_OTHER_CATA.NAME_OUT_HOS_MODE, '') AS AEM01C_MC, NVL(HIS.CI_MR_FP_PAT_CATA.DT_ACPT, '') AS AAB01, NVL(HIS.CI_MR_FP_PAT_CATA.DT_END, '') AS AAC01, NVL(HIS.CI_MR_FP_PAT_CATA.HOSDAYS, '') AS AAC04, NVL(CI_MR_FP_BL_CATA.AMOUNT, '') AS ADA01, NVL(CI_MR_FP_BL_CATA.CMS_SPAMOUNT, '') AS ADA0101, NVL(HIS.CI_MR_FP_PAT_CATA.N_TIMES_INHOSPITAL, '') AS AAA29, NVL(CASE WHEN HIS.CI_MR_FP_PAT_CATA.SD_REFERALSRC = '1' THEN 2 WHEN HIS.CI_MR_FP_PAT_CATA.SD_REFERALSRC = '2' THEN 1 WHEN HIS.CI_MR_FP_PAT_CATA.SD_REFERALSRC = '3' THEN 3 WHEN HIS.CI_MR_FP_PAT_CATA.SD_REFERALSRC = '9' THEN 9 END, '') AS AAB06C, NVL(HIS.CI_MR_FP_PAT_CATA.NAME_REFERALSRC, '') AS AAB06C_MC, NVL(CASE WHEN HIS.CI_MR_FP_PAT_CATA.SD_PAY_METHOD = '1.1' THEN 1 WHEN HIS.CI_MR_FP_PAT_CATA.SD_PAY_METHOD = '1.2' THEN 1 WHEN HIS.CI_MR_FP_PAT_CATA.SD_PAY_METHOD = '2.1' THEN 2 WHEN HIS.CI_MR_FP_PAT_CATA.SD_PAY_METHOD = '2.2' THEN 2 WHEN HIS.CI_MR_FP_PAT_CATA.SD_PAY_METHOD = '3.1' THEN 3 WHEN HIS.CI_MR_FP_PAT_CATA.SD_PAY_METHOD = '3.2' THEN 3 WHEN HIS.CI_MR_FP_PAT_CATA.SD_PAY_METHOD = '4' THEN 4 WHEN HIS.CI_MR_FP_PAT_CATA.SD_PAY_METHOD = '5' THEN 5 WHEN HIS.CI_MR_FP_PAT_CATA.SD_PAY_METHOD = '6' THEN 6 WHEN HIS.CI_MR_FP_PAT_CATA.SD_PAY_METHOD = '7' THEN 7 WHEN HIS.CI_MR_FP_PAT_CATA.SD_PAY_METHOD = '8' THEN 8 WHEN HIS.CI_MR_FP_PAT_CATA.SD_PAY_METHOD = '9' THEN 99 END, '') AS AAA26C, NVL(HIS.CI_MR_FP_PAT_CATA.NAME_PAY_METHOD, '') AS AAA26C_MC, NVL(CI_MR_FP_OTHER_CATA.NAME_IIOUTREASON, '') AS ABG01N, NVL(CI_MR_FP_OTHER_CATA.SD_IIOUTREASON, '') AS ABG01C, NVL(CASE WHEN HIS.CI_MR_FP_PAT_CATA.ID_ENT IS NULL THEN 2 ELSE 1 END , '') AS is_CATA , NVL(CASE WHEN HIS.EN_ENT_IP.SD_STATUS = '25' THEN 1 ELSE 2 END, '') AS in_hospital FROM HIS.CI_MR_FP_PAT_CATA LEFT JOIN HIS.EN_ENT ON HIS.EN_ENT.ID_ENT = HIS.CI_MR_FP_PAT_CATA.ID_ENT LEFT JOIN HIS.CI_MR_FP_OTHER_CATA ON HIS.CI_MR_FP_OTHER_CATA.ID_ENT= HIS.CI_MR_FP_PAT_CATA.ID_ENT LEFT JOIN HIS.CI_MR_FP_BL_CATA ON HIS.CI_MR_FP_OTHER_CATA.ID_ENT= HIS.CI_MR_FP_BL_CATA.ID_ENT LEFT JOIN HIS.EN_ENT_IP ON HIS.EN_ENT_IP.ID_ENT= HIS.CI_MR_FP_BL_CATA.ID_ENT";
        return $this;
    }

    /**
     *获取patient_hospital_info表Sql
     * @return self
     */
    public function getHospitalSql()
    {
        $this->sql = "SELECT NVL(HIS.CI_MR_FP_PAT_CATA.SD_DEP_PHYADM, '') AS AAB02C, NVL(HIS.CI_MR_FP_PAT_CATA.NAME_DEP_PHYADM, '') AS LEFT JOIN HIS.CI_MR_FP_BL_CATA ON HIS.CI_MR_FP_OTHER_CATA.ID_ENT= HIS.CI_MR_FP_BL_CATA.ID_ENT AAB03, NVL(HIS.CI_MR_FP_PAT_CATA.SD_IN_BED, '') AS AAB11C, NVL(HIS.CI_MR_FP_PAT_CATA.NAME_IN_BED, '') AS AAB11N, NVL(HIS.CI_MR_FP_PAT_CATA.SD_DEP_PHYDISC, '') AS AAC02C, NVL(HIS.CI_MR_FP_PAT_CATA.NAME_DEP_PHYDISC, '') AS AAC02C_MC, NVL(HIS.CI_MR_FP_PAT_CATA.NAME_OUT_BED, '') AS AAC03, NVL(HIS.CI_MR_FP_PAT_CATA.SD_OUT_BED, '') AS AAC11C, NVL(HIS.CI_MR_FP_PAT_CATA.SD_DEP_TRANS, '') AS AAD01C, NVL(HIS.CI_MR_FP_PAT_CATA.NAME_DEP_TRANS, '') AS ZKKBMC, NVL(CI_MR_FP_OTHER_CATA.NAME_MED_IN_1, '') AS AEM02, NVL(CI_MR_FP_OTHER_CATA.NAME_IS_HAVE_INHOS_PLAN, '') AS AEM03C, NVL(CI_MR_FP_OTHER_CATA.GOAL_INHOS_PLAN, '') AS AEM04, NVL(CI_MR_FP_OTHER_CATA.NAME_AUT_DEAD_PAT, '') AS AEI01C FROM HIS.CI_MR_FP_PAT_CATA LEFT JOIN HIS.CI_MR_FP_OTHER_CATA ON HIS.CI_MR_FP_OTHER_CATA.ID_ENT= HIS.CI_MR_FP_PAT_CATA.ID_ENT";
        return $this;
    }

    /**
     * patient_doctor_info表Sql
     * @return self
     */
    public function getDoctorSql()
    {
        $this->sql =" SELECT NVL(CI_MR_FP_OTHER_CATA.SD_QCP_DOC, '') AS ZKYS_BH, NVL(CI_MR_FP_OTHER_CATA.NAME_QCP_DOC, '') AS AED02, NVL(CI_MR_FP_OTHER_CATA.SD_QCP_NUR, '') AS ZKHS_BH, NVL(CI_MR_FP_OTHER_CATA.NAME_QCP_NUR, '') AS AED03, NVL(CI_MR_FP_OTHER_CATA.QC_DATE, '') AS AED04, NVL(CI_MR_FP_OTHER_CATA.DIROFDEPT, '') AS AEE01, NVL(CI_MR_FP_OTHER_CATA.SD_DIROFDEPT, '') AS AEE01_CODE, NVL(CI_MR_FP_OTHER_CATA.NAME_ZR_DOC, '') AS AEE02, NVL(CI_MR_FP_OTHER_CATA.NAME_ZZ_DOC, '') AS AEE03, NVL(CI_MR_FP_OTHER_CATA.NAME_ZY_DOC, '') AS AEE04, NVL(CI_MR_FP_OTHER_CATA.NAME_LEARN_DOC, '') AS AEE05, NVL(CI_MR_FP_OTHER_CATA.NAME_INTERN_DOC, '') AS AEE07, NVL(CI_MR_FP_OTHER_CATA.SD_INTERN_DOC, '') AS SXYS_BH, NVL(CI_MR_FP_OTHER_CATA.NAME_CODER, '') AS AEE08, NVL(CI_MR_FP_OTHER_CATA.SD_CODER, '') AS BMY_BH, NVL(CI_MR_FP_OTHER_CATA.NAME_EMP_NUR, '') AS AEE10, NVL(CI_MR_FP_OTHER_CATA.SD_EMP_NUR, '') AS ZRHS_BH, NVL(CI_MR_FP_OTHER_CATA.NAME_TEAM_DOC, '') AS YLZZ, NVL(CI_MR_FP_OTHER_CATA.SD_TEAM_DOC, '') AS YLZZ_BH, NVL(CI_MR_FP_OTHER_CATA.SD_ZR_DOC, '') AS AEE02_CODE, NVL(CI_MR_FP_OTHER_CATA.SD_ZZ_DOC, '') AS AEE03_CODE, NVL(CI_MR_FP_OTHER_CATA.SD_ZY_DOC, '') AS AEE04_CODE FROM HIS.CI_MR_FP_PAT_CATA LEFT JOIN HIS.CI_MR_FP_OTHER_CATA ON HIS.CI_MR_FP_OTHER_CATA.ID_ENT= HIS.CI_MR_FP_PAT_CATA.ID_ENT ";
        return $this;
    }

    /**
     * patient_contacts_info表sql
     * @return $this
     */
    public function getContactsSql()
    {
        $this->sql = " SELECT NVL(HIS.CI_MR_FP_PAT_CATA.NAME_CONT, '') AS AAA22, NVL(HIS.CI_MR_FP_PAT_CATA.NAME_CONTTP, '') AS GX_MC, NVL(HIS.CI_MR_FP_PAT_CATA.ADDR_CONT, '') AS AAA24, NVL(HIS.CI_MR_FP_PAT_CATA.TEL_CONT, '') AS AAA25 FROM HIS.CI_MR_FP_PAT_CATA ";
        return $this;
    }

    /**
     * patient_address_info表sql
     * @return $this
     */
    public function getAddressSql()
    {
        $this->sql = "SELECT NVL(HIS.CI_MR_FP_PAT_CATA.ADDR_NOW, '') AS AAA15,NVL(HIS.CI_MR_FP_PAT_CATA.TEL_ADDR_NOW, '') AS AAA51,NVL(HIS.CI_MR_FP_PAT_CATA.ADDR_BORN, '') AS CSD, NVL(HIS.CI_MR_FP_PAT_CATA.ADDR_ORIGIN, '') AS GG, NVL(HIS.CI_MR_FP_PAT_CATA.ADDR_CENCUS, '') AS AAA12, NVL(HIS.CI_MR_FP_PAT_CATA.ZIP_ADDR_CENCUS, '') AS AAA14C, NVL(HIS.CI_MR_FP_PAT_CATA.ZIP_ADDR_NOW, '') AS AAA17C FROM HIS.CI_MR_FP_PAT_CATA ";
        return $this;
    }

    /**
     * patient_add表sql
     * @return $this
     */
    public function getAddSql()
    {
        $this->sql = " SELECT NVL(HIS.CI_MR_FP_PAT_CATA.HEALTH_CARD_ID, '') AS JKKH, NVL(HIS.CI_MR_FP_PAT_CATA.NAME_IDTP, '') AS ZJLB_MC, NVL(CI_MR_FP_OTHER_CATA.THREELEV_NUR_DAYS, '') AS SJHL, NVL(CI_MR_FP_OTHER_CATA.TWOLEV_NUR_DAYS, '') AS EJHL, NVL(CI_MR_FP_OTHER_CATA.ONELEV_NUR_DAYS, '') AS YJHL, NVL(CI_MR_FP_OTHER_CATA.SUPERLEV_NUR_DAYS, '') AS TJHL, NVL(CI_MR_FP_OTHER_CATA.NAME_INPATHSTATUS, '') AS LCLJ, NVL(CI_MR_FP_OTHER_CATA.NAME_COMPLETESTATUS, '') AS WCQK, NVL(CI_MR_FP_OTHER_CATA.NAME_VARIATIONSTAUS, '') AS BYQK FROM HIS.CI_MR_FP_PAT_CATA LEFT JOIN HIS.CI_MR_FP_OTHER_CATA ON HIS.CI_MR_FP_OTHER_CATA.ID_ENT= HIS.CI_MR_FP_PAT_CATA.ID_ENT ";
        return $this;
    }

    /**
     * patient_work_info表sql
     * @return $this
     */
    public function getWorkSql()
    {
        $this->sql = " SELECT NVL(HIS.CI_MR_FP_PAT_CATA.SD_OCCU, '') AS AAA18C, NVL(HIS.CI_MR_FP_PAT_CATA.NAME_OCCU, '') AS ZY_MC, NVL(HIS.CI_MR_FP_PAT_CATA.WORKUNIT, '') AS GZDWJ, NVL(HIS.CI_MR_FP_PAT_CATA.ADDR_WORK, '') AS GZDWJDZ, (NVL(HIS.CI_MR_FP_PAT_CATA.WORKUNIT, '') || '' || NVL(HIS.CI_MR_FP_PAT_CATA.ADDR_WORK, '')) AS AAA19, NVL(HIS.CI_MR_FP_PAT_CATA.DEL_ADDR_WORK, '') AS AAA20, NVL(HIS.CI_MR_FP_PAT_CATA.ZIP_ADDR_WORK, '') AS AAA21C FROM HIS.CI_MR_FP_PAT_CATA ";
        return $this;
    }

    /**
     * patient_medical_info表
     * @return $this
     */
    public function getMedicalSql()
    {
        $this->sql = "SELECT NVL(HIS.CI_MR_FP_PAT_CATA.SD_OUTP_EMER_DI, '') AS ABA01C, NVL(HIS.CI_MR_FP_PAT_CATA.NAME_OUTP_EMER_DI, '') AS ABA01N, NVL(CI_MR_FP_OTHER_CATA.SD_DIPATHOLOGY, '') AS ABF01C, NVL(CI_MR_FP_OTHER_CATA.NAME_DIPATHOLOGY, '') AS ABF01N, NVL(CI_MR_FP_OTHER_CATA.NUM_PATHO, '') AS ABF04, NVL(CI_MR_FP_OTHER_CATA.REASON_HIGHTESTDI, '') AS ABF02C, NVL(CI_MR_FP_OTHER_CATA.NAME_DRUG_ALLERGY, '') AS AEB02C, NVL(CI_MR_FP_OTHER_CATA.ALLERGIC_DRUGS, '') AS AEB01, NVL(CI_MR_FP_OTHER_CATA.NAME_QOM_RECORD, '') AS AED01C, NVL(CI_MR_FP_OTHER_CATA.NAME_BLOOD_TYPE, '') AS AEG01C, NVL(CI_MR_FP_OTHER_CATA.NAME_RH_TYPE, '') AS AEG02C, NVL(CI_MR_FP_OTHER_CATA.COMA_TIME_BEF_INHOS_DAYS, '') AS AEJ01, NVL(CI_MR_FP_OTHER_CATA.COMA_TIME_BEF_INHOS_HOURS, '') AS AEJ02, NVL(CI_MR_FP_OTHER_CATA.COMA_TIME_BEF_INHOS_MINS, '') AS AEJ03, NVL(CI_MR_FP_OTHER_CATA.COMA_TIME_INHOS_DAYS, '') AS AEJ04, NVL(CI_MR_FP_OTHER_CATA.COMA_TIME_INHOS_HOURS, '') AS AEJ05, NVL(CI_MR_FP_OTHER_CATA.COMA_TIME_INHOS_MINS, '') AS AEJ06, NVL(CI_MR_FP_OTHER_CATA.VENTILATOR_USE_TIME_DAYS, '') AS AEL01_T, NVL(CI_MR_FP_OTHER_CATA.VENTILATOR_USE_TIME_HOURS, '') AS AEL01, NVL(CI_MR_FP_OTHER_CATA.VENTILATOR_USE_TIME_MINUTES, '') AS AEL01_F, NVL(CI_MR_FP_OTHER_CATA.FG_DAY_SURGERY, '') AS SFRJSS FROM HIS.CI_MR_FP_PAT_CATA LEFT JOIN HIS.CI_MR_FP_OTHER_CATA ON HIS.CI_MR_FP_OTHER_CATA.ID_ENT= HIS.CI_MR_FP_PAT_CATA.ID_ENT  ";
        return $this;
    }

    /**
     * patient_cost_info表sql
     * @return $this
     */
    public function getCostSql()
    {
        $this->sql = " SELECT NVL(CI_MR_FP_BL_CATA.CMS_GMSFEE, '') AS D11, NVL(CI_MR_FP_BL_CATA.CMS_GTOFEE, '') AS D12, NVL(CI_MR_FP_BL_CATA.CMS_NURFEE, '') AS D13, NVL(CI_MR_FP_BL_CATA.CMS_OTHERFEE, '') AS D14, NVL(CI_MR_FP_BL_CATA.DI_PDIFEE, '') AS D15, NVL(CI_MR_FP_BL_CATA.DI_LDIFEE, '') AS D16, NVL(CI_MR_FP_BL_CATA.DI_IDIFEE, '') AS D17, NVL(CI_MR_FP_BL_CATA.DI_CDIFEE, '') AS D18, NVL(CI_MR_FP_BL_CATA.TC_NSTPFEE, '') AS D19, NVL(CI_MR_FP_BL_CATA.TC_CPTFEE, '') AS D19X01, NVL(CI_MR_FP_BL_CATA.TC_STFEE, '') AS D20, NVL(CI_MR_FP_BL_CATA.TC_ANFEE, '') AS D20X01, NVL(CI_MR_FP_BL_CATA.TC_OPFEE, '') AS D20X02, NVL(CI_MR_FP_BL_CATA.RC_RCFEE, '') AS D21, NVL(CI_MR_FP_BL_CATA.TCM_CMTFEE, '') AS D22, NVL(CI_MR_FP_BL_CATA.WM_WMFEE, '') AS D23, NVL(CI_MR_FP_BL_CATA.WM_AGFEE, '') AS D23X01, NVL(CI_MR_FP_BL_CATA.TCMT_CPMFEE, '') AS D24, NVL(CI_MR_FP_BL_CATA.TCMT_CHMFEE, '') AS D25, NVL(CI_MR_FP_BL_CATA.BABP_BFEE, '') AS D26, NVL(CI_MR_FP_BL_CATA.BABP_APFEE, '') AS D27, NVL(CI_MR_FP_BL_CATA.BABP_GPFEE, '') AS D28, NVL(CI_MR_FP_BL_CATA.BABP_BCFFEE, '') AS D29, NVL(CI_MR_FP_BL_CATA.BABP_CFLFEE, '') AS D30, NVL(CI_MR_FP_BL_CATA.SC_DMMFIFEE, '') AS D31, NVL(CI_MR_FP_BL_CATA.SC_DMMFTFEE, '') AS D32, NVL(CI_MR_FP_BL_CATA.SC_DMMFSFEE, '') AS D33, NVL(CI_MR_FP_BL_CATA.OC_OCFEE, '') AS D34 FROM HIS.CI_MR_FP_PAT_CATA LEFT JOIN HIS.CI_MR_FP_BL_CATA ON HIS.CI_MR_FP_PAT_CATA.ID_ENT= HIS.CI_MR_FP_BL_CATA.ID_ENT ";
        return $this;
    }

    /**
     * diagnosis表sql
     * @return $this
     */
    public function getDiagnosisSql()
    {
        $this->sql = " SELECT NVL(CI_MR_FP_XYDI_CATA.SORTNO, '') AS DIA_ORDER, NVL(CASE HIS.CI_MR_FP_XYDI_CATA.FG_MAINDI WHEN 'Y' THEN 1 WHEN 'N' THEN 0 ELSE 2 END, '') AS ZZPB, NVL(CI_MR_FP_XYDI_CATA.NAME_DI_TYPE, '') AS LBMC, NVL(CI_MR_FP_XYDI_CATA.SD_DI, '') AS ICD10_ID1, NVL(CI_MR_FP_XYDI_CATA.NAME_DI, '') AS ICD10_NAME, NVL(CI_MR_FP_XYDI_CATA.ID_DISLVL_INP, '') AS RYQK, NVL(CI_MR_FP_XYDI_CATA.SD_TREATMENT_OUTCOME, '') AS CYQK,NVL ( CI_MR_FP_XYDI_CATA.ID_MRFPXYDI, '' ) AS ZDXH FROM HIS.CI_MR_FP_PAT_CATA LEFT JOIN HIS.CI_MR_FP_DI_CATA ON HIS.CI_MR_FP_DI_CATA.ID_ENT = HIS.CI_MR_FP_PAT_CATA.ID_ENT LEFT JOIN HIS.CI_MR_FP_XYDI_CATA ON HIS.CI_MR_FP_XYDI_CATA.ID_MRFPDI = HIS.CI_MR_FP_DI_CATA.ID_MRFPDI";
        return $this;
    }

    /**
     * operation表sql
     * @return $this
     */
    public function getOperationSql()
    {
        $this->sql = " SELECT (NVL(HIS.CI_MR_FP_PAT_CATA.CODE_AMR_IP, '') || '' || NVL(HIS.CI_MR_FP_PAT_CATA.N_TIMES_INHOSPITAL, '')) AS AAA28, NVL(CI_MR_FP_SUG_CATA.ID_ENT, '') AS ZYH_ID, NVL(CI_MR_FP_SUG_CATA.SD_SUG, '') AS ICD9_ID1, NVL(CI_MR_FP_SUG_CATA.NAME_SUG, '') AS ICD9_NAME, NVL(CI_MR_FP_SUG_CATA.DT_START_SUG, '') AS OPE_DATE, NVL(CI_MR_FP_SUG_CATA.NAME_EMP_SUG, '') AS OPE_MAN_NAME, NVL(CI_MR_FP_SUG_CATA.SD_EMP_SUG, '') AS OPE_MAN_CODE, NVL(CI_MR_FP_SUG_CATA.SD_EMP_ASST1, '') AS FRIST_ASSISTANT_CODE, NVL(CI_MR_FP_SUG_CATA.NAME_EMP_ASST1, '') AS FRIST_ASSISTANT_NAME, NVL(CI_MR_FP_SUG_CATA.SD_EMP_ASST2, '') AS SECOND_ASSISTANT_CODE, NVL(CI_MR_FP_SUG_CATA.NAME_EMP_ASST2, '') AS SECOND_ASSISTANT_NAME, NVL(CI_MR_FP_SUG_CATA.SD_ANESTP, '') AS HOCUS_WAY_ID, NVL(CI_MR_FP_SUG_CATA.NAME_ANESTP, '') AS HOCUS_WAY_MC, NVL(CI_MR_FP_SUG_CATA.ID_INCICONDI, '') AS INCISION_GRADE_ID, NVL(CI_MR_FP_SUG_CATA.NAME_INCICONDI, '') AS INCISION_GRADE_MC, NVL(CI_MR_FP_SUG_CATA.SD_EMP_ANES, '') AS HOCUS_MAN_CODE, NVL(CI_MR_FP_SUG_CATA.NAME_EMP_ANES, '') AS HOCUS_MAN_NAME, NVL(CI_MR_FP_SUG_CATA.DT_START_SUG, '') AS START_TIME, NVL(CI_MR_FP_SUG_CATA.DT_END_SUG, '') AS END_TIME, NVL(CI_MR_FP_SUG_CATA.SORTNO, '') AS OPE_ORDER, NVL(CI_MR_FP_SUG_CATA.SD_LVLSUG, '') AS OPE_LEVEL, NVL(CI_MR_FP_SUG_CATA.NAME_LVLSUG, '') AS OPE_LEVEL_MC, NVL(CI_MR_FP_SUG_CATA.SD_CLASS_SUG, '') AS SSPB, NVL(CI_MR_FP_SUG_CATA.NAME_CLASS_SUG, '') AS SSPB_MC, NVL(CI_MR_FP_SUG_CATA.SORTNO, '') AS SFZYSS, NVL(CI_MR_FP_SUG_CATA.SD_INCITP, '') AS QKDJ, NVL(CI_MR_FP_SUG_CATA.NAME_INCITP, '') AS QKDJ_MC, NVL(CI_MR_FP_SUG_CATA.SD_METHOD_SUG, '') AS SSLX, NVL(CI_MR_FP_SUG_CATA.NAME_METHOD_SUG, '') AS SSLX_MC,NVL ( CI_MR_FP_SUG_CATA.ID_MRFPSUG, '' ) AS SSXH FROM HIS.CI_MR_FP_PAT_CATA LEFT JOIN HIS.CI_MR_FP_SUG_CATA ON HIS.CI_MR_FP_SUG_CATA.ID_ENT = HIS.CI_MR_FP_PAT_CATA.ID_ENT";
        return $this;
    }

    /**
     * feeDetailed表sql
     * @return $this
     */
    public function getFeeDetailedSql()
    {
        $this->sql = "SELECT NVL(BL_CG_IP.ID_CGIP, '') AS FYXH, NVL(BL_CG_IP.NAME_SRV, '') AS FYMC, NVL(BL_CG_IP.DT_ST, '') AS JFRQ, NVL(BL_CG_IP.QUAN, '') AS FYSL, NVL(BL_CG_IP.AMT_STD, '') AS FYDJ, NVL(BL_CG_IP.ID_DEP_OR, '') AS FYKS, NVL(BL_CG_IP.NAME_INCCAITM, '') AS FYGB, NVL(BL_CG_IP.ID_CGIP, '') AS JLXH, NVL(BL_CG_IP.ID_DEP_MP, '') AS ZXKS, NVL(BL_CG_IP.CODE_HPPR, '') AS YBBM, NVL(BL_CG_IP.FG_REFUND, '') AS TKBZ, NVL(BL_CG_IP.NAME_ACCOUNT, '') AS SYGB,(NVL ( BL_CG_IP.ID_CGIP, '' ) || '' || NVL (to_char (BL_CG_IP.\"ods_insert_time\", 'yyyymmddHH24miss'),'')) AS FYXH_NO FROM HIS.BL_CG_IP LEFT JOIN HIS.CI_MR_FP_PAT_CATA ON HIS.BL_CG_IP.ID_ENT = HIS.CI_MR_FP_PAT_CATA.ID_ENT ";
        return $this;
    }

    /**
     * yzb表sql
     * @return $this
     */
    public function getYzSql()
    {
        $this->sql =  "SELECT (NVL(CI_MR_FP_PAT_CATA.CODE_AMR_IP, '') || '' || NVL(CI_MR_FP_PAT_CATA.N_TIMES_INHOSPITAL, '')) AS ZYH, NVL(CI_ORDER.ID_EN, '') AS ZYH_ID, NVL(CI_ORDER.ID_OR, '') AS YZBXH, NVL(CI_ORDER.ID_DEP_OR, '') AS BRKS, NVL(CI_ORDER.ID_WG_OR, '') AS BRBQ, NVL(CI_ORDER.SD_SRVTP, '') AS YDYZLB, NVL(CASE CI_ORDER.FG_LONG WHEN 'Y' THEN 1 WHEN 'N' THEN 2 ELSE 3 END, '') AS YZQX, NVL(CI_ORDER.ID_DEP_OR, '') AS KZKS, NVL(CI_ORDER.ID_EMP_OR, '') AS KZYS, NVL(CI_ORDER.DT_ENTRY, '') AS KZSJ, NVL(CI_ORDER.NAME_OR, '') AS YZMC, NVL(CI_ORDER.ID_FREQ, '') AS YPCD, NVL(CI_ORDER.ID_FREQ, '') AS SYPC, NVL(CI_ORDER.ID_ROUTE, '') AS GYTJ, NVL(CI_ORDER.ID_ROUTE, '') AS YCJL, NVL(CASE CI_ORDER.FG_URGENT WHEN 'Y' THEN 1 WHEN 'N' THEN 0 ELSE 9 END, '') AS JJYZ, NVL(CI_ORDER.SD_SU_OR, '') AS YZZT, NVL(CI_ORDER.SD_SU_MP, '') AS ZXZT, NVL(CI_ORDER.ID_EMP_CHK, '') AS XZJDGH, NVL(CI_ORDER.DT_CHK, '') AS XZJDSJ, NVL( CASE CI_ORDER.FG_SKINTEST WHEN 'Y' THEN 1 WHEN 'N' THEN 0 ELSE 9 END, '' ) AS PSBZ,NVL( CASE CI_ORDER.FG_CANC WHEN 'Y' THEN 1 WHEN 'N' THEN 0 ELSE 9 END, '' ) AS ZFBS FROM HIS.CI_ORDER LEFT JOIN HIS.CI_MR_FP_PAT_CATA ON HIS.CI_ORDER.ID_EN = HIS.CI_MR_FP_PAT_CATA.ID_ENT ";
        return $this;
    }

    /**
     * 获取所属院区
     * @param $ksCode
     * @return $this
     */
    public function getYq($ksCode)
    {
        $this->sql =  "SELECT NVL(BD_UDIDOC.ID_UDIDOC, '') AS YQ_CODE FROM HIS.BD_UDIDOC  WHERE HIS.BD_UDIDOC.ID_UDIDOCLIST = '@@@@LL200000000002GJ' AND HIS.BD_UDIDOC.CODE = （SELECT NVL(BD_DEP.SD_HOSDISTRICT, '') AS SD_HOSDISTRICT FROM HIS.BD_DEP WHERE HIS.BD_DEP.CODE = {$ksCode}";
        return $this;
    }

    public function setCommonWhere($ID_ENT){
        $this->sql .= " WHERE HIS.CI_MR_FP_PAT_CATA.ID_ENT = {$ID_ENT}";
        return $this;
    }

    public function getResult()
    {
        $result = [];
        try {
            $data = oci_parse($this->connect, $this->sql);

            oci_execute($data, OCI_DEFAULT);

            while ($row = oci_fetch_assoc($data)) {
                $result[] = $row;
            }
            oci_free_statement($data);

        }catch (\Exception $exception){
            Log::error(__CLASS__."ODS查询失败,请检查链接或查询语句::".$exception->getMessage());
        }

        return $result;
    }
}
