<?php

return [
    'fileName' => '国考上报.xlsx',
    'title' => [
        'A01' => '',
        'A02' => '',
        'A48' => 'AAA28',
        'A49' => 'AAA29',
        'B12' => 'AAB01',
        'B15' => 'AAC01',
        'A47' => 'JKKH',
        'A46C' => 'AAA26C',
        'A11' => 'AAA01',
        'A12C' => 'AAA02C',
        'A13' => 'AAA03',
        'A14' => 'AAA04',
        'A15C' => 'AAA05C',
        'A21C' => 'AAA08C',
        'A38C' => 'AAA18C',
        'A19C' => 'AAA06C',
        'A20N' => 'SFZJLX',
        'A20' => 'AAA07',
        'A22' => 'AAA09',
        'A23C' => 'AAA43',
        'A24' => 'AAA12',
        'A25C' => 'AAA14C',
        'A26' => 'AAA48',
        'A27' => 'AAA51',
        'A28C' => 'AAA17C',
        'A29' => 'AAA19',
        'A30' => 'AAA20',
        'A31C' => 'AAA21C',
        'A32' => 'AAA22',
        'A33C' => 'AAA23C',
        'A34' => 'AAA24',
        'A35' => 'AAA25',
        'B38' => ['type' => 'ms','id' => 0 ,'key' => 'RJSS'],
        'B11C' => 'AAB06C',
        'B13C' => 'AAB02C',
        'B14' => 'BFRY',
        'B21C' => 'AAD01C',
        'B16C' => 'AAC02C',
        'B17' => 'AAC03',
        'B20' => 'AAC04',
        'C01C' => 'ABA01C',
        'C02N' => 'ABA01N',
        'C03C' => 'ICD10_ID1',
        'C04N' => 'ICD10_NAME',
        'C05C' => 'RYQK',
        'C06X01C' => ['type' => 'qd','id' => 0 ,'key' => 'ICD10_NAME'],
        'C07X01N' => ['type' => 'qd','id' => 0 ,'key' => 'ICD10_ID1'],
        'C08X01C' => ['type' => 'qd','id' => 0 ,'key' => 'RYQK'],
        'C06X02C' => ['type' => 'qd','id' => 1 ,'key' => 'ICD10_NAME'],
        'C07X02N' => ['type' => 'qd','id' => 1 ,'key' => 'ICD10_ID1'],
        'C08X02C' => ['type' => 'qd','id' => 1 ,'key' => 'RYQK'],
        'C06X03C' => ['type' => 'qd','id' => 2 ,'key' => 'ICD10_NAME'],
        'C07X03N' => ['type' => 'qd','id' => 2 ,'key' => 'ICD10_ID1'],
        'C08X03C' => ['type' => 'qd','id' => 2 ,'key' => 'RYQK'],
        'C06X04C' => ['type' => 'qd','id' => 3 ,'key' => 'ICD10_NAME'],
        'C07X04N' => ['type' => 'qd','id' => 3 ,'key' => 'ICD10_ID1'],
        'C08X04C' => ['type' => 'qd','id' => 3 ,'key' => 'RYQK'],
        'C06X05C' => ['type' => 'qd','id' => 4 ,'key' => 'ICD10_NAME'],
        'C07X05N' => ['type' => 'qd','id' => 4 ,'key' => 'ICD10_ID1'],
        'C08X05C' => ['type' => 'qd','id' => 4 ,'key' => 'RYQK'],
        'C06X06C' => ['type' => 'qd','id' => 5 ,'key' => 'ICD10_NAME'],
        'C07X06N' => ['type' => 'qd','id' => 5 ,'key' => 'ICD10_ID1'],
        'C08X06C' => ['type' => 'qd','id' => 5 ,'key' => 'RYQK'],
        'C06X07C' => ['type' => 'qd','id' => 6 ,'key' => 'ICD10_NAME'],
        'C07X07N' => ['type' => 'qd','id' => 6 ,'key' => 'ICD10_ID1'],
        'C08X07C' => ['type' => 'qd','id' => 6 ,'key' => 'RYQK'],
        'C06X08C' => ['type' => 'qd','id' => 7 ,'key' => 'ICD10_NAME'],
        'C07X08N' => ['type' => 'qd','id' => 7 ,'key' => 'ICD10_ID1'],
        'C08X08C' => ['type' => 'qd','id' => 7 ,'key' => 'RYQK'],
        'C06X09C' => ['type' => 'qd','id' => 8 ,'key' => 'ICD10_NAME'],
        'C07X09N' => ['type' => 'qd','id' => 8 ,'key' => 'ICD10_ID1'],
        'C08X09C' => ['type' => 'qd','id' => 8 ,'key' => 'RYQK'],
        'C06X10C' => ['type' => 'qd','id' => 9 ,'key' => 'ICD10_NAME'],
        'C07X10N' => ['type' => 'qd','id' => 9 ,'key' => 'ICD10_ID1'],
        'C08X10C' => ['type' => 'qd','id' => 9 ,'key' => 'RYQK'],
        'C06X11C' => ['type' => 'qd','id' => 10 ,'key' => 'ICD10_NAME'],
        'C07X11N' => ['type' => 'qd','id' => 10 ,'key' => 'ICD10_ID1'],
        'C08X11C' => ['type' => 'qd','id' => 10 ,'key' => 'RYQK'],
        'C06X12C'=> ['type' => 'qd','id' => 11 ,'key' => 'ICD10_NAME'],
        'C07X12N' => ['type' => 'qd','id' => 11 ,'key' => 'ICD10_ID1'],
        'C08X12C' => ['type' => 'qd','id' => 11 ,'key' => 'RYQK'],
        'C06X13C' => ['type' => 'qd','id' => 12 ,'key' => 'ICD10_NAME'],
        'C07X13N'=> ['type' => 'qd','id' => 12 ,'key' => 'ICD10_ID1'],
        'C08X13C' => ['type' => 'qd','id' => 12 ,'key' => 'RYQK'],
        'C06X14C' => ['type' => 'qd','id' => 13 ,'key' => 'ICD10_NAME'],
        'C07X14N' => ['type' => 'qd','id' => 13 ,'key' => 'ICD10_ID1'],
        'C08X14C'=> ['type' => 'qd','id' => 13 ,'key' => 'RYQK'],
        'C06X15C' => ['type' => 'qd','id' => 14 ,'key' => 'ICD10_NAME'],
        'C07X15N' => ['type' => 'qd','id' => 14 ,'key' => 'ICD10_ID1'],
        'C08X15C' => ['type' => 'qd','id' => 14 ,'key' => 'RYQK'],
        'C06X16C'=> ['type' => 'qd','id' => 15 ,'key' => 'ICD10_NAME'],
        'C07X16N' => ['type' => 'qd','id' => 15 ,'key' => 'ICD10_ID1'],
        'C08X16C' => ['type' => 'qd','id' => 15 ,'key' => 'RYQK'],
        'C06X17C' => ['type' => 'qd','id' => 16 ,'key' => 'ICD10_NAME'],
        'C07X17N'=> ['type' => 'qd','id' => 16 ,'key' => 'ICD10_ID1'],
        'C08X17C' => ['type' => 'qd','id' => 16 ,'key' => 'RYQK'],
        'C06X18C' => ['type' => 'qd','id' => 17 ,'key' => 'ICD10_NAME'],
        'C07X18N' => ['type' => 'qd','id' => 17 ,'key' => 'ICD10_ID1'],
        'C08X18C'=> ['type' => 'qd','id' => 17 ,'key' => 'RYQK'],
        'C06X19C' => ['type' => 'qd','id' => 18 ,'key' => 'ICD10_NAME'],
        'C07X19N' => ['type' => 'qd','id' => 18 ,'key' => 'ICD10_ID1'],
        'C08X19C' => ['type' => 'qd','id' => 18 ,'key' => 'RYQK'],
        'C06X20C'=> ['type' => 'qd','id' => 19 ,'key' => 'ICD10_NAME'],
        'C07X20N' => ['type' => 'qd','id' => 19 ,'key' => 'ICD10_ID1'],
        'C08X20C' => ['type' => 'qd','id' => 19 ,'key' => 'RYQK'],
        'C06X21C' => ['type' => 'qd','id' => 20 ,'key' => 'ICD10_NAME'],
        'C07X21N'=> ['type' => 'qd','id' => 20 ,'key' => 'ICD10_ID1'],
        'C08X21C' => ['type' => 'qd','id' => 20 ,'key' => 'RYQK'],
        'C06X22C' => ['type' => 'qd','id' => 21 ,'key' => 'ICD10_NAME'],
        'C07X22N' => ['type' => 'qd','id' => 21 ,'key' => 'ICD10_ID1'],
        'C08X22C'=> ['type' => 'qd','id' => 21 ,'key' => 'RYQK'],
        'C06X23C' => ['type' => 'qd','id' => 22 ,'key' => 'ICD10_NAME'],
        'C07X23N' => ['type' => 'qd','id' => 22 ,'key' => 'ICD10_ID1'],
        'C08X23C' => ['type' => 'qd','id' => 22 ,'key' => 'RYQK'],
        'C06X24C'=> ['type' => 'qd','id' => 23 ,'key' => 'ICD10_NAME'],
        'C07X24N' => ['type' => 'qd','id' => 23 ,'key' => 'ICD10_ID1'],
        'C08X24C' => ['type' => 'qd','id' => 23 ,'key' => 'RYQK'],
        'C06X25C' => ['type' => 'qd','id' => 24 ,'key' => 'ICD10_NAME'],
        'C07X25N'=> ['type' => 'qd','id' => 24 ,'key' => 'ICD10_ID1'],
        'C08X25C' => ['type' => 'qd','id' => 24 ,'key' => 'RYQK'],
        'C06X26C' => ['type' => 'qd','id' => 25 ,'key' => 'ICD10_NAME'],
        'C07X26N' => ['type' => 'qd','id' => 25 ,'key' => 'ICD10_ID1'],
        'C08X26C'=> ['type' => 'qd','id' => 25 ,'key' => 'RYQK'],
        'C06X27C' => ['type' => 'qd','id' => 26 ,'key' => 'ICD10_NAME'],
        'C07X27N' => ['type' => 'qd','id' => 26 ,'key' => 'ICD10_ID1'],
        'C08X27C' => ['type' => 'qd','id' => 26 ,'key' => 'RYQK'],
        'C06X28C'=> ['type' => 'qd','id' => 27 ,'key' => 'ICD10_NAME'],
        'C07X28N' => ['type' => 'qd','id' => 27 ,'key' => 'ICD10_ID1'],
        'C08X28C' => ['type' => 'qd','id' => 27 ,'key' => 'RYQK'],
        'C06X29C' => ['type' => 'qd','id' => 28 ,'key' => 'ICD10_NAME'],
        'C07X29N'=> ['type' => 'qd','id' => 28 ,'key' => 'ICD10_ID1'],
        'C08X29C' => ['type' => 'qd','id' => 28 ,'key' => 'RYQK'],
        'C06X30C' => ['type' => 'qd','id' => 29 ,'key' => 'ICD10_NAME'],
        'C07X30N' => ['type' => 'qd','id' => 29 ,'key' => 'ICD10_ID1'],
        'C08X30C'=> ['type' => 'qd','id' => 29 ,'key' => 'RYQK'],
        'C06X31C' => ['type' => 'qd','id' => 30 ,'key' => 'ICD10_NAME'],
        'C07X31N' => ['type' => 'qd','id' => 30 ,'key' => 'ICD10_ID1'],
        'C08X31C' => ['type' => 'qd','id' => 30 ,'key' => 'RYQK'],
        'C06X32C'=> ['type' => 'qd','id' => 31 ,'key' => 'ICD10_NAME'],
        'C07X32N' => ['type' => 'qd','id' => 31 ,'key' => 'ICD10_ID1'],
        'C08X32C' => ['type' => 'qd','id' => 31 ,'key' => 'RYQK'],
        'C06X33C' => ['type' => 'qd','id' => 32 ,'key' => 'ICD10_NAME'],
        'C07X33N'=> ['type' => 'qd','id' => 32 ,'key' => 'ICD10_ID1'],
        'C08X33C' => ['type' => 'qd','id' => 32 ,'key' => 'RYQK'],
        'C06X34C' => ['type' => 'qd','id' => 33 ,'key' => 'ICD10_NAME'],
        'C07X34N' => ['type' => 'qd','id' => 33 ,'key' => 'ICD10_ID1'],
        'C08X34C'=> ['type' => 'qd','id' => 33 ,'key' => 'RYQK'],
        'C06X35C' => ['type' => 'qd','id' => 34 ,'key' => 'ICD10_NAME'],
        'C07X35N' => ['type' => 'qd','id' => 34 ,'key' => 'ICD10_ID1'],
        'C08X35C' => ['type' => 'qd','id' => 34 ,'key' => 'RYQK'],
        'C06X36C'=> ['type' => 'qd','id' => 35 ,'key' => 'ICD10_NAME'],
        'C07X36N' => ['type' => 'qd','id' => 35 ,'key' => 'ICD10_ID1'],
        'C08X36C' => ['type' => 'qd','id' => 35 ,'key' => 'RYQK'],
        'C06X37C' => ['type' => 'qd','id' => 36 ,'key' => 'ICD10_NAME'],
        'C07X37N'=> ['type' => 'qd','id' => 36 ,'key' => 'ICD10_ID1'],
        'C08X37C' => ['type' => 'qd','id' => 36 ,'key' => 'RYQK'],
        'C06X38C' => ['type' => 'qd','id' => 37 ,'key' => 'ICD10_NAME'],
        'C07X38N' => ['type' => 'qd','id' => 37 ,'key' => 'ICD10_ID1'],
        'C08X38C'=> ['type' => 'qd','id' => 37 ,'key' => 'RYQK'],
        'C06X39C' => ['type' => 'qd','id' => 38 ,'key' => 'ICD10_NAME'],
        'C07X39N' => ['type' => 'qd','id' => 38 ,'key' => 'ICD10_ID1'],
        'C08X39C' => ['type' => 'qd','id' => 38 ,'key' => 'RYQK'],
        'C06X40C'=> ['type' => 'qd','id' => 39 ,'key' => 'ICD10_NAME'],
        'C07X40N' => ['type' => 'qd','id' => 39 ,'key' => 'ICD10_ID1'],
        'C08X40C' => ['type' => 'qd','id' => 39 ,'key' => 'RYQK'],
        'C09C' => 'ABF01C',
        'C10N'=> 'ABF01N',
        'C11' => 'ABF04',
        'C12C' => 'ABG01C',
        'C13N' => 'ABG01N',
        'C24C'=> 'AEB02C',
        'C25' => 'AEB01',
        'B22' => 'AEE01',
        'B22C' => 'AEE01_CODE',
        'B23'=> 'ZHFZRYSXM',
        'B23C' => 'ZHFZRYS',
        'B24' => 'ZZYSXM',
        'B24C' => 'ZZYSBM',
        'B25'=> 'ZYYSXM',
        'B25C' => 'ZYYSBM',
        'B26' => 'ZRHS',
        'B26C' => 'ZRHSBM',
        'B27'=> 'AEE05',
        'B28' => 'AEE07',
        'B29' => 'BMY',
        'B30C' => 'AED01C',
        'B31'=> 'AED02',
        'B32' => 'ZKHS',
        'B33' => 'AED04',
        'C34C' => 'AEI01C',
        'C26C'=> 'AEG01C',
        'C27C' => 'AEG02C',
        'C14X01C' => ['type' => 'ms','id' => 0 ,'key' => 'ICD9_ID1'],
        'C15X01N' => ['type' => 'ms','id' => 0 ,'key' => 'ICD9_NAME'],
        'C16X01'=> ['type' => 'ms','id' => 0 ,'key' => 'OPE_DATE'],
        'C17X01' => ['type' => 'ms','id' => 0 ,'key' => 'OPE_LEVEL'],
        'C18X01' => ['type' => 'ms','id' => 0 ,'key' => 'OPE_MAN_NAME'],
        'C19X01' => ['type' => 'ms','id' => 0 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C20X01'=> ['type' => 'ms','id' => 0 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C21X01C' => ['type' => 'ms','id' => 0 ,'key' => 'INCISION_GRADE_ID'],
        'C22X01C' => ['type' => 'ms','id' => 0 ,'key' => 'HOCUS_WAY_ID'],
        'C23X01' => ['type' => 'ms','id' => 0 ,'key' => 'HOCUS_MAN_NAME'],
        'C35X01C'=> ['type' => 'qs','id' => 0 ,'key' => 'ICD9_ID1'],
        'C36X01N' => ['type' => 'qs','id' => 0 ,'key' => 'ICD9_NAME'],
        'C37X01' => ['type' => 'qs','id' => 0 ,'key' => 'OPE_DATE'],
        'C38X01' => ['type' => 'qs','id' => 0 ,'key' => 'OPE_LEVEL'],
        'C39X01'=> ['type' => 'qs','id' => 0 ,'key' => 'OPE_MAN_NAME'],
        'C40X01' => ['type' => 'qs','id' => 0 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X01' => ['type' => 'qs','id' => 0 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X01C' => ['type' => 'qs','id' => 0 ,'key' => 'INCISION_GRADE_ID'],
        'C43X01C'=> ['type' => 'qs','id' => 0 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X01' => ['type' => 'qs','id' => 0 ,'key' => 'HOCUS_WAY_ID'],
        'C35X02C'=> ['type' => 'qs','id' => 1 ,'key' => 'ICD9_ID1'],
        'C36X02N' => ['type' => 'qs','id' => 1 ,'key' => 'ICD9_NAME'],
        'C37X02' => ['type' => 'qs','id' => 1 ,'key' => 'OPE_DATE'],
        'C38X02' => ['type' => 'qs','id' => 1 ,'key' => 'OPE_LEVEL'],
        'C39X02'=> ['type' => 'qs','id' => 1 ,'key' => 'OPE_MAN_NAME'],
        'C40X02' => ['type' => 'qs','id' => 1 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X02' => ['type' => 'qs','id' => 1 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X02C' => ['type' => 'qs','id' => 1 ,'key' => 'INCISION_GRADE_ID'],
        'C43X02C'=> ['type' => 'qs','id' => 1 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X02' => ['type' => 'qs','id' => 1 ,'key' => 'HOCUS_WAY_ID'],
        'C35X03C'=> ['type' => 'qs','id' => 2 ,'key' => 'ICD9_ID1'],
        'C36X03N' => ['type' => 'qs','id' => 2 ,'key' => 'ICD9_NAME'],
        'C37X03' => ['type' => 'qs','id' => 2 ,'key' => 'OPE_DATE'],
        'C38X03' => ['type' => 'qs','id' => 2 ,'key' => 'OPE_LEVEL'],
        'C39X03'=> ['type' => 'qs','id' => 2 ,'key' => 'OPE_MAN_NAME'],
        'C40X03' => ['type' => 'qs','id' => 2 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X03' => ['type' => 'qs','id' => 2 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X03C' => ['type' => 'qs','id' => 2 ,'key' => 'INCISION_GRADE_ID'],
        'C43X03C'=> ['type' => 'qs','id' => 2 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X03' => ['type' => 'qs','id' => 2 ,'key' => 'HOCUS_WAY_ID'],
        'C35X04C'=> ['type' => 'qs','id' => 3 ,'key' => 'ICD9_ID1'],
        'C36X04N' => ['type' => 'qs','id' => 3 ,'key' => 'ICD9_NAME'],
        'C37X04' => ['type' => 'qs','id' => 3 ,'key' => 'OPE_DATE'],
        'C38X04' => ['type' => 'qs','id' => 3 ,'key' => 'OPE_LEVEL'],
        'C39X04'=> ['type' => 'qs','id' => 3 ,'key' => 'OPE_MAN_NAME'],
        'C40X04' => ['type' => 'qs','id' => 3 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X04' => ['type' => 'qs','id' => 3 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X04C' => ['type' => 'qs','id' => 3 ,'key' => 'INCISION_GRADE_ID'],
        'C43X04C'=> ['type' => 'qs','id' => 3 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X04' => ['type' => 'qs','id' => 3 ,'key' => 'HOCUS_WAY_ID'],
        'C35X05C'=> ['type' => 'qs','id' => 4 ,'key' => 'ICD9_ID1'],
        'C36X05N' => ['type' => 'qs','id' => 4 ,'key' => 'ICD9_NAME'],
        'C37X05' => ['type' => 'qs','id' => 4 ,'key' => 'OPE_DATE'],
        'C38X05' => ['type' => 'qs','id' => 4 ,'key' => 'OPE_LEVEL'],
        'C39X05'=> ['type' => 'qs','id' => 4 ,'key' => 'OPE_MAN_NAME'],
        'C40X05' => ['type' => 'qs','id' => 4 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X05' => ['type' => 'qs','id' => 4 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X05C' => ['type' => 'qs','id' => 4 ,'key' => 'INCISION_GRADE_ID'],
        'C43X05C'=> ['type' => 'qs','id' => 4 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X05' => ['type' => 'qs','id' => 4 ,'key' => 'HOCUS_WAY_ID'],
        'C35X06C'=> ['type' => 'qs','id' => 5 ,'key' => 'ICD9_ID1'],
        'C36X06N' => ['type' => 'qs','id' => 5 ,'key' => 'ICD9_NAME'],
        'C37X06' => ['type' => 'qs','id' => 5 ,'key' => 'OPE_DATE'],
        'C38X06' => ['type' => 'qs','id' => 5 ,'key' => 'OPE_LEVEL'],
        'C39X06'=> ['type' => 'qs','id' => 5 ,'key' => 'OPE_MAN_NAME'],
        'C40X06' => ['type' => 'qs','id' => 5 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X06' => ['type' => 'qs','id' => 5 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X06C' => ['type' => 'qs','id' => 5 ,'key' => 'INCISION_GRADE_ID'],
        'C43X06C'=> ['type' => 'qs','id' => 5 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X06' => ['type' => 'qs','id' => 5 ,'key' => 'HOCUS_WAY_ID'],
        'C35X07C'=> ['type' => 'qs','id' => 6 ,'key' => 'ICD9_ID1'],
        'C36X07N' => ['type' => 'qs','id' => 6 ,'key' => 'ICD9_NAME'],
        'C37X07' => ['type' => 'qs','id' => 6 ,'key' => 'OPE_DATE'],
        'C38X07' => ['type' => 'qs','id' => 6 ,'key' => 'OPE_LEVEL'],
        'C39X07'=> ['type' => 'qs','id' => 6 ,'key' => 'OPE_MAN_NAME'],
        'C40X07' => ['type' => 'qs','id' => 6 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X07' => ['type' => 'qs','id' => 6 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X07C' => ['type' => 'qs','id' => 6 ,'key' => 'INCISION_GRADE_ID'],
        'C43X07C'=> ['type' => 'qs','id' => 6 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X07' => ['type' => 'qs','id' => 6 ,'key' => 'HOCUS_WAY_ID'],
        'C35X08C'=> ['type' => 'qs','id' => 7 ,'key' => 'ICD9_ID1'],
        'C36X08N' => ['type' => 'qs','id' => 7 ,'key' => 'ICD9_NAME'],
        'C37X08' => ['type' => 'qs','id' => 7 ,'key' => 'OPE_DATE'],
        'C38X08' => ['type' => 'qs','id' => 7 ,'key' => 'OPE_LEVEL'],
        'C39X08'=> ['type' => 'qs','id' => 7 ,'key' => 'OPE_MAN_NAME'],
        'C40X08' => ['type' => 'qs','id' => 7 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X08' => ['type' => 'qs','id' => 7 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X08C' => ['type' => 'qs','id' => 7 ,'key' => 'INCISION_GRADE_ID'],
        'C43X08C'=> ['type' => 'qs','id' => 7 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X08' => ['type' => 'qs','id' => 7 ,'key' => 'HOCUS_WAY_ID'],
        'C35X09C'=> ['type' => 'qs','id' => 8 ,'key' => 'ICD9_ID1'],
        'C36X09N' => ['type' => 'qs','id' => 8 ,'key' => 'ICD9_NAME'],
        'C37X09' => ['type' => 'qs','id' => 8 ,'key' => 'OPE_DATE'],
        'C38X09' => ['type' => 'qs','id' => 8 ,'key' => 'OPE_LEVEL'],
        'C39X09'=> ['type' => 'qs','id' => 8 ,'key' => 'OPE_MAN_NAME'],
        'C40X09' => ['type' => 'qs','id' => 8 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X09' => ['type' => 'qs','id' => 8 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X09C' => ['type' => 'qs','id' => 8 ,'key' => 'INCISION_GRADE_ID'],
        'C43X09C'=> ['type' => 'qs','id' => 8 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X09' => ['type' => 'qs','id' => 8 ,'key' => 'HOCUS_WAY_ID'],
        'C35X10C'=> ['type' => 'qs','id' => 9 ,'key' => 'ICD9_ID1'],
        'C36X10N' => ['type' => 'qs','id' => 9 ,'key' => 'ICD9_NAME'],
        'C37X10' => ['type' => 'qs','id' => 9 ,'key' => 'OPE_DATE'],
        'C38X10' => ['type' => 'qs','id' => 9 ,'key' => 'OPE_LEVEL'],
        'C39X10'=> ['type' => 'qs','id' => 9 ,'key' => 'OPE_MAN_NAME'],
        'C40X10' => ['type' => 'qs','id' => 9 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X10' => ['type' => 'qs','id' => 9 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X10C' => ['type' => 'qs','id' => 9 ,'key' => 'INCISION_GRADE_ID'],
        'C43X10C'=> ['type' => 'qs','id' => 9 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X10' => ['type' => 'qs','id' => 9 ,'key' => 'HOCUS_WAY_ID'],
        'C35X11C'=> ['type' => 'qs','id' => 10 ,'key' => 'ICD9_ID1'],
        'C36X11N' => ['type' => 'qs','id' => 10 ,'key' => 'ICD9_NAME'],
        'C37X11' => ['type' => 'qs','id' => 10 ,'key' => 'OPE_DATE'],
        'C38X11' => ['type' => 'qs','id' => 10 ,'key' => 'OPE_LEVEL'],
        'C39X11'=> ['type' => 'qs','id' => 10 ,'key' => 'OPE_MAN_NAME'],
        'C40X11' => ['type' => 'qs','id' => 10 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X11' => ['type' => 'qs','id' => 10 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X11C' => ['type' => 'qs','id' => 10 ,'key' => 'INCISION_GRADE_ID'],
        'C43X11C'=> ['type' => 'qs','id' => 10 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X11' => ['type' => 'qs','id' => 10 ,'key' => 'HOCUS_WAY_ID'],
        'C35X12C'=> ['type' => 'qs','id' => 11 ,'key' => 'ICD9_ID1'],
        'C36X12N' => ['type' => 'qs','id' => 11 ,'key' => 'ICD9_NAME'],
        'C37X12' => ['type' => 'qs','id' => 11 ,'key' => 'OPE_DATE'],
        'C38X12' => ['type' => 'qs','id' => 11 ,'key' => 'OPE_LEVEL'],
        'C39X12'=> ['type' => 'qs','id' => 11 ,'key' => 'OPE_MAN_NAME'],
        'C40X12' => ['type' => 'qs','id' => 11 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X12' => ['type' => 'qs','id' => 11 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X12C' => ['type' => 'qs','id' => 11 ,'key' => 'INCISION_GRADE_ID'],
        'C43X12C'=> ['type' => 'qs','id' => 11 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X12' => ['type' => 'qs','id' => 11 ,'key' => 'HOCUS_WAY_ID'],
        'C35X13C'=> ['type' => 'qs','id' => 12 ,'key' => 'ICD9_ID1'],
        'C36X13N' => ['type' => 'qs','id' => 12 ,'key' => 'ICD9_NAME'],
        'C37X13' => ['type' => 'qs','id' => 12 ,'key' => 'OPE_DATE'],
        'C38X13' => ['type' => 'qs','id' => 12 ,'key' => 'OPE_LEVEL'],
        'C39X13'=> ['type' => 'qs','id' => 12 ,'key' => 'OPE_MAN_NAME'],
        'C40X13' => ['type' => 'qs','id' => 12 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X13' => ['type' => 'qs','id' => 12 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X13C' => ['type' => 'qs','id' => 12 ,'key' => 'INCISION_GRADE_ID'],
        'C43X13C'=> ['type' => 'qs','id' => 12 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X13' => ['type' => 'qs','id' => 12 ,'key' => 'HOCUS_WAY_ID'],
        'C35X14C'=> ['type' => 'qs','id' => 13 ,'key' => 'ICD9_ID1'],
        'C36X14N' => ['type' => 'qs','id' => 13 ,'key' => 'ICD9_NAME'],
        'C37X14' => ['type' => 'qs','id' => 13 ,'key' => 'OPE_DATE'],
        'C38X14' => ['type' => 'qs','id' => 13 ,'key' => 'OPE_LEVEL'],
        'C39X14'=> ['type' => 'qs','id' => 13 ,'key' => 'OPE_MAN_NAME'],
        'C40X14' => ['type' => 'qs','id' => 13 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X14' => ['type' => 'qs','id' => 13 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X14C' => ['type' => 'qs','id' => 13 ,'key' => 'INCISION_GRADE_ID'],
        'C43X14C'=> ['type' => 'qs','id' => 13 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X14' => ['type' => 'qs','id' => 13 ,'key' => 'HOCUS_WAY_ID'],
        'C35X15C'=> ['type' => 'qs','id' => 14 ,'key' => 'ICD9_ID1'],
        'C36X15N' => ['type' => 'qs','id' => 14 ,'key' => 'ICD9_NAME'],
        'C37X15' => ['type' => 'qs','id' => 14 ,'key' => 'OPE_DATE'],
        'C38X15' => ['type' => 'qs','id' => 14 ,'key' => 'OPE_LEVEL'],
        'C39X15'=> ['type' => 'qs','id' => 14 ,'key' => 'OPE_MAN_NAME'],
        'C40X15' => ['type' => 'qs','id' => 14 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X15' => ['type' => 'qs','id' => 14 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X15C' => ['type' => 'qs','id' => 14 ,'key' => 'INCISION_GRADE_ID'],
        'C43X15C'=> ['type' => 'qs','id' => 14 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X15' => ['type' => 'qs','id' => 14 ,'key' => 'HOCUS_WAY_ID'],
        'C35X16C'=> ['type' => 'qs','id' => 15 ,'key' => 'ICD9_ID1'],
        'C36X16N' => ['type' => 'qs','id' => 15 ,'key' => 'ICD9_NAME'],
        'C37X16' => ['type' => 'qs','id' => 15 ,'key' => 'OPE_DATE'],
        'C38X16' => ['type' => 'qs','id' => 15 ,'key' => 'OPE_LEVEL'],
        'C39X16'=> ['type' => 'qs','id' => 15 ,'key' => 'OPE_MAN_NAME'],
        'C40X16' => ['type' => 'qs','id' => 15 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X16' => ['type' => 'qs','id' => 15 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X16C' => ['type' => 'qs','id' => 15 ,'key' => 'INCISION_GRADE_ID'],
        'C43X16C'=> ['type' => 'qs','id' => 15 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X16' => ['type' => 'qs','id' => 15 ,'key' => 'HOCUS_WAY_ID'],
        'C35X17C'=> ['type' => 'qs','id' => 16 ,'key' => 'ICD9_ID1'],
        'C36X17N' => ['type' => 'qs','id' => 16 ,'key' => 'ICD9_NAME'],
        'C37X17' => ['type' => 'qs','id' => 16 ,'key' => 'OPE_DATE'],
        'C38X17' => ['type' => 'qs','id' => 16 ,'key' => 'OPE_LEVEL'],
        'C39X17'=> ['type' => 'qs','id' => 16 ,'key' => 'OPE_MAN_NAME'],
        'C40X17' => ['type' => 'qs','id' => 16 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X17' => ['type' => 'qs','id' => 16 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X17C' => ['type' => 'qs','id' => 16 ,'key' => 'INCISION_GRADE_ID'],
        'C43X17C'=> ['type' => 'qs','id' => 16 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X17' => ['type' => 'qs','id' => 16 ,'key' => 'HOCUS_WAY_ID'],
        'C35X18C'=> ['type' => 'qs','id' => 17 ,'key' => 'ICD9_ID1'],
        'C36X18N' => ['type' => 'qs','id' => 17 ,'key' => 'ICD9_NAME'],
        'C37X18' => ['type' => 'qs','id' => 17 ,'key' => 'OPE_DATE'],
        'C38X18' => ['type' => 'qs','id' => 17 ,'key' => 'OPE_LEVEL'],
        'C39X18'=> ['type' => 'qs','id' => 17 ,'key' => 'OPE_MAN_NAME'],
        'C40X18' => ['type' => 'qs','id' => 17 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X18' => ['type' => 'qs','id' => 17 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X18C' => ['type' => 'qs','id' => 17 ,'key' => 'INCISION_GRADE_ID'],
        'C43X18C'=> ['type' => 'qs','id' => 17 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X18' => ['type' => 'qs','id' => 17 ,'key' => 'HOCUS_WAY_ID'],
        'C35X19C'=> ['type' => 'qs','id' => 18 ,'key' => 'ICD9_ID1'],
        'C36X19N' => ['type' => 'qs','id' => 18 ,'key' => 'ICD9_NAME'],
        'C37X19' => ['type' => 'qs','id' => 18 ,'key' => 'OPE_DATE'],
        'C38X19' => ['type' => 'qs','id' => 18 ,'key' => 'OPE_LEVEL'],
        'C39X19'=> ['type' => 'qs','id' => 18 ,'key' => 'OPE_MAN_NAME'],
        'C40X19' => ['type' => 'qs','id' => 18 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X19' => ['type' => 'qs','id' => 18 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X19C' => ['type' => 'qs','id' => 18 ,'key' => 'INCISION_GRADE_ID'],
        'C43X19C'=> ['type' => 'qs','id' => 18 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X19' => ['type' => 'qs','id' => 18 ,'key' => 'HOCUS_WAY_ID'],
        'C35X20C'=> ['type' => 'qs','id' => 19 ,'key' => 'ICD9_ID1'],
        'C36X20N' => ['type' => 'qs','id' => 19 ,'key' => 'ICD9_NAME'],
        'C37X20' => ['type' => 'qs','id' => 19 ,'key' => 'OPE_DATE'],
        'C38X20' => ['type' => 'qs','id' => 19 ,'key' => 'OPE_LEVEL'],
        'C39X20'=> ['type' => 'qs','id' => 19 ,'key' => 'OPE_MAN_NAME'],
        'C40X20' => ['type' => 'qs','id' => 19 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X20' => ['type' => 'qs','id' => 19 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X20C' => ['type' => 'qs','id' => 19 ,'key' => 'INCISION_GRADE_ID'],
        'C43X20C'=> ['type' => 'qs','id' => 19 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X20' => ['type' => 'qs','id' => 19 ,'key' => 'HOCUS_WAY_ID'],
        'C35X21C'=> ['type' => 'qs','id' => 20 ,'key' => 'ICD9_ID1'],
        'C36X21N' => ['type' => 'qs','id' => 20 ,'key' => 'ICD9_NAME'],
        'C37X21' => ['type' => 'qs','id' => 20 ,'key' => 'OPE_DATE'],
        'C38X21' => ['type' => 'qs','id' => 20 ,'key' => 'OPE_LEVEL'],
        'C39X21'=> ['type' => 'qs','id' => 20 ,'key' => 'OPE_MAN_NAME'],
        'C40X21' => ['type' => 'qs','id' => 20 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X21' => ['type' => 'qs','id' => 20 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X21C' => ['type' => 'qs','id' => 20 ,'key' => 'INCISION_GRADE_ID'],
        'C43X21C'=> ['type' => 'qs','id' => 20 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X21' => ['type' => 'qs','id' => 20 ,'key' => 'HOCUS_WAY_ID'],
        'C35X22C'=> ['type' => 'qs','id' => 21 ,'key' => 'ICD9_ID1'],
        'C36X22N' => ['type' => 'qs','id' => 21 ,'key' => 'ICD9_NAME'],
        'C37X22' => ['type' => 'qs','id' => 21 ,'key' => 'OPE_DATE'],
        'C38X22' => ['type' => 'qs','id' => 21 ,'key' => 'OPE_LEVEL'],
        'C39X22'=> ['type' => 'qs','id' => 21 ,'key' => 'OPE_MAN_NAME'],
        'C40X22' => ['type' => 'qs','id' => 21 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X22' => ['type' => 'qs','id' => 21 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X22C' => ['type' => 'qs','id' => 21 ,'key' => 'INCISION_GRADE_ID'],
        'C43X22C'=> ['type' => 'qs','id' => 21 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X22' => ['type' => 'qs','id' => 21 ,'key' => 'HOCUS_WAY_ID'],
        'C35X23C'=> ['type' => 'qs','id' => 22 ,'key' => 'ICD9_ID1'],
        'C36X23N' => ['type' => 'qs','id' => 22 ,'key' => 'ICD9_NAME'],
        'C37X23' => ['type' => 'qs','id' => 22 ,'key' => 'OPE_DATE'],
        'C38X23' => ['type' => 'qs','id' => 22 ,'key' => 'OPE_LEVEL'],
        'C39X23'=> ['type' => 'qs','id' => 22 ,'key' => 'OPE_MAN_NAME'],
        'C40X23' => ['type' => 'qs','id' => 22 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X23' => ['type' => 'qs','id' => 22 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X23C' => ['type' => 'qs','id' => 22 ,'key' => 'INCISION_GRADE_ID'],
        'C43X23C'=> ['type' => 'qs','id' => 22 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X23' => ['type' => 'qs','id' => 22 ,'key' => 'HOCUS_WAY_ID'],
        'C35X24C'=> ['type' => 'qs','id' => 23 ,'key' => 'ICD9_ID1'],
        'C36X24N' => ['type' => 'qs','id' => 23 ,'key' => 'ICD9_NAME'],
        'C37X24' => ['type' => 'qs','id' => 23 ,'key' => 'OPE_DATE'],
        'C38X24' => ['type' => 'qs','id' => 23 ,'key' => 'OPE_LEVEL'],
        'C39X24'=> ['type' => 'qs','id' => 23 ,'key' => 'OPE_MAN_NAME'],
        'C40X24' => ['type' => 'qs','id' => 23 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X24' => ['type' => 'qs','id' => 23 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X24C' => ['type' => 'qs','id' => 23 ,'key' => 'INCISION_GRADE_ID'],
        'C43X24C'=> ['type' => 'qs','id' => 23 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X24' => ['type' => 'qs','id' => 23 ,'key' => 'HOCUS_WAY_ID'],
        'C35X25C'=> ['type' => 'qs','id' => 24 ,'key' => 'ICD9_ID1'],
        'C36X25N' => ['type' => 'qs','id' => 24 ,'key' => 'ICD9_NAME'],
        'C37X25' => ['type' => 'qs','id' => 24 ,'key' => 'OPE_DATE'],
        'C38X25' => ['type' => 'qs','id' => 24 ,'key' => 'OPE_LEVEL'],
        'C39X25'=> ['type' => 'qs','id' => 24 ,'key' => 'OPE_MAN_NAME'],
        'C40X25' => ['type' => 'qs','id' => 24 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X25' => ['type' => 'qs','id' => 24 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X25C' => ['type' => 'qs','id' => 24 ,'key' => 'INCISION_GRADE_ID'],
        'C43X25C'=> ['type' => 'qs','id' => 24 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X25' => ['type' => 'qs','id' => 24 ,'key' => 'HOCUS_WAY_ID'],
        'C35X26C'=> ['type' => 'qs','id' => 25 ,'key' => 'ICD9_ID1'],
        'C36X26N' => ['type' => 'qs','id' => 25 ,'key' => 'ICD9_NAME'],
        'C37X26' => ['type' => 'qs','id' => 25 ,'key' => 'OPE_DATE'],
        'C38X26' => ['type' => 'qs','id' => 25 ,'key' => 'OPE_LEVEL'],
        'C39X26'=> ['type' => 'qs','id' => 25 ,'key' => 'OPE_MAN_NAME'],
        'C40X26' => ['type' => 'qs','id' => 25 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X26' => ['type' => 'qs','id' => 25 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X26C' => ['type' => 'qs','id' => 25 ,'key' => 'INCISION_GRADE_ID'],
        'C43X26C'=> ['type' => 'qs','id' => 25 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X26' => ['type' => 'qs','id' => 25 ,'key' => 'HOCUS_WAY_ID'],
        'C35X27C'=> ['type' => 'qs','id' => 26 ,'key' => 'ICD9_ID1'],
        'C36X27N' => ['type' => 'qs','id' => 26 ,'key' => 'ICD9_NAME'],
        'C37X27' => ['type' => 'qs','id' => 26 ,'key' => 'OPE_DATE'],
        'C38X27' => ['type' => 'qs','id' => 26 ,'key' => 'OPE_LEVEL'],
        'C39X27'=> ['type' => 'qs','id' => 26 ,'key' => 'OPE_MAN_NAME'],
        'C40X27' => ['type' => 'qs','id' => 26 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X27' => ['type' => 'qs','id' => 26 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X27C' => ['type' => 'qs','id' => 26 ,'key' => 'INCISION_GRADE_ID'],
        'C43X27C'=> ['type' => 'qs','id' => 26 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X27' => ['type' => 'qs','id' => 26 ,'key' => 'HOCUS_WAY_ID'],
        'C35X28C'=> ['type' => 'qs','id' => 27 ,'key' => 'ICD9_ID1'],
        'C36X28N' => ['type' => 'qs','id' => 27 ,'key' => 'ICD9_NAME'],
        'C37X28' => ['type' => 'qs','id' => 27 ,'key' => 'OPE_DATE'],
        'C38X28' => ['type' => 'qs','id' => 27 ,'key' => 'OPE_LEVEL'],
        'C39X28'=> ['type' => 'qs','id' => 27 ,'key' => 'OPE_MAN_NAME'],
        'C40X28' => ['type' => 'qs','id' => 27 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X28' => ['type' => 'qs','id' => 27 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X28C' => ['type' => 'qs','id' => 27 ,'key' => 'INCISION_GRADE_ID'],
        'C43X28C'=> ['type' => 'qs','id' => 27 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X28' => ['type' => 'qs','id' => 27 ,'key' => 'HOCUS_WAY_ID'],
        'C35X29C'=> ['type' => 'qs','id' => 28 ,'key' => 'ICD9_ID1'],
        'C36X29N' => ['type' => 'qs','id' => 28 ,'key' => 'ICD9_NAME'],
        'C37X29' => ['type' => 'qs','id' => 28 ,'key' => 'OPE_DATE'],
        'C38X29' => ['type' => 'qs','id' => 28 ,'key' => 'OPE_LEVEL'],
        'C39X29'=> ['type' => 'qs','id' => 28 ,'key' => 'OPE_MAN_NAME'],
        'C40X29' => ['type' => 'qs','id' => 28 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X29' => ['type' => 'qs','id' => 28 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X29C' => ['type' => 'qs','id' => 28 ,'key' => 'INCISION_GRADE_ID'],
        'C43X29C'=> ['type' => 'qs','id' => 28 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X29' => ['type' => 'qs','id' => 28 ,'key' => 'HOCUS_WAY_ID'],
        'C35X30C'=> ['type' => 'qs','id' => 29 ,'key' => 'ICD9_ID1'],
        'C36X30N' => ['type' => 'qs','id' => 29 ,'key' => 'ICD9_NAME'],
        'C37X30' => ['type' => 'qs','id' => 29 ,'key' => 'OPE_DATE'],
        'C38X30' => ['type' => 'qs','id' => 29 ,'key' => 'OPE_LEVEL'],
        'C39X30'=> ['type' => 'qs','id' => 29 ,'key' => 'OPE_MAN_NAME'],
        'C40X30' => ['type' => 'qs','id' => 29 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X30' => ['type' => 'qs','id' => 29 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X30C' => ['type' => 'qs','id' => 29 ,'key' => 'INCISION_GRADE_ID'],
        'C43X30C'=> ['type' => 'qs','id' => 29 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X30' => ['type' => 'qs','id' => 29 ,'key' => 'HOCUS_WAY_ID'],
        'C35X31C'=> ['type' => 'qs','id' => 30 ,'key' => 'ICD9_ID1'],
        'C36X31N' => ['type' => 'qs','id' => 30 ,'key' => 'ICD9_NAME'],
        'C37X31' => ['type' => 'qs','id' => 30 ,'key' => 'OPE_DATE'],
        'C38X31' => ['type' => 'qs','id' => 30 ,'key' => 'OPE_LEVEL'],
        'C39X31'=> ['type' => 'qs','id' => 30 ,'key' => 'OPE_MAN_NAME'],
        'C40X31' => ['type' => 'qs','id' => 30 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X31' => ['type' => 'qs','id' => 30 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X31C' => ['type' => 'qs','id' => 30 ,'key' => 'INCISION_GRADE_ID'],
        'C43X31C'=> ['type' => 'qs','id' => 30 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X31' => ['type' => 'qs','id' => 30 ,'key' => 'HOCUS_WAY_ID'],
        'C35X32C'=> ['type' => 'qs','id' => 31 ,'key' => 'ICD9_ID1'],
        'C36X32N' => ['type' => 'qs','id' => 31 ,'key' => 'ICD9_NAME'],
        'C37X32' => ['type' => 'qs','id' => 31 ,'key' => 'OPE_DATE'],
        'C38X32' => ['type' => 'qs','id' => 31 ,'key' => 'OPE_LEVEL'],
        'C39X32'=> ['type' => 'qs','id' => 31 ,'key' => 'OPE_MAN_NAME'],
        'C40X32' => ['type' => 'qs','id' => 31 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X32' => ['type' => 'qs','id' => 31 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X32C' => ['type' => 'qs','id' => 31 ,'key' => 'INCISION_GRADE_ID'],
        'C43X32C'=> ['type' => 'qs','id' => 31 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X32' => ['type' => 'qs','id' => 31 ,'key' => 'HOCUS_WAY_ID'],
        'C35X33C'=> ['type' => 'qs','id' => 32 ,'key' => 'ICD9_ID1'],
        'C36X33N' => ['type' => 'qs','id' => 32 ,'key' => 'ICD9_NAME'],
        'C37X33' => ['type' => 'qs','id' => 32 ,'key' => 'OPE_DATE'],
        'C38X33' => ['type' => 'qs','id' => 32 ,'key' => 'OPE_LEVEL'],
        'C39X33'=> ['type' => 'qs','id' => 32 ,'key' => 'OPE_MAN_NAME'],
        'C40X33' => ['type' => 'qs','id' => 32 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X33' => ['type' => 'qs','id' => 32 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X33C' => ['type' => 'qs','id' => 32 ,'key' => 'INCISION_GRADE_ID'],
        'C43X33C'=> ['type' => 'qs','id' => 32 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X33' => ['type' => 'qs','id' => 32 ,'key' => 'HOCUS_WAY_ID'],
        'C35X34C'=> ['type' => 'qs','id' => 33 ,'key' => 'ICD9_ID1'],
        'C36X34N' => ['type' => 'qs','id' => 33 ,'key' => 'ICD9_NAME'],
        'C37X34' => ['type' => 'qs','id' => 33 ,'key' => 'OPE_DATE'],
        'C38X34' => ['type' => 'qs','id' => 33 ,'key' => 'OPE_LEVEL'],
        'C39X34'=> ['type' => 'qs','id' => 33 ,'key' => 'OPE_MAN_NAME'],
        'C40X34' => ['type' => 'qs','id' => 33 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X34' => ['type' => 'qs','id' => 33 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X34C' => ['type' => 'qs','id' => 33 ,'key' => 'INCISION_GRADE_ID'],
        'C43X34C'=> ['type' => 'qs','id' => 33 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X34' => ['type' => 'qs','id' => 33 ,'key' => 'HOCUS_WAY_ID'],
        'C35X35C'=> ['type' => 'qs','id' => 34 ,'key' => 'ICD9_ID1'],
        'C36X35N' => ['type' => 'qs','id' => 34 ,'key' => 'ICD9_NAME'],
        'C37X35' => ['type' => 'qs','id' => 34 ,'key' => 'OPE_DATE'],
        'C38X35' => ['type' => 'qs','id' => 34 ,'key' => 'OPE_LEVEL'],
        'C39X35'=> ['type' => 'qs','id' => 34 ,'key' => 'OPE_MAN_NAME'],
        'C40X35' => ['type' => 'qs','id' => 34 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X35' => ['type' => 'qs','id' => 34 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X35C' => ['type' => 'qs','id' => 34 ,'key' => 'INCISION_GRADE_ID'],
        'C43X35C'=> ['type' => 'qs','id' => 34 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X35' => ['type' => 'qs','id' => 34 ,'key' => 'HOCUS_WAY_ID'],
        'C35X36C'=> ['type' => 'qs','id' => 35 ,'key' => 'ICD9_ID1'],
        'C36X36N' => ['type' => 'qs','id' => 35 ,'key' => 'ICD9_NAME'],
        'C37X36' => ['type' => 'qs','id' => 35 ,'key' => 'OPE_DATE'],
        'C38X36' => ['type' => 'qs','id' => 35 ,'key' => 'OPE_LEVEL'],
        'C39X36'=> ['type' => 'qs','id' => 35 ,'key' => 'OPE_MAN_NAME'],
        'C40X36' => ['type' => 'qs','id' => 35 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X36' => ['type' => 'qs','id' => 35 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X36C' => ['type' => 'qs','id' => 35 ,'key' => 'INCISION_GRADE_ID'],
        'C43X36C'=> ['type' => 'qs','id' => 35 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X36' => ['type' => 'qs','id' => 35 ,'key' => 'HOCUS_WAY_ID'],
        'C35X37C'=> ['type' => 'qs','id' => 36 ,'key' => 'ICD9_ID1'],
        'C36X37N' => ['type' => 'qs','id' => 36 ,'key' => 'ICD9_NAME'],
        'C37X37' => ['type' => 'qs','id' => 36 ,'key' => 'OPE_DATE'],
        'C38X37' => ['type' => 'qs','id' => 36 ,'key' => 'OPE_LEVEL'],
        'C39X37'=> ['type' => 'qs','id' => 36 ,'key' => 'OPE_MAN_NAME'],
        'C40X37' => ['type' => 'qs','id' => 36 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X37' => ['type' => 'qs','id' => 36 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X37C' => ['type' => 'qs','id' => 36 ,'key' => 'INCISION_GRADE_ID'],
        'C43X37C'=> ['type' => 'qs','id' => 36 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X37' => ['type' => 'qs','id' => 36 ,'key' => 'HOCUS_WAY_ID'],
        'C35X38C'=> ['type' => 'qs','id' => 37 ,'key' => 'ICD9_ID1'],
        'C36X38N' => ['type' => 'qs','id' => 37 ,'key' => 'ICD9_NAME'],
        'C37X38' => ['type' => 'qs','id' => 37 ,'key' => 'OPE_DATE'],
        'C38X38' => ['type' => 'qs','id' => 37 ,'key' => 'OPE_LEVEL'],
        'C39X38'=> ['type' => 'qs','id' => 37 ,'key' => 'OPE_MAN_NAME'],
        'C40X38' => ['type' => 'qs','id' => 37 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X38' => ['type' => 'qs','id' => 37 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X38C' => ['type' => 'qs','id' => 37 ,'key' => 'INCISION_GRADE_ID'],
        'C43X38C'=> ['type' => 'qs','id' => 37 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X38' => ['type' => 'qs','id' => 37 ,'key' => 'HOCUS_WAY_ID'],
        'C35X39C'=> ['type' => 'qs','id' => 38 ,'key' => 'ICD9_ID1'],
        'C36X39N' => ['type' => 'qs','id' => 38 ,'key' => 'ICD9_NAME'],
        'C37X39' => ['type' => 'qs','id' => 38 ,'key' => 'OPE_DATE'],
        'C38X39' => ['type' => 'qs','id' => 38 ,'key' => 'OPE_LEVEL'],
        'C39X39'=> ['type' => 'qs','id' => 38 ,'key' => 'OPE_MAN_NAME'],
        'C40X39' => ['type' => 'qs','id' => 38 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X39' => ['type' => 'qs','id' => 38 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X39C' => ['type' => 'qs','id' => 38 ,'key' => 'INCISION_GRADE_ID'],
        'C43X39C'=> ['type' => 'qs','id' => 38 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X39' => ['type' => 'qs','id' => 38 ,'key' => 'HOCUS_WAY_ID'],
        'C35X40C'=> ['type' => 'qs','id' => 39 ,'key' => 'ICD9_ID1'],
        'C36X40N' => ['type' => 'qs','id' => 39 ,'key' => 'ICD9_NAME'],
        'C37X40' => ['type' => 'qs','id' => 39 ,'key' => 'OPE_DATE'],
        'C38X40' => ['type' => 'qs','id' => 39 ,'key' => 'OPE_LEVEL'],
        'C39X40'=> ['type' => 'qs','id' => 39 ,'key' => 'OPE_MAN_NAME'],
        'C40X40' => ['type' => 'qs','id' => 39 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'C41X40' => ['type' => 'qs','id' => 39 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'C42X40C' => ['type' => 'qs','id' => 39 ,'key' => 'INCISION_GRADE_ID'],
        'C43X40C'=> ['type' => 'qs','id' => 39 ,'key' => 'HOCUS_MAN_NAME'],
        'C44X40' => ['type' => 'qs','id' => 39 ,'key' => 'HOCUS_WAY_ID'],
        'A16' => 'AAA40',
        'A18X01' => 'AEN01',
        'A18X02' => '',
        'A18X03' => '',
        'A18X04' => '',
        'A18X05' => '',
        'A17' => 'AAA42',
        'C28' => 'AEJ01',
        'C29' => 'AEJ02',
        'C30' => 'AEJ03',
        'C31' => 'AEJ04',
        'C32' => 'AEJ05',
        'C33' => 'AEJ06',
        'C47' => 'AEL01',
        'C48X01C' => ['type' => 'icu','id' => 0 ,'key' => 'IS_MAIN_WAY'],
        'C48X02C' => ['type' => 'icu','id' => 1 ,'key' => 'IS_MAIN_WAY'],
        'C48X03C' => ['type' => 'icu','id' => 2 ,'key' => 'IS_MAIN_WAY'],
        'C48X04C' => ['type' => 'icu','id' => 3 ,'key' => 'IS_MAIN_WAY'],
        'C48X05C' => ['type' => 'icu','id' => 4 ,'key' => 'IS_MAIN_WAY'],
        'C49X01' => ['type' => 'icu','id' => 0 ,'key' => 'IN_TIME'],
        'C49X02' => ['type' => 'icu','id' => 1 ,'key' => 'IN_TIME'],
        'C49X03' => ['type' => 'icu','id' => 2 ,'key' => 'IN_TIME'],
        'C49X04' => ['type' => 'icu','id' => 3 ,'key' => 'IN_TIME'],
        'C49X05' => ['type' => 'icu','id' => 4 ,'key' => 'IN_TIME'],
        'C50X01' => ['type' => 'icu','id' => 0 ,'key' => 'OUT_TIME'],
        'C50X02' => ['type' => 'icu','id' => 1 ,'key' => 'OUT_TIME'],
        'C50X03' => ['type' => 'icu','id' => 2 ,'key' => 'OUT_TIME'],
        'C50X04' => ['type' => 'icu','id' => 3 ,'key' => 'OUT_TIME'],
        'C50X05' => ['type' => 'icu','id' => 4 ,'key' => 'OUT_TIME'],
        'B36C' => 'AEM03C',
        'B37' => 'AEM04',
        'B34C' => 'AEM01C',
        'B35' => 'AEM02',
        'D01' => 'ADA01',
        'D09' => 'ADA0101',
        'D11' => 'D11',
        'D12' => 'D12',
        'D13' => 'D13',
        'D14' => 'D14',
        'D15' => 'D15',
        'D16' => 'D16',
        'D17' => 'D17',
        'D18' => 'D18',
        'D19' => 'D19',
        'D19X01' => 'D19X01',
        'D20' => 'D20',
        'D20X01' => 'D20X01',
        'D20X02' => 'D20X02',
        'D21' => 'D21',
        'D22' => 'D22',
        'D23' => 'D23',
        'D23X01' => 'D23X01',
        'D24' => 'D24',
        'D25' => 'D25',
        'D26' => 'D26',
        'D27' => 'D27',
        'D28' => 'D28',
        'D29' => 'D29',
        'D30' =>  'D30',
        'D31' => 'D31',
        'D32' => 'D32',
        'D33' => 'D33',
        'D34' => 'D34',
        'F01' => 'AAB07',
        'F02C' => 'AAB07C',
        'F03N' => 'AAB07N',
        'F04' => 'AAB07D',
        'F05' => '',
        'F06X01' => ['type' => 'qd','id' => 0 ,'key' => ''],
        'F06X02' => ['type' => 'qd','id' => 1 ,'key' => ''],
        'F06X03' => ['type' => 'qd','id' => 2 ,'key' => ''],
        'F06X04' => ['type' => 'qd','id' => 3 ,'key' => ''],
        'F06X05' => ['type' => 'qd','id' => 4 ,'key' => ''],
        'F06X06' => ['type' => 'qd','id' => 5 ,'key' => ''],
        'F06X07' => ['type' => 'qd','id' => 6 ,'key' => ''],
        'F06X08' => ['type' => 'qd','id' => 7 ,'key' => ''],
        'F06X09' => ['type' => 'qd','id' => 8 ,'key' => ''],
        'F06X10' => ['type' => 'qd','id' => 9 ,'key' => ''],
        'F06X11' => ['type' => 'qd','id' => 10 ,'key' => ''],
        'F06X12' => ['type' => 'qd','id' => 11 ,'key' => ''],
        'F06X13' => ['type' => 'qd','id' => 12 ,'key' => ''],
        'F06X14' => ['type' => 'qd','id' => 13 ,'key' => ''],
        'F06X15' => ['type' => 'qd','id' => 14 ,'key' => ''],
        'F06X16' => ['type' => 'qd','id' => 15 ,'key' => ''],
        'F06X17' => ['type' => 'qd','id' => 16 ,'key' => ''],
        'F06X18' => ['type' => 'qd','id' => 17 ,'key' => ''],
        'F06X19' => ['type' => 'qd','id' => 18 ,'key' => ''],
        'F06X20' => ['type' => 'qd','id' => 19 ,'key' => ''],
        'F06X21' => ['type' => 'qd','id' => 20 ,'key' => ''],
        'F06X22' => ['type' => 'qd','id' => 21 ,'key' => ''],
        'F06X23' => ['type' => 'qd','id' => 22 ,'key' => ''],
        'F06X24' => ['type' => 'qd','id' => 23 ,'key' => ''],
        'F06X25' => ['type' => 'qd','id' => 24 ,'key' => ''],
        'F06X26' => ['type' => 'qd','id' => 25 ,'key' => ''],
        'F06X27' => ['type' => 'qd','id' => 26 ,'key' => ''],
        'F06X28' => ['type' => 'qd','id' => 27 ,'key' => ''],
        'F06X29' => ['type' => 'qd','id' => 28 ,'key' => ''],
        'F06X30' => ['type' => 'qd','id' => 29 ,'key' => ''],
        'F06X31' => ['type' => 'qd','id' => 30 ,'key' => ''],
        'F06X32' => ['type' => 'qd','id' => 31 ,'key' => ''],
        'F06X33' => ['type' => 'qd','id' => 32 ,'key' => ''],
        'F06X34' => ['type' => 'qd','id' => 33 ,'key' => ''],
        'F06X35' => ['type' => 'qd','id' => 34 ,'key' => ''],
        'F06X36' => ['type' => 'qd','id' => 35 ,'key' => ''],
        'F06X37' => ['type' => 'qd','id' => 36 ,'key' => ''],
        'F06X38' => ['type' => 'qd','id' => 37 ,'key' => ''],
        'F06X39' => ['type' => 'qd','id' => 38 ,'key' => ''],
        'F06X40' => ['type' => 'qd','id' => 39 ,'key' => ''],
        'F07X01C' => 'ABF01C',
        'F07X02C' => 'ABF01C',
        'F08X01N' => 'ABF01N',
        'F08X02N' => 'ABF01N',
        'F09X01' => 'ABF04',
        'F09X02' => 'ABF04',
        'F10' => 'HB',
        'F11' => 'HCV',
        'F12' => 'HIV',
        'F13' => ['type' => 'ms','id' => 0 ,'key' => 'es'],
        'F14X01' => ['type' => 'ms','id' => 0 ,'key' => 'es'],
        'F14X02' => ['type' => 'qs','id' => 0 ,'key' => 'es'],
        'F14X03' => ['type' => 'qs','id' => 1 ,'key' => 'es'],
        'F14X04' => ['type' => 'qs','id' => 2 ,'key' => 'es'],
        'F14X05' => ['type' => 'qs','id' => 3 ,'key' => 'es'],
        'F14X06' => ['type' => 'qs','id' => 4 ,'key' => 'es'],
        'F14X07' => ['type' => 'qs','id' => 5 ,'key' => 'es'],
        'F14X08' => ['type' => 'qs','id' => 6 ,'key' => 'es'],
        'F14X09' => ['type' => 'qs','id' => 7 ,'key' => 'es'],
        'F14X10' => ['type' => 'qs','id' => 8 ,'key' => 'es'],
        'F14X11' => ['type' => 'qs','id' => 9 ,'key' => 'es'],
        'F14X12' => ['type' => 'qs','id' => 10 ,'key' => 'es'],
        'F14X13' => ['type' => 'qs','id' => 11 ,'key' => 'es'],
        'F14X14' => ['type' => 'qs','id' => 12 ,'key' => 'es'],
        'F14X15' => ['type' => 'qs','id' => 13 ,'key' => 'es'],
        'F14X16' => ['type' => 'qs','id' => 14 ,'key' => 'es'],
        'F14X17' => ['type' => 'qs','id' => 15 ,'key' => 'es'],
        'F14X18' => ['type' => 'qs','id' => 16 ,'key' => 'es'],
        'F14X19' => ['type' => 'qs','id' => 17 ,'key' => 'es'],
        'F14X20' => ['type' => 'qs','id' => 18 ,'key' => 'es'],
        'F14X21' => ['type' => 'qs','id' => 19 ,'key' => 'es'],
        'F14X22' => ['type' => 'qs','id' => 20 ,'key' => 'es'],
        'F14X23' => ['type' => 'qs','id' => 21 ,'key' => 'es'],
        'F14X24' => ['type' => 'qs','id' => 22 ,'key' => 'es'],
        'F14X25' => ['type' => 'qs','id' => 23 ,'key' => 'es'],
        'F14X26' => ['type' => 'qs','id' => 24 ,'key' => 'es'],
        'F14X27' => ['type' => 'qs','id' => 25 ,'key' => 'es'],
        'F14X28' => ['type' => 'qs','id' => 26 ,'key' => 'es'],
        'F14X29' => ['type' => 'qs','id' => 27 ,'key' => 'es'],
        'F14X30' => ['type' => 'qs','id' => 28 ,'key' => 'es'],
        'F14X31' => ['type' => 'qs','id' => 29 ,'key' => 'es'],
        'F14X32' => ['type' => 'qs','id' => 30 ,'key' => 'es'],
        'F14X33' => ['type' => 'qs','id' => 31 ,'key' => 'es'],
        'F14X34' => ['type' => 'qs','id' => 32 ,'key' => 'es'],
        'F14X35' => ['type' => 'qs','id' => 33 ,'key' => 'es'],
        'F14X36' => ['type' => 'qs','id' => 34 ,'key' => 'es'],
        'F14X37' => ['type' => 'qs','id' => 35 ,'key' => 'es'],
        'F14X38' => ['type' => 'qs','id' => 36 ,'key' => 'es'],
        'F14X39' => ['type' => 'qs','id' => 37 ,'key' => 'es'],
        'F14X40' => ['type' => 'qs','id' => 38 ,'key' => 'es'],
        'F15' => ['type' => 'ms','id' => 0 ,'key' => ''],
        'F16X01' => ['type' => 'qs','id' => 0 ,'key' => ''],
        'F16X02' => ['type' => 'qs','id' => 1 ,'key' => ''],
        'F16X03' => ['type' => 'qs','id' => 2 ,'key' => ''],
        'F16X04' => ['type' => 'qs','id' => 3 ,'key' => ''],
        'F16X05' => ['type' => 'qs','id' => 4 ,'key' => ''],
        'F16X06' => ['type' => 'qs','id' => 5 ,'key' => ''],
        'F16X07' => ['type' => 'qs','id' => 6 ,'key' => ''],
        'F16X08' => ['type' => 'qs','id' => 7 ,'key' => ''],
        'F16X09' => ['type' => 'qs','id' => 8 ,'key' => ''],
        'F16X10' => ['type' => 'qs','id' => 9 ,'key' => ''],
        'F16X11' => ['type' => 'qs','id' => 10 ,'key' => ''],
        'F16X12' => ['type' => 'qs','id' => 11 ,'key' => ''],
        'F16X13' => ['type' => 'qs','id' => 12 ,'key' => ''],
        'F16X14' => ['type' => 'qs','id' => 13 ,'key' => ''],
        'F16X15' => ['type' => 'qs','id' => 14 ,'key' => ''],
        'F16X16' => ['type' => 'qs','id' => 15 ,'key' => ''],
        'F16X17' => ['type' => 'qs','id' => 16 ,'key' => ''],
        'F16X18' => ['type' => 'qs','id' => 17 ,'key' => ''],
        'F16X19' => ['type' => 'qs','id' => 18 ,'key' => ''],
        'F16X20' => ['type' => 'qs','id' => 19 ,'key' => ''],
        'F16X21' => ['type' => 'qs','id' => 20 ,'key' => ''],
        'F16X22' => ['type' => 'qs','id' => 21 ,'key' => ''],
        'F16X23' => ['type' => 'qs','id' => 22 ,'key' => ''],
        'F16X24' => ['type' => 'qs','id' => 23 ,'key' => ''],
        'F16X25' => ['type' => 'qs','id' => 24 ,'key' => ''],
        'F16X26' => ['type' => 'qs','id' => 25 ,'key' => ''],
        'F16X27' => ['type' => 'qs','id' => 26 ,'key' => ''],
        'F16X28' => ['type' => 'qs','id' => 27 ,'key' => ''],
        'F16X29' => ['type' => 'qs','id' => 28 ,'key' => ''],
        'F16X30' => ['type' => 'qs','id' => 29 ,'key' => ''],
        'F16X31' => ['type' => 'qs','id' => 30 ,'key' => ''],
        'F16X32' => ['type' => 'qs','id' => 31 ,'key' => ''],
        'F16X33' => ['type' => 'qs','id' => 32 ,'key' => ''],
        'F16X34' => ['type' => 'qs','id' => 33 ,'key' => ''],
        'F16X35' => ['type' => 'qs','id' => 34 ,'key' => ''],
        'F16X36' => ['type' => 'qs','id' => 35 ,'key' => ''],
        'F16X37' => ['type' => 'qs','id' => 36 ,'key' => ''],
        'F16X38' => ['type' => 'qs','id' => 37 ,'key' => ''],
        'F16X39' => ['type' => 'qs','id' => 38 ,'key' => ''],
        'F16X40' => ['type' => 'qs','id' => 39 ,'key' => ''],
        'F17' => 'TJHL',
        'F18' => 'YJHL',
        'F19' => 'EJHL',
        'F20' => 'SJHL',
        'F21' => 'AFA08',
        'F22' => 'AEG04',
        'F23' => 'AEG05',
        'F24' => 'AEG06',
        'F25' => 'AEG07',
        'F26' => ''
    ]
];
