<?php

return [
        //诊断
        'diagnosis'=>'diagnosis',
        //手术
        'operation'=>'operation',

        //患者信息
                'AAA01'=>'patient_info',
                'AAA02C'=>'patient_info',
                'AAA03'=>'patient_info',
                'AAA04'=>'patient_info',
                'AAA05C'=>'patient_info',
                'AAA40'=>'patient_info',
                'AAA42'=>'patient_info',
                'AEN01'=>'patient_info',
                'AAA06C'=>'patient_info',
                'AAA07'=>'patient_info',
                'AAA08C'=>'patient_info',
                'AEM01C'=>'patient_info',
                'AAC01'=>'patient_info',
                'AAC11N'=>'patient_info',
                'AAC04'=>'patient_info',
                'ADA01'=>'patient_info',
                'AAA29'=>'patient_info',
                'AAB06C'=>'patient_info',
                'ABC01N'=>'patient_info',
                'ICD9_NAME'=>'patient_info',
                'ORG_STATE'=>'patient_info',
                'AAA26C'=>'patient_info',
                'ATTEND_GRP_CODE'=>'patient_info',
                'ATTEND_GRP_NAME'=>'patient_info',
                'F_D'=>'patient_info',
                'J'=>'patient_info',
                'coder_id'=>'patient_info',
                'score'=>'patient_info',
                'status'=>'patient_info',

        //患者联系信息
                'AAB07C'=>'patient_other_info',
                'AAB07N'=>'patient_other_info',
                'AAB07'=>'patient_other_info',
                'AAB07D'=>'patient_other_info',
                'ABD04'=>'patient_other_info',
                'ABD051'=>'patient_other_info',
                'ABD052'=>'patient_other_info',
                'ABD053'=>'patient_other_info',
                'ABD054'=>'patient_other_info',
                'ZB09'=>'patient_other_info',
                'ZB08'=>'patient_other_info',
                'ZB07'=>'patient_other_info',
                'ZB06'=>'patient_other_info',
                'ZB05'=>'patient_other_info',
                'ZB04'=>'patient_other_info',
                'ZB03'=>'patient_other_info',
                'ZB02'=>'patient_other_info',
                'ZB01C'=>'patient_other_info',
                'ZA04'=>'patient_other_info',
                'MED_REC_ID'=>'patient_other_info',
                'UNT_ID'=>'patient_other_info',
                'ZA03'=>'patient_other_info',
                'AFA01'=>'patient_other_info',
                'AFA02'=>'patient_other_info',
                'AFA03'=>'patient_other_info',
                'AFA04'=>'patient_other_info',
                'AFA05'=>'patient_other_info',
                'AFA06'=>'patient_other_info',
                'AFA07'=>'patient_other_info',
                'AFA08'=>'patient_other_info',
                'AFA09'=>'patient_other_info',
                'AFA10'=>'patient_other_info',
                'AFA11'=>'patient_other_info',
                'AFA12'=>'patient_other_info',
                'ZB10'=>'patient_other_info',
                'ZB11'=>'patient_other_info',
                'IS_VALID'=>'patient_other_info',
                'SYN_DATE'=>'patient_other_info',
                'QU_STATE'=>'patient_other_info',
                'DATA_STATE'=>'patient_other_info',
                'BALANCEID'=>'patient_other_info',
                'AKC021'=>'patient_other_info',

        //患者医疗信息
                'ABA01C'=>'patient_medical_info',
                'ABA01N'=>'patient_medical_info',
                'ABC03C'=>'patient_medical_info',
                'ABF01C'=>'patient_medical_info',
                'ABF01N'=>'patient_medical_info',
                'ABF04'=>'patient_medical_info',
                'ABF02C'=>'patient_medical_info',
                'ABF03C'=>'patient_medical_info',
                'ABH01C'=>'patient_medical_info',
                'ABH0201C'=>'patient_medical_info',
                'ABH0202C'=>'patient_medical_info',
                'ABH0203C'=>'patient_medical_info',
                'ABH03C'=>'patient_medical_info',
                'AEB02C'=>'patient_medical_info',
                'AEB01'=>'patient_medical_info',
                'AED01C'=>'patient_medical_info',
                'AEG01C'=>'patient_medical_info',
                'AEG02C'=>'patient_medical_info',
                'AEG04'=>'patient_medical_info',
                'AEG05'=>'patient_medical_info',
                'AEG06'=>'patient_medical_info',
                'AEG07'=>'patient_medical_info',
                'AEG08'=>'patient_medical_info',
                'AEJ01'=>'patient_medical_info',
                'AEJ02'=>'patient_medical_info',
                'AEJ03'=>'patient_medical_info',
                'AEJ04'=>'patient_medical_info',
                'AEJ05'=>'patient_medical_info',
                'AEJ06'=>'patient_medical_info',
                'AEL01'=>'patient_medical_info',
                'AEN02C'=>'patient_medical_info',
                'AEN02N'=>'patient_medical_info',
                'AEI09'=>'patient_medical_info',
                'AEI10'=>'patient_medical_info',
                'AEI08'=>'patient_medical_info',



        //患者住院信息
                'AAA30'=>'patient_hospital_info',
                'ABC01C'=>'patient_hospital_info',
                'AAA27'=>'patient_hospital_info',
                'AAC001'=>'patient_hospital_info',
                'AAB01'=>'patient_hospital_info',
                'AAB02C'=>'patient_hospital_info',
                'AAB03'=>'patient_hospital_info',
                'AAB11C'=>'patient_hospital_info',
                'AAB11N'=>'patient_hospital_info',
                'AAC02C'=>'patient_hospital_info',
                'AAC03'=>'patient_hospital_info',
                'AAC11C'=>'patient_hospital_info',
                'AAD01C'=>'patient_hospital_info',
                'AEM02'=>'patient_hospital_info',
                'AEM03C'=>'patient_hospital_info',
                'AEM04'=>'patient_hospital_info',
                'AEI01C'=>'patient_hospital_info',



        //患者医生信息
                'AED02'=>'patient_doctor_info',
                'AED03'=>'patient_doctor_info',
                'AED04'=>'patient_doctor_info',
                'AEE01'=>'patient_doctor_info',
                'AEE02'=>'patient_doctor_info',
                'AEE03'=>'patient_doctor_info',
                'AEE11'=>'patient_doctor_info',
                'AEE09'=>'patient_doctor_info',
                'AEE04'=>'patient_doctor_info',
                'AEE05'=>'patient_doctor_info',
                'AEE07'=>'patient_doctor_info',
                'AEE08'=>'patient_doctor_info',
                'AEE10'=>'patient_doctor_info',
                'CODE_DATE'=>'patient_doctor_info',
                'COMPLETION_DATE'=>'patient_doctor_info',
                'SIGN_IN_DATE'=>'patient_doctor_info',
                'QUALITY_CONTROL'=>'patient_doctor_info',
                'AEE02_CODE'=>'patient_doctor_info',
                'AEE03_CODE'=>'patient_doctor_info',
                'AEE04_CODE'=>'patient_doctor_info',



        //患者地址相关信息
                'AAA09'=>'patient_address_info',
                'AAA10'=>'patient_address_info',
                'AAA11'=>'patient_address_info',
                'AAA43'=>'patient_address_info',
                'AAA44'=>'patient_address_info',
                'AAA45'=>'patient_address_info',
                'AAA46'=>'patient_address_info',
                'AAA47'=>'patient_address_info',
                'AAA12'=>'patient_address_info',
                'AAA13C'=>'patient_address_info',
                'AAA33C'=>'patient_address_info',
                'AAA14C'=>'patient_address_info',
                'AAA15'=>'patient_address_info',
                'AAA48'=>'patient_address_info',
                'AAA49'=>'patient_address_info',
                'AAA50'=>'patient_address_info',
                'AAA16C'=>'patient_address_info',
                'AAA36C'=>'patient_address_info',
                'AAA51'=>'patient_address_info',
                'AAA17C'=>'patient_address_info',

        //患者工作信息
                'AAA18C'=>'patient_work_info',
                'AAA19'=>'patient_work_info',
                'AAA20'=>'patient_work_info',
                'AAA21C'=>'patient_work_info',


        //患者联系人信息
                'AAA22'=>'patient_contacts_info',
                'AAA23C'=>'patient_contacts_info',
                'AAA24'=>'patient_contacts_info',
                'AAA25'=>'patient_contacts_info',




        //患者重症信息
                'IS_MAIN_WAY'=>'icu',
                'IN_TIME'=>'icu',
                'OUT_TIME'=>'icu',
                'AREA_ID'=>'icu',
                'BATCH_ID'=>'icu',



        //患者费用信息
                'ADA0101'=>'patient_cost_info',
                'AAE040'=>'patient_cost_info',
                'D11'=>'patient_cost_info',
                'D12'=>'patient_cost_info',
                'D13'=>'patient_cost_info',
                'D14'=>'patient_cost_info',
                'D15'=>'patient_cost_info',
                'D16'=>'patient_cost_info',
                'D17'=>'patient_cost_info',
                'D18'=>'patient_cost_info',
                'D19'=>'patient_cost_info',
                'D19X01'=>'patient_cost_info',
                'D20'=>'patient_cost_info',
                'D20X01'=>'patient_cost_info',
                'D20X02'=>'patient_cost_info',
                'D21'=>'patient_cost_info',
                'D22'=>'patient_cost_info',
                'D23'=>'patient_cost_info',
                'D23X01'=>'patient_cost_info',
                'D24'=>'patient_cost_info',
                'D25'=>'patient_cost_info',
                'D26'=>'patient_cost_info',
                'D27'=>'patient_cost_info',
                'D28'=>'patient_cost_info',
                'D29'=>'patient_cost_info',
                'D30'=>'patient_cost_info',
                'D31'=>'patient_cost_info',
                'D32'=>'patient_cost_info',
                'D33'=>'patient_cost_info',
                'D34'=>'patient_cost_info',
];
