<?php


namespace App\Model;

use Illuminate\Database\Eloquent\Model;

class UserSearchLog extends Model
{
    /**
     * 与模型关联的表名
     *
     * @var string
     */
    protected $table = 'user_search_log';

    const KEY_VALUE = [
        'is_tm' => '是否脱敏',
        'page' => '页码',
        'limit' => '每页条数',
        'page_size' => '每页条数',
        'keyword' => '关键字',
        'AAC01_start' => '出院时间-起',
        'AAC01_end' => '出院时间-止',
        'AAA28' => '住院号',
        'AAC04_start' => '住院天数-起',
        'AAC04_end' => '住院天数-止',
        'AAA04_start' => '患者年龄-起',
        'AAA04_end' => '患者年龄-止',
        'AAA40_start' => '患者天数-起',
        'AAA40_end' => '患者天数-止',
        'field' => '组合搜索条件',
        'level' => '状态',
        'ORG_STATE' => '质控类型',
        'coder_id' => '编码员',
        'AAC11C' => '出院科室',
        'AAA26C' => '医疗付款方式',
        'status' => '编辑状态',
        'AAC01_start_date' => '出院时间-起',
        'AAC01_end_date' => '出院时间-止',
        'AAC0401' => '住院天数-起',
        'AAC0402' => '住院天数-止',
        'AAA40' => '患者年龄/天-起',
        'AAA04' => '患者年龄/天-止',
        'age_start_type' => '患者开始年龄按天查询',
        'age_end_type' => '患者结束年龄按天查询',
        'AAC04' => '住院天数起止',
        'ABC01N' => '主要诊断名称',
        'ABC01C' => '主要诊断编码',
        'ICD10_ID1_first' => '第一其它诊断编码',
        'ICD10_NAME_first' => '第一其它诊断名称',
        'ICD10_ID1' => '其它诊断编码',
        'ICD10_NAME' => '其它诊断名称',
        'ICD9_ID1' => '手术编码',
        'ICD9_NAME' => '手术名称',
        'ABC03C' => '主要诊断入院病情',
        'RYQK' => '其它诊断入院病情',
        'OPE_LEVEL' => '手术级别',
        'AEM01C' => '离院方式',
        'ABA01N' => '门（急）诊诊断',
        'ABA01C' => '门急诊的疾病编码',
        'AEL01' => '有创呼吸机使用时间',
        'RJSS' => '是否为日间手术',
        'LNSSQ' => '颅脑损伤昏迷时间-入院前',
        'LNSSH' => '颅脑损伤昏迷时间-入院后',
        'AAA01' => '姓名',
        'AAA02C' => '性别',
        'AAA29' => '住院次数',
        'SSPB' => '手术判别',
        'AAC11N' => '出院科室',
        'YZMC' => '医嘱名称',
        'BRKS' => '病人科室',
        'KZKS' => '开嘱科室',
        'YZQX' => '医嘱期效',
        'start' => '开嘱开始时间',
        'end' => '开嘱解释时间',
        'is_export' => '是否导出',
        'AAA29_start' => '住院次数开始',
        'AAA29_end' => '住院次数结束',
        'KZSJ_start' => '开嘱开始时间',
        'KZSJ_end' => '开嘱结束时间',
        'user_code' => '请求者code',
        'BLNR_TXT' => '门诊病历搜索关键字',
        'mzh' => '门诊号',
        'xy' => '西药',
        'ks' => '科室',
        'xb' => '性别',
        'xm' => '姓名',
        'SFZH' => '身份证号',
        'start_nl' => '患者年龄-起',
        'end_nl' => '患者年龄-止',
        'start_time' => '就诊时间-起',
        'end_time' => '就诊时间-止',
        'AAC01_START' => '出院时间-起',
        'AAC01_END' => '出院时间-止',
        'TIWEN_START' => '体温大于',
        'TIWEN_END' => '体温小于',
    ];

    const KEY_LIST = [
        '1' => '出院记录',
        '292' => '入院记录',
        '294' => '病程记录',
        '303' => '手术记录',
        '43' => '病历讨论记录',
        '329' => '授权同意类',
        '79' => '评估评分表',
        '288' => '死亡记录类',
        '18' => '24小时内记录类',
        '34' => '医患沟通类',
        '87' => '医疗常用表格',
        '49' => '医嘱单',
        'AAC11N' => '科室',
        'FYMC' => '费用明细',
        '2000002' => '报告单',
        '101' => '会诊记录',
        'YZMC' => '医嘱名称',
        'KZKS' => '开嘱科室',
        'YZQX' => '医嘱期效',
        'YYSX' => '用药属性',
        'XMLB' => '项目类别',
        'BRKS' => '病人科室',
        'AAA28' => '病案号',
        'AAA01' => '姓名',
        'MD_ICD10_NAME' => '主要诊断名称',
        'MD_ICD10_ID1' => '主要诊断编码',
        'MD_RYQK' => '主要诊断入院情况',
        'OD_ICD10_NAME' => '其他诊断名称',
        'OD_ICD10_ID1' => '其他诊断编码',
        'OD_RYQK' => '其他诊断入院情况',
        'PMI_ABF01N' => '病理诊断名称',
        'PMI_ABF01C' => '病理诊断编码',
        'MO_ICD9_NAME' => '主要手术名称',
        'MO_ICD9_ID1' => '主要手术编码',
        'MO_OPE_LEVEL' => '主要手术级别',
        'MO_SSPB' => '主要手术判别',
        'MO_OPE_TYPE' => '主要手术类型',
        'SO_ICD9_NAME' => '其他手术名称',
        'SO_ICD9_ID1' => '其他手术编码',
        'SO_OPE_LEVEL' => '其他手术手术级别',
        'SO_SSPB' => '其他手术判别',
        'SO_OPE_TYPE' => '其他手术类型',
        'MO_SO_ICD9_NAME' => '手术名称',
        'MO_SO_ICD9_ID1' => '手术编码',
        'MO_SO_OPE_LEVEL' => '手术级别',
        'MO_SO_SSPB' => '手术判别',
        'MO_SO_OPE_TYPE' => '手术类型',
        'MO_SO_RJSS' => '是否为日间手术',
        'AEM01C' => '离院方式',
        'AAB06C' => '入院途径',
        'PMI_ABA01N' => '门（急）诊诊断名称',
        'PMI_ABA01C' => '门（急）诊诊断编码',
        'BLNR_TXT' => '门诊病历搜索关键字',
        'mzh' => '门诊号',
        'xy' => '西药',
        'ks' => '科室',
        'xb' => '性别',
        'xm' => '姓名',
        'SFZH' => '身份证号',
        'start_nl' => '患者年龄-起',
        'end_nl' => '患者年龄-止',
        'start_time' => '就诊时间-起',
        'end_time' => '就诊时间-止',
    ];

    /**
     * 指示是否自动维护时间戳
     *
     * @var bool
     */
    public $timestamps = false;
}
