<?php

return [
    'fileName' => '卫统上报.xlsx',
    'title' => [
        'JGMC' => '',
        'ZZJGDM' => '',
        'USERNAME' => '',
        'BAH' => 'AAA28',
        'ZYCS' => 'AAA29',
        'JKKH' => 'JKKH',
        'YLFKFS' => 'AAA26C',
        'XM' => 'AAA01',
        'XB' => 'AAA02C',
        'CSRQ' => 'AAA03',
        'NL' => 'AAA04',
        'GJ' => 'AAA05C',
        'BZYZSNL' => 'AAA40',
        'XSECSTZ' => 'AEN01',
        'XSECSTZ1' => '',
        'XSECSTZ2' => '',
        'XSECSTZ3' => '',
        'XSECSTZ4' => '',
        'XSERYTZ' => 'AAA42',
        'CSD_SG' => 'AAA09',
        'CSD_SI' => 'AAA10',
        'CSD_QX' => 'AAA11',
        'CSD_DZ' => '',
        'JG_SG' => 'AAA43',
        'JG_SI' => 'AAA44',
        'MZ' => 'AAA06C',
        'SFZJLB' => 'SFZJLX',
        'SFZH' => 'AAA07',
        'ZY' => 'AAA18C',
        'HY' => 'AAA08C',
        'XZZ_SG' => 'AAA48',
        'XZZ_SI' => 'AAA49',
        'XZZ_QX' => 'AAA50',
        'XZZ_DZ' => 'AAA15',
        'DH' => 'AAA51',
        'YB1' => 'AAA17C',
        'HKDZ_SG' => 'AAA45',
        'HKDZ_SI' => 'AAA46',
        'HKDZ_QX' => 'AAA47',
        'HKDZ_DZ' => 'AAA12',
        'YB2' => 'AAA14C',
        'GZDWJDZMC' => 'AAA19',
        'GZDWJDZ_SG' => '',
        'GZDWJDZ_SI' => '',
        'GZDWJDZ_QX' => '',
        'GZDWJDZ_DZ' => '',
        'DWDH' => 'AAA20',
        'YB3' => 'AAA21C',
        'LXRXM' => 'AAA22',
        'GX' => 'AAA23C',
        'DZ_SG' => '',
        'DZ_SI' => '',
        'DZ_QX' => '',
        'DZ_DZ' => 'AAA24',
        'DH2' => 'AAA25',
        'RYTJ' => 'AAB06C',
        'ZZYLJGMC' => 'AEM02',
        'RYSJ' => 'AAB01',
        'RYSJS' => 'rys',
        'RYKB' => 'AAB02C',
        'RYBF' => 'BFRY',
        'ZKKB' => 'AAD01C',
        'ZKKB1' => '',
        'ZKKB2' => '',
        'CYSJ' => 'AAC01',
        'CYSJS' => 'CYSJS',
        'CYKB' => 'AAC02C',
        'CYBF' => 'AAC03',
        'SJZYTS' => 'AAC04',
        'JBBM' => 'ABA01C',
        'MZZD' => 'ABA01N',
        'RYSQK' => 'AAB07',
        'RYZDBM' => 'AAB07C',
        'RYZDMC' => 'AAB07N',
        'RYHQZRQ' => 'AAB07D',
        'JBDM' => 'ICD10_ID1',
        'ZYZD' => 'ICD10_NAME',
        'RYBQ' => 'ABC03C',
        'CYQK' => '',
        'JBDM1'=> ['type' => 'qd','id' => 0 ,'key' => 'ICD10_ID1'],
        'QTZD1' => ['type' => 'qd','id' => 0 ,'key' => 'ICD10_NAME'],
        'RYBQ1' => ['type' => 'qd','id' => 0 ,'key' => 'RYQK'],
        'CYQK1' => ['type' => 'qd','id' => 0 ,'key' => ''],
        'JBDM2'=> ['type' => 'qd','id' => 1 ,'key' => 'ICD10_ID1'],
        'QTZD2' => ['type' => 'qd','id' => 1 ,'key' => 'ICD10_NAME'],
        'RYBQ2' => ['type' => 'qd','id' => 1 ,'key' => 'RYQK'],
        'CYQK2' => ['type' => 'qd','id' => 1 ,'key' => ''],
        'JBDM3'=> ['type' => 'qd','id' => 2 ,'key' => 'ICD10_ID1'],
        'QTZD3' => ['type' => 'qd','id' => 2 ,'key' => 'ICD10_NAME'],
        'RYBQ3' => ['type' => 'qd','id' => 2 ,'key' => 'RYQK'],
        'CYQK3' => ['type' => 'qd','id' => 2 ,'key' => ''],
        'JBDM4'=> ['type' => 'qd','id' => 3 ,'key' => 'ICD10_ID1'],
        'QTZD4' => ['type' => 'qd','id' => 3 ,'key' => 'ICD10_NAME'],
        'RYBQ4' => ['type' => 'qd','id' => 3 ,'key' => 'RYQK'],
        'CYQK4' => ['type' => 'qd','id' => 3 ,'key' => ''],
        'JBDM5'=> ['type' => 'qd','id' => 4 ,'key' => 'ICD10_ID1'],
        'QTZD5' => ['type' => 'qd','id' => 4 ,'key' => 'ICD10_NAME'],
        'RYBQ5' => ['type' => 'qd','id' => 4 ,'key' => 'RYQK'],
        'CYQK5' => ['type' => 'qd','id' => 4 ,'key' => ''],
        'JBDM6'=> ['type' => 'qd','id' => 5 ,'key' => 'ICD10_ID1'],
        'QTZD6' => ['type' => 'qd','id' => 5 ,'key' => 'ICD10_NAME'],
        'RYBQ6' => ['type' => 'qd','id' => 5 ,'key' => 'RYQK'],
        'CYQK6' => ['type' => 'qd','id' => 5 ,'key' => ''],
        'JBDM7'=> ['type' => 'qd','id' => 6 ,'key' => 'ICD10_ID1'],
        'QTZD7' => ['type' => 'qd','id' => 6 ,'key' => 'ICD10_NAME'],
        'RYBQ7' => ['type' => 'qd','id' => 6 ,'key' => 'RYQK'],
        'CYQK7' => ['type' => 'qd','id' => 6 ,'key' => ''],
        'JBDM8'=> ['type' => 'qd','id' => 7 ,'key' => 'ICD10_ID1'],
        'QTZD8' => ['type' => 'qd','id' => 7 ,'key' => 'ICD10_NAME'],
        'RYBQ8' => ['type' => 'qd','id' => 7 ,'key' => 'RYQK'],
        'CYQK8' => ['type' => 'qd','id' => 7 ,'key' => ''],
        'JBDM9'=> ['type' => 'qd','id' => 8 ,'key' => 'ICD10_ID1'],
        'QTZD9' => ['type' => 'qd','id' => 8 ,'key' => 'ICD10_NAME'],
        'RYBQ9' => ['type' => 'qd','id' => 8 ,'key' => 'RYQK'],
        'CYQK9' => ['type' => 'qd','id' => 8 ,'key' => ''],
        'JBDM10'=> ['type' => 'qd','id' => 9 ,'key' => 'ICD10_ID1'],
        'QTZD10' => ['type' => 'qd','id' => 9 ,'key' => 'ICD10_NAME'],
        'RYBQ10' => ['type' => 'qd','id' => 9 ,'key' => 'RYQK'],
        'CYQK10' => ['type' => 'qd','id' => 9 ,'key' => ''],
        'JBDM11'=> ['type' => 'qd','id' => 10 ,'key' => 'ICD10_ID1'],
        'QTZD11' => ['type' => 'qd','id' => 10 ,'key' => 'ICD10_NAME'],
        'RYBQ11' => ['type' => 'qd','id' => 10 ,'key' => 'RYQK'],
        'CYQK11' => ['type' => 'qd','id' => 10 ,'key' => ''],
        'JBDM12'=> ['type' => 'qd','id' => 11 ,'key' => 'ICD10_ID1'],
        'QTZD12' => ['type' => 'qd','id' => 11 ,'key' => 'ICD10_NAME'],
        'RYBQ12' => ['type' => 'qd','id' => 11 ,'key' => 'RYQK'],
        'CYQK12' => ['type' => 'qd','id' => 11 ,'key' => ''],
        'JBDM13'=> ['type' => 'qd','id' => 12 ,'key' => 'ICD10_ID1'],
        'QTZD13' => ['type' => 'qd','id' => 12 ,'key' => 'ICD10_NAME'],
        'RYBQ13' => ['type' => 'qd','id' => 12 ,'key' => 'RYQK'],
        'CYQK13' => ['type' => 'qd','id' => 12 ,'key' => ''],
        'JBDM14'=> ['type' => 'qd','id' => 13 ,'key' => 'ICD10_ID1'],
        'QTZD14' => ['type' => 'qd','id' => 13 ,'key' => 'ICD10_NAME'],
        'RYBQ14' => ['type' => 'qd','id' => 13 ,'key' => 'RYQK'],
        'CYQK14' => ['type' => 'qd','id' => 13 ,'key' => ''],
        'JBDM15'=> ['type' => 'qd','id' => 14 ,'key' => 'ICD10_ID1'],
        'QTZD15' => ['type' => 'qd','id' => 14 ,'key' => 'ICD10_NAME'],
        'RYBQ15' => ['type' => 'qd','id' => 14 ,'key' => 'RYQK'],
        'CYQK15' => ['type' => 'qd','id' => 14 ,'key' => ''],
        'JBDM16'=> ['type' => 'qd','id' => 15 ,'key' => 'ICD10_ID1'],
        'QTZD16' => ['type' => 'qd','id' => 15 ,'key' => 'ICD10_NAME'],
        'RYBQ16' => ['type' => 'qd','id' => 15 ,'key' => 'RYQK'],
        'CYQK16' => ['type' => 'qd','id' => 15 ,'key' => ''],
        'JBDM17'=> ['type' => 'qd','id' => 16 ,'key' => 'ICD10_ID1'],
        'QTZD17' => ['type' => 'qd','id' => 16 ,'key' => 'ICD10_NAME'],
        'RYBQ17' => ['type' => 'qd','id' => 16 ,'key' => 'RYQK'],
        'CYQK17' => ['type' => 'qd','id' => 16 ,'key' => ''],
        'JBDM18'=> ['type' => 'qd','id' => 17 ,'key' => 'ICD10_ID1'],
        'QTZD18' => ['type' => 'qd','id' => 17 ,'key' => 'ICD10_NAME'],
        'RYBQ18' => ['type' => 'qd','id' => 17 ,'key' => 'RYQK'],
        'CYQK18' => ['type' => 'qd','id' => 17 ,'key' => ''],
        'JBDM19'=> ['type' => 'qd','id' => 18 ,'key' => 'ICD10_ID1'],
        'QTZD19' => ['type' => 'qd','id' => 18 ,'key' => 'ICD10_NAME'],
        'RYBQ19' => ['type' => 'qd','id' => 18 ,'key' => 'RYQK'],
        'CYQK19' => ['type' => 'qd','id' => 18 ,'key' => ''],
        'JBDM20'=> ['type' => 'qd','id' => 19 ,'key' => 'ICD10_ID1'],
        'QTZD20' => ['type' => 'qd','id' => 19 ,'key' => 'ICD10_NAME'],
        'RYBQ20' => ['type' => 'qd','id' => 19 ,'key' => 'RYQK'],
        'CYQK20' => ['type' => 'qd','id' => 19 ,'key' => ''],
        'JBDM21'=> ['type' => 'qd','id' => 20 ,'key' => 'ICD10_ID1'],
        'QTZD21' => ['type' => 'qd','id' => 20 ,'key' => 'ICD10_NAME'],
        'RYBQ21' => ['type' => 'qd','id' => 20 ,'key' => 'RYQK'],
        'CYQK21' => ['type' => 'qd','id' => 20 ,'key' => ''],
        'JBDM22'=> ['type' => 'qd','id' => 21 ,'key' => 'ICD10_ID1'],
        'QTZD22' => ['type' => 'qd','id' => 21 ,'key' => 'ICD10_NAME'],
        'RYBQ22' => ['type' => 'qd','id' => 21 ,'key' => 'RYQK'],
        'CYQK22' => ['type' => 'qd','id' => 21 ,'key' => ''],
        'JBDM23'=> ['type' => 'qd','id' => 22 ,'key' => 'ICD10_ID1'],
        'QTZD23' => ['type' => 'qd','id' => 22 ,'key' => 'ICD10_NAME'],
        'RYBQ23' => ['type' => 'qd','id' => 22 ,'key' => 'RYQK'],
        'CYQK23' => ['type' => 'qd','id' => 22 ,'key' => ''],
        'JBDM24'=> ['type' => 'qd','id' => 23 ,'key' => 'ICD10_ID1'],
        'QTZD24' => ['type' => 'qd','id' => 23 ,'key' => 'ICD10_NAME'],
        'RYBQ24' => ['type' => 'qd','id' => 23 ,'key' => 'RYQK'],
        'CYQK24' => ['type' => 'qd','id' => 23 ,'key' => ''],
        'JBDM25'=> ['type' => 'qd','id' => 24 ,'key' => 'ICD10_ID1'],
        'QTZD25' => ['type' => 'qd','id' => 24 ,'key' => 'ICD10_NAME'],
        'RYBQ25' => ['type' => 'qd','id' => 24 ,'key' => 'RYQK'],
        'CYQK25' => ['type' => 'qd','id' => 24 ,'key' => ''],
        'JBDM26'=> ['type' => 'qd','id' => 25 ,'key' => 'ICD10_ID1'],
        'QTZD26' => ['type' => 'qd','id' => 25 ,'key' => 'ICD10_NAME'],
        'RYBQ26' => ['type' => 'qd','id' => 25 ,'key' => 'RYQK'],
        'CYQK26' => ['type' => 'qd','id' => 25 ,'key' => ''],
        'JBDM27'=> ['type' => 'qd','id' => 26 ,'key' => 'ICD10_ID1'],
        'QTZD27' => ['type' => 'qd','id' => 26 ,'key' => 'ICD10_NAME'],
        'RYBQ27' => ['type' => 'qd','id' => 26 ,'key' => 'RYQK'],
        'CYQK27' => ['type' => 'qd','id' => 26 ,'key' => ''],
        'JBDM28'=> ['type' => 'qd','id' => 27 ,'key' => 'ICD10_ID1'],
        'QTZD28' => ['type' => 'qd','id' => 27 ,'key' => 'ICD10_NAME'],
        'RYBQ28' => ['type' => 'qd','id' => 27 ,'key' => 'RYQK'],
        'CYQK28' => ['type' => 'qd','id' => 27 ,'key' => ''],
        'JBDM29'=> ['type' => 'qd','id' => 28 ,'key' => 'ICD10_ID1'],
        'QTZD29' => ['type' => 'qd','id' => 28 ,'key' => 'ICD10_NAME'],
        'RYBQ29' => ['type' => 'qd','id' => 28 ,'key' => 'RYQK'],
        'CYQK29' => ['type' => 'qd','id' => 28 ,'key' => ''],
        'JBDM30'=> ['type' => 'qd','id' => 29 ,'key' => 'ICD10_ID1'],
        'QTZD30' => ['type' => 'qd','id' => 29 ,'key' => 'ICD10_NAME'],
        'RYBQ30' => ['type' => 'qd','id' => 29 ,'key' => 'RYQK'],
        'CYQK30' => ['type' => 'qd','id' => 29 ,'key' => ''],
        'JBDM31'=> ['type' => 'qd','id' => 30 ,'key' => 'ICD10_ID1'],
        'QTZD31' => ['type' => 'qd','id' => 30 ,'key' => 'ICD10_NAME'],
        'RYBQ31' => ['type' => 'qd','id' => 30 ,'key' => 'RYQK'],
        'CYQK31' => ['type' => 'qd','id' => 30 ,'key' => ''],
        'JBDM32'=> ['type' => 'qd','id' => 31 ,'key' => 'ICD10_ID1'],
        'QTZD32' => ['type' => 'qd','id' => 31 ,'key' => 'ICD10_NAME'],
        'RYBQ32' => ['type' => 'qd','id' => 31 ,'key' => 'RYQK'],
        'CYQK32' => ['type' => 'qd','id' => 31 ,'key' => ''],
        'JBDM33'=> ['type' => 'qd','id' => 32 ,'key' => 'ICD10_ID1'],
        'QTZD33' => ['type' => 'qd','id' => 32 ,'key' => 'ICD10_NAME'],
        'RYBQ33' => ['type' => 'qd','id' => 32 ,'key' => 'RYQK'],
        'CYQK33' => ['type' => 'qd','id' => 32 ,'key' => ''],
        'JBDM34'=> ['type' => 'qd','id' => 33 ,'key' => 'ICD10_ID1'],
        'QTZD34' => ['type' => 'qd','id' => 33 ,'key' => 'ICD10_NAME'],
        'RYBQ34' => ['type' => 'qd','id' => 33 ,'key' => 'RYQK'],
        'CYQK34' => ['type' => 'qd','id' => 33 ,'key' => ''],
        'JBDM35'=> ['type' => 'qd','id' => 34 ,'key' => 'ICD10_ID1'],
        'QTZD35' => ['type' => 'qd','id' => 34 ,'key' => 'ICD10_NAME'],
        'RYBQ35' => ['type' => 'qd','id' => 34 ,'key' => 'RYQK'],
        'CYQK35' => ['type' => 'qd','id' => 34 ,'key' => ''],
        'JBDM36'=> ['type' => 'qd','id' => 35 ,'key' => 'ICD10_ID1'],
        'QTZD36' => ['type' => 'qd','id' => 35 ,'key' => 'ICD10_NAME'],
        'RYBQ36' => ['type' => 'qd','id' => 35 ,'key' => 'RYQK'],
        'CYQK36' => ['type' => 'qd','id' => 35 ,'key' => ''],
        'JBDM37'=> ['type' => 'qd','id' => 36 ,'key' => 'ICD10_ID1'],
        'QTZD37' => ['type' => 'qd','id' => 36 ,'key' => 'ICD10_NAME'],
        'RYBQ37' => ['type' => 'qd','id' => 36 ,'key' => 'RYQK'],
        'CYQK37' => ['type' => 'qd','id' => 36 ,'key' => ''],
        'JBDM38'=> ['type' => 'qd','id' => 37 ,'key' => 'ICD10_ID1'],
        'QTZD38' => ['type' => 'qd','id' => 37 ,'key' => 'ICD10_NAME'],
        'RYBQ38' => ['type' => 'qd','id' => 37 ,'key' => 'RYQK'],
        'CYQK38' => ['type' => 'qd','id' => 37 ,'key' => ''],
        'JBDM39'=> ['type' => 'qd','id' => 38 ,'key' => 'ICD10_ID1'],
        'QTZD39' => ['type' => 'qd','id' => 38 ,'key' => 'ICD10_NAME'],
        'RYBQ39' => ['type' => 'qd','id' => 38 ,'key' => 'RYQK'],
        'CYQK39' => ['type' => 'qd','id' => 38 ,'key' => ''],
        'JBDM40'=> ['type' => 'qd','id' => 39 ,'key' => 'ICD10_ID1'],
        'QTZD40' => ['type' => 'qd','id' => 39 ,'key' => 'ICD10_NAME'],
        'RYBQ40' => ['type' => 'qd','id' => 39 ,'key' => 'RYQK'],
        'CYQK40' => ['type' => 'qd','id' => 39 ,'key' => ''],
        'WBYY' => 'ABG01N',
        'H23' => 'ABG01C',
        'BLZD' => 'ABF01N',
        'JBMM' => 'ABF01C',
        'BLH' => 'ABF04',
        'ICDO3' => '',
        'ZGZDYJ' => 'ABF02C',
        'YWGM' => 'AEB02C',
        'GMYW' => 'AEB01',
        'SWHZSJ' => 'AEI01C',
        'XX' => 'AEG01C',
        'RH' => 'AEG02C',
        'HBSAG' => 'HB',
        'HCVAb' => 'HCV',
        'HIVAb' => 'HIV',
        'SXFY' => 'AFA08',
        'HXB' => 'AEG04',
        'XXB' => 'AEG05',
        'XJ' => 'AEG06',
        'QX' => 'AEG07',
        'ZTXHS' => '',
        'TJHL_T' => 'TJHL',
        'YJHL_T' => 'YJHL',
        'EJHL_T' => 'EJHL',
        'SJHL_T' => 'SJHL',
        'SFWRJSS' => ['type' => 'ms','id' => 0 ,'key' => 'RJSS'],
        'YCHXJSYSJ' => 'AEL01',
        'ZZJHSMC1' =>['type' => 'icu','id' => 0 ,'key' => 'IS_MAIN_WAY'],
        'JRSJ1' =>['type' => 'icu','id' => 0 ,'key' => 'IN_TIME'],
        'TCSJ1' =>['type' => 'icu','id' => 0 ,'key' => 'OUT_TIME'],
        'ZZJHSMC2' =>['type' => 'icu','id' => 1 ,'key' => 'IS_MAIN_WAY'],
        'JRSJ2' =>['type' => 'icu','id' => 1 ,'key' => 'IN_TIME'],
        'TCSJ2' =>['type' => 'icu','id' => 1 ,'key' => 'OUT_TIME'],
        'ZZJHSMC3' =>['type' => 'icu','id' => 2 ,'key' => 'IS_MAIN_WAY'],
        'JRSJ3' =>['type' => 'icu','id' => 2 ,'key' => 'IN_TIME'],
        'TCSJ3' =>['type' => 'icu','id' => 2 ,'key' => 'OUT_TIME'],
        'ZZJHSMC4' =>['type' => 'icu','id' => 3 ,'key' => 'IS_MAIN_WAY'],
        'JRSJ4' =>['type' => 'icu','id' => 3 ,'key' => 'IN_TIME'],
        'TCSJ4' =>['type' => 'icu','id' => 3 ,'key' => 'OUT_TIME'],
        'ZZJHSMC5' =>['type' => 'icu','id' => 4 ,'key' => 'IS_MAIN_WAY'],
        'JRSJ5' =>['type' => 'icu','id' => 4 ,'key' => 'IN_TIME'],
        'TCSJ5' =>['type' => 'icu','id' => 4 ,'key' => 'OUT_TIME'],
        'KZRBM' => 'AEE01_CODE',
        'KZRSFZH' => 'AEE01_SFZ',
        'KZR' => 'AEE01',
        'YLZZBM' => 'AEE09_CODE',
        'YLZZSFZH' => 'AEE09_SFZ',
        'YLZZ' => 'AEE09',
        'ZRYSBM' => 'ZHFZRYS',
        'ZRYSSFZH' => 'ZHFZRYS_SFZ',
        'ZRYS' => 'ZHFZRYSXM',
        'ZZYSBM' => 'ZZYSBM',
        'ZZYSSFZH' => 'ZZYS_SFZ',
        'ZZYS' => 'ZZYSXM',
        'ZYYSBM' => 'ZYYSBM',
        'ZYYSSFZH' => 'ZYYS_SFZ',
        'ZYYS' => 'ZYYSXM',
        'ZRHSBM' => 'ZRHSBM',
        'ZRHSSFZH' => 'ZRHS_SFZ',
        'ZRHS' => 'ZRHS',
        'JXYSBM' => 'AEE05_CODE',
        'JXYSSFZH' => 'AEE05_SFZ',
        'JXYS' => 'AEE05',
        'SXYS' => 'AEE07',
        'BMYSFZH' => 'BMY_SFZ',
        'BMY' => 'BMY',
        'BAZL' =>'AED01C',
        'ZKRQ' => 'AED04',
        'ZKYSBM' => 'AED02_CODE',
        'ZKYSSFZH' => 'AED02_SFZ',
        'ZKYS' => 'AED02',
        'ZKHSBM' => 'ZKHSBM',
        'ZKHSSFZH' => 'ZKHS_SFZ',
        'ZKHS' => 'ZKHS',
        'SSJCZBM1' => ['type' => 'ms','id' => 0 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ1' => ['type' => 'ms','id' => 0 ,'key' => 'OPE_DATE'],
        'SSJCZMC1' => ['type' => 'ms','id' => 0 ,'key' => 'ICD9_NAME'],
        'SSJB1' => ['type' => 'ms','id' => 0 ,'key' => 'OPE_LEVEL'],
        'SSLX1' => ['type' => 'ms','id' => 0 ,'key' => 'OPE_TYPE'],
        'SZ1' => ['type' => 'ms','id' => 0 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH1' => ['type' => 'ms','id' => 0 ,'key' => 'OPE_MAN'],
        'SZBM1' => ['type' => 'ms','id' => 0 ,'key' => 'OPE_MAN_CODE'],
        'YZ1' => ['type' => 'ms','id' => 0 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH1' => ['type' => 'ms','id' => 0 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM1' => ['type' => 'ms','id' => 0 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ1' => ['type' => 'ms','id' => 0 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH1' => ['type' => 'ms','id' => 0 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM1' => ['type' => 'ms','id' => 0 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ1' => ['type' => 'ms','id' => 0 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB1' => ['type' => 'ms','id' => 0 ,'key' => 'HEAL_ID'],
        'MZFS1' => ['type' => 'ms','id' => 0 ,'key' => 'HOCUS_WAY_ID'],
        'MZYS1' => ['type' => 'ms','id' => 0 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYSBM1' => ['type' => 'ms','id' => 0 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH1' => ['type' => 'ms','id' => 0 ,'key' => 'HOCUS_MAN'],
        'MZFJ1' => ['type' => 'ms','id' => 0 ,'key' => ''],
        'SSCXSJ1' => ['type' => 'ms','id' => 0 ,'key' => 'es'],
        'SSJCZBM2' => ['type' => 'qs','id' => 0 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ2' => ['type' => 'qs','id' => 0 ,'key' => 'OPE_DATE'],
        'SSJCZMC2' => ['type' => 'qs','id' => 0 ,'key' => 'ICD9_NAME'],
        'SSJB2' => ['type' => 'qs','id' => 0 ,'key' => 'OPE_LEVEL'],
        'SSLX2' => ['type' => 'qs','id' => 0 ,'key' => 'OPE_TYPE'],
        'SZ2' => ['type' => 'qs','id' => 0 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH2' => ['type' => 'qs','id' => 0 ,'key' => 'OPE_MAN'],
        'SZBM2' => ['type' => 'qs','id' => 0 ,'key' => 'OPE_MAN_CODE'],
        'YZ2' => ['type' => 'qs','id' => 0 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH2' => ['type' => 'qs','id' =>0 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM2' => ['type' => 'qs','id' =>0 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ2' => ['type' => 'qs','id' => 0 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH2' => ['type' => 'qs','id' =>0 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM2' => ['type' => 'qs','id' => 0 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ2' => ['type' => 'qs','id' => 0 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB2' => ['type' => 'qs','id' => 0 ,'key' => 'HEAL_ID'],
        'MZFS2' => ['type' => 'qs','id' => 0 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS2' => ['type' => 'qs','id' => 0 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM2' => ['type' => 'qs','id' => 0 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH2' => ['type' => 'qs','id' => 0 ,'key' => 'HOCUS_MAN'],
        'MZFJ2' => ['type' => 'qs','id' => 0 ,'key' => ''],
        'SSCXSJ2' => ['type' => 'qs','id' => 0 ,'key' => 'es'],

        'SSJCZBM3' => ['type' => 'qs','id' => 1 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ3' => ['type' => 'qs','id' => 1 ,'key' => 'OPE_DATE'],
        'SSJCZMC3' => ['type' => 'qs','id' => 1 ,'key' => 'ICD9_NAME'],
        'SSJB3' => ['type' => 'qs','id' => 1 ,'key' => 'OPE_LEVEL'],
        'SSLX3' => ['type' => 'qs','id' => 1 ,'key' => 'OPE_TYPE'],
        'SZ3' => ['type' => 'qs','id' => 1 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH3' => ['type' => 'qs','id' => 1 ,'key' => 'OPE_MAN'],
        'SZBM3' => ['type' => 'qs','id' => 1 ,'key' => 'OPE_MAN_CODE'],
        'YZ3' => ['type' => 'qs','id' => 1 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH3' => ['type' => 'qs','id' => 1 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM3' => ['type' => 'qs','id' => 1 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ3' => ['type' => 'qs','id' => 1 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH3' => ['type' => 'qs','id' => 1 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM3' => ['type' => 'qs','id' => 1 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ3' => ['type' => 'qs','id' => 1 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB3' => ['type' => 'qs','id' => 1 ,'key' => 'HEAL_ID'],
        'MZFS3' => ['type' => 'qs','id' => 1 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS3' => ['type' => 'qs','id' => 1 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM3' => ['type' => 'qs','id' => 1 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH3' => ['type' => 'qs','id' => 1 ,'key' => 'HOCUS_MAN'],
        'MZFJ3' => ['type' => 'qs','id' => 1 ,'key' => ''],
        'SSCXSJ3' => ['type' => 'qs','id' => 1 ,'key' => 'es'],

        'SSJCZBM4' => ['type' => 'qs','id' => 2 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ4' => ['type' => 'qs','id' => 2 ,'key' => 'OPE_DATE'],
        'SSJCZMC4' => ['type' => 'qs','id' => 2 ,'key' => 'ICD9_NAME'],
        'SSJB4' => ['type' => 'qs','id' => 2 ,'key' => 'OPE_LEVEL'],
        'SSLX4' => ['type' => 'qs','id' => 2 ,'key' => 'OPE_TYPE'],
        'SZ4' => ['type' => 'qs','id' => 2 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH4' => ['type' => 'qs','id' => 2 ,'key' => 'OPE_MAN'],
        'SZBM4' => ['type' => 'qs','id' => 2 ,'key' => 'OPE_MAN_CODE'],
        'YZ4' => ['type' => 'qs','id' => 2 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH4' => ['type' => 'qs','id' => 2 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM4' => ['type' => 'qs','id' => 2 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ4' => ['type' => 'qs','id' => 2 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH4' => ['type' => 'qs','id' => 2 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM4' => ['type' => 'qs','id' => 2 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ4' => ['type' => 'qs','id' => 2 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB4' => ['type' => 'qs','id' => 2 ,'key' => 'HEAL_ID'],
        'MZFS4' => ['type' => 'qs','id' => 2 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS4' => ['type' => 'qs','id' => 2 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM4' => ['type' => 'qs','id' => 2 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH4' => ['type' => 'qs','id' => 2 ,'key' => 'HOCUS_MAN'],
        'MZFJ4' => ['type' => 'qs','id' => 2 ,'key' => ''],
        'SSCXSJ4' => ['type' => 'qs','id' => 2 ,'key' => 'es'],
        'SSJCZBM5' => ['type' => 'qs','id' => 3 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ5' => ['type' => 'qs','id' => 3 ,'key' => 'OPE_DATE'],
        'SSJCZMC5' => ['type' => 'qs','id' => 3 ,'key' => 'ICD9_NAME'],
        'SSJB5' => ['type' => 'qs','id' => 3 ,'key' => 'OPE_LEVEL'],
        'SSLX5' => ['type' => 'qs','id' => 3 ,'key' => 'OPE_TYPE'],
        'SZ5' => ['type' => 'qs','id' => 3 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH5' => ['type' => 'qs','id' => 3 ,'key' => 'OPE_MAN'],
        'SZBM5' => ['type' => 'qs','id' => 3 ,'key' => 'OPE_MAN_CODE'],
        'YZ5' => ['type' => 'qs','id' => 3 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH5' => ['type' => 'qs','id' => 3 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM5' => ['type' => 'qs','id' => 3 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ5' => ['type' => 'qs','id' => 3 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH5' => ['type' => 'qs','id' => 3 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM5' => ['type' => 'qs','id' => 3 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ5' => ['type' => 'qs','id' => 3 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB5' => ['type' => 'qs','id' => 3 ,'key' => 'HEAL_ID'],
        'MZFS5' => ['type' => 'qs','id' => 3 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS5' => ['type' => 'qs','id' => 3 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM5' => ['type' => 'qs','id' => 3 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH5' => ['type' => 'qs','id' => 3 ,'key' => 'HOCUS_MAN'],
        'MZFJ5' => ['type' => 'qs','id' => 3 ,'key' => ''],
        'SSCXSJ5' => ['type' => 'qs','id' => 3 ,'key' => 'es'],
        'SSJCZBM6' => ['type' => 'qs','id' => 4 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ6' => ['type' => 'qs','id' => 4 ,'key' => 'OPE_DATE'],
        'SSJCZMC6' => ['type' => 'qs','id' => 4 ,'key' => 'ICD9_NAME'],
        'SSJB6' => ['type' => 'qs','id' => 4 ,'key' => 'OPE_LEVEL'],
        'SSLX6' => ['type' => 'qs','id' => 4 ,'key' => 'OPE_TYPE'],
        'SZ6' => ['type' => 'qs','id' => 4 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH6' => ['type' => 'qs','id' => 4 ,'key' => 'OPE_MAN'],
        'SZBM6' => ['type' => 'qs','id' => 4 ,'key' => 'OPE_MAN_CODE'],
        'YZ6' => ['type' => 'qs','id' => 4 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH6' => ['type' => 'qs','id' => 4 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM6' => ['type' => 'qs','id' => 4 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ6' => ['type' => 'qs','id' => 4 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH6' => ['type' => 'qs','id' => 4 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM6' => ['type' => 'qs','id' => 4 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ6' => ['type' => 'qs','id' => 4 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB6' => ['type' => 'qs','id' => 4 ,'key' => 'HEAL_ID'],
        'MZFS6' => ['type' => 'qs','id' => 4 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS6' => ['type' => 'qs','id' => 4 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM6' => ['type' => 'qs','id' => 4 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH6' => ['type' => 'qs','id' => 4 ,'key' => 'HOCUS_MAN'],
        'MZFJ6' => ['type' => 'qs','id' => 4 ,'key' => ''],
        'SSCXSJ6' => ['type' => 'qs','id' => 4 ,'key' => 'es'],
        'SSJCZBM7' => ['type' => 'qs','id' => 5 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ7' => ['type' => 'qs','id' => 5 ,'key' => 'OPE_DATE'],
        'SSJCZMC7' => ['type' => 'qs','id' => 5 ,'key' => 'ICD9_NAME'],
        'SSJB7' => ['type' => 'qs','id' => 5 ,'key' => 'OPE_LEVEL'],
        'SSLX7' => ['type' => 'qs','id' => 5 ,'key' => 'OPE_TYPE'],
        'SZ7' => ['type' => 'qs','id' => 5 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH7' => ['type' => 'qs','id' => 5 ,'key' => 'OPE_MAN'],
        'SZBM7' => ['type' => 'qs','id' => 5 ,'key' => 'OPE_MAN_CODE'],
        'YZ7' => ['type' => 'qs','id' => 5 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH7' => ['type' => 'qs','id' => 5 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM7' => ['type' => 'qs','id' => 5 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ7' => ['type' => 'qs','id' => 5 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH7' => ['type' => 'qs','id' => 5 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM7' => ['type' => 'qs','id' => 5 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ7' => ['type' => 'qs','id' => 5 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB7' => ['type' => 'qs','id' => 5 ,'key' => 'HEAL_ID'],
        'MZFS7' => ['type' => 'qs','id' => 5 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS7' => ['type' => 'qs','id' => 5 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM7' => ['type' => 'qs','id' => 5 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH7' => ['type' => 'qs','id' => 5 ,'key' => 'HOCUS_MAN'],
        'MZFJ7' => ['type' => 'qs','id' => 5 ,'key' => ''],
        'SSCXSJ7' => ['type' => 'qs','id' => 5 ,'key' => 'es'],
        'SSJCZBM8' => ['type' => 'qs','id' => 6 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ8' => ['type' => 'qs','id' => 6 ,'key' => 'OPE_DATE'],
        'SSJCZMC8' => ['type' => 'qs','id' => 6 ,'key' => 'ICD9_NAME'],
        'SSJB8' => ['type' => 'qs','id' => 6 ,'key' => 'OPE_LEVEL'],
        'SSLX8' => ['type' => 'qs','id' => 6 ,'key' => 'OPE_TYPE'],
        'SZ8' => ['type' => 'qs','id' => 6 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH8' => ['type' => 'qs','id' => 6 ,'key' => 'OPE_MAN'],
        'SZBM8' => ['type' => 'qs','id' => 6 ,'key' => 'OPE_MAN_CODE'],
        'YZ8' => ['type' => 'qs','id' => 6 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH8' => ['type' => 'qs','id' => 6 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM8' => ['type' => 'qs','id' => 6 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ8' => ['type' => 'qs','id' => 6 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH8' => ['type' => 'qs','id' => 6 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM8' => ['type' => 'qs','id' => 6 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ8' => ['type' => 'qs','id' => 6 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB8' => ['type' => 'qs','id' => 6 ,'key' => 'HEAL_ID'],
        'MZFS8' => ['type' => 'qs','id' => 6 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS8' => ['type' => 'qs','id' => 6 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM8' => ['type' => 'qs','id' => 6 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH8' => ['type' => 'qs','id' => 6 ,'key' => 'HOCUS_MAN'],
        'MZFJ8' => ['type' => 'qs','id' => 6 ,'key' => ''],
        'SSCXSJ8' => ['type' => 'qs','id' => 6 ,'key' => 'es'],
        'SSJCZBM9' => ['type' => 'qs','id' => 7 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ9' => ['type' => 'qs','id' => 7 ,'key' => 'OPE_DATE'],
        'SSJCZMC9' => ['type' => 'qs','id' => 7 ,'key' => 'ICD9_NAME'],
        'SSJB9' => ['type' => 'qs','id' => 7 ,'key' => 'OPE_LEVEL'],
        'SSLX9' => ['type' => 'qs','id' => 7 ,'key' => 'OPE_TYPE'],
        'SZ9' => ['type' => 'qs','id' => 7 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH9' => ['type' => 'qs','id' => 7 ,'key' => 'OPE_MAN'],
        'SZBM9' => ['type' => 'qs','id' => 7 ,'key' => 'OPE_MAN_CODE'],
        'YZ9' => ['type' => 'qs','id' => 7 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH9' => ['type' => 'qs','id' => 7 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM9' => ['type' => 'qs','id' => 7 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ9' => ['type' => 'qs','id' => 7 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH9' => ['type' => 'qs','id' => 7 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM9' => ['type' => 'qs','id' => 7 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ9' => ['type' => 'qs','id' => 7 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB9' => ['type' => 'qs','id' => 7 ,'key' => 'HEAL_ID'],
        'MZFS9' => ['type' => 'qs','id' => 7 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS9' => ['type' => 'qs','id' => 7 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM9' => ['type' => 'qs','id' => 7 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH9' => ['type' => 'qs','id' => 7 ,'key' => 'HOCUS_MAN'],
        'MZFJ9' => ['type' => 'qs','id' => 7 ,'key' => ''],
        'SSCXSJ9' => ['type' => 'qs','id' => 7 ,'key' => 'es'],
        'SSJCZBM10' => ['type' => 'qs','id' => 8 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ10' => ['type' => 'qs','id' => 8 ,'key' => 'OPE_DATE'],
        'SSJCZMC10' => ['type' => 'qs','id' => 8 ,'key' => 'ICD9_NAME'],
        'SSJB10' => ['type' => 'qs','id' => 8 ,'key' => 'OPE_LEVEL'],
        'SSLX10' => ['type' => 'qs','id' => 8 ,'key' => 'OPE_TYPE'],
        'SZ10' => ['type' => 'qs','id' => 8 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH10' => ['type' => 'qs','id' => 8 ,'key' => 'OPE_MAN'],
        'SZBM10' => ['type' => 'qs','id' => 8 ,'key' => 'OPE_MAN_CODE'],
        'YZ10' => ['type' => 'qs','id' => 8 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH10' => ['type' => 'qs','id' => 8 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM10' => ['type' => 'qs','id' => 8 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ10' => ['type' => 'qs','id' => 8 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH10' => ['type' => 'qs','id' => 8 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM10' => ['type' => 'qs','id' => 8 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ10' => ['type' => 'qs','id' => 8 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB10' => ['type' => 'qs','id' => 8 ,'key' => 'HEAL_ID'],
        'MZFS10' => ['type' => 'qs','id' => 8 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS10' => ['type' => 'qs','id' => 8 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM10' => ['type' => 'qs','id' => 8 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH10' => ['type' => 'qs','id' => 8 ,'key' => 'HOCUS_MAN'],
        'MZFJ10' => ['type' => 'qs','id' => 8 ,'key' => ''],
        'SSCXSJ10' => ['type' => 'qs','id' => 8 ,'key' => 'es'],
        'SSJCZBM11' => ['type' => 'qs','id' => 9 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ11' => ['type' => 'qs','id' => 9 ,'key' => 'OPE_DATE'],
        'SSJCZMC11' => ['type' => 'qs','id' => 9 ,'key' => 'ICD9_NAME'],
        'SSJB11' => ['type' => 'qs','id' => 9 ,'key' => 'OPE_LEVEL'],
        'SSLX11' => ['type' => 'qs','id' => 9 ,'key' => 'OPE_TYPE'],
        'SZ11' => ['type' => 'qs','id' => 9 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH11' => ['type' => 'qs','id' => 9 ,'key' => 'OPE_MAN'],
        'SZBM11' => ['type' => 'qs','id' => 9 ,'key' => 'OPE_MAN_CODE'],
        'YZ11' => ['type' => 'qs','id' => 9 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH11' => ['type' => 'qs','id' => 9 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM11' => ['type' => 'qs','id' => 9 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ11' => ['type' => 'qs','id' => 9 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH11' => ['type' => 'qs','id' => 9 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM11' => ['type' => 'qs','id' => 9 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ11' => ['type' => 'qs','id' => 9 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB11' => ['type' => 'qs','id' => 9 ,'key' => 'HEAL_ID'],
        'MZFS11' => ['type' => 'qs','id' => 9 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS11' => ['type' => 'qs','id' => 9 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM11' => ['type' => 'qs','id' => 9 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH11' => ['type' => 'qs','id' => 9 ,'key' => 'HOCUS_MAN'],
        'MZFJ11' => ['type' => 'qs','id' => 9 ,'key' => ''],
        'SSCXSJ11' => ['type' => 'qs','id' => 9 ,'key' => 'es'],
        'SSJCZBM12' => ['type' => 'qs','id' => 10 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ12' => ['type' => 'qs','id' => 10 ,'key' => 'OPE_DATE'],
        'SSJCZMC12' => ['type' => 'qs','id' => 10 ,'key' => 'ICD9_NAME'],
        'SSJB12' => ['type' => 'qs','id' => 10 ,'key' => 'OPE_LEVEL'],
        'SSLX12' => ['type' => 'qs','id' => 10 ,'key' => 'OPE_TYPE'],
        'SZ12' => ['type' => 'qs','id' => 10 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH12' => ['type' => 'qs','id' => 10 ,'key' => 'OPE_MAN'],
        'SZBM12' => ['type' => 'qs','id' => 10 ,'key' => 'OPE_MAN_CODE'],
        'YZ12' => ['type' => 'qs','id' => 10 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH12' => ['type' => 'qs','id' => 10 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM12' => ['type' => 'qs','id' => 10 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ12' => ['type' => 'qs','id' => 10 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH12' => ['type' => 'qs','id' => 10 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM12' => ['type' => 'qs','id' => 10 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ12' => ['type' => 'qs','id' => 10 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB12' => ['type' => 'qs','id' => 10 ,'key' => 'HEAL_ID'],
        'MZFS12' => ['type' => 'qs','id' => 10 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS12' => ['type' => 'qs','id' => 10 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM12' => ['type' => 'qs','id' => 10 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH12' => ['type' => 'qs','id' => 10 ,'key' => 'HOCUS_MAN'],
        'MZFJ12' => ['type' => 'qs','id' => 10 ,'key' => ''],
        'SSCXSJ12' => ['type' => 'qs','id' => 10 ,'key' => 'es'],
        'SSJCZBM13' => ['type' => 'qs','id' => 11 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ13' => ['type' => 'qs','id' => 11 ,'key' => 'OPE_DATE'],
        'SSJCZMC13' => ['type' => 'qs','id' => 11 ,'key' => 'ICD9_NAME'],
        'SSJB13' => ['type' => 'qs','id' => 11 ,'key' => 'OPE_LEVEL'],
        'SSLX13' => ['type' => 'qs','id' => 11 ,'key' => 'OPE_TYPE'],
        'SZ13' => ['type' => 'qs','id' => 11 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH13' => ['type' => 'qs','id' => 11 ,'key' => 'OPE_MAN'],
        'SZBM13' => ['type' => 'qs','id' => 11 ,'key' => 'OPE_MAN_CODE'],
        'YZ13' => ['type' => 'qs','id' => 11 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH13' => ['type' => 'qs','id' => 11 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM13' => ['type' => 'qs','id' => 11 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ13' => ['type' => 'qs','id' => 11 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH13' => ['type' => 'qs','id' => 11 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM13' => ['type' => 'qs','id' => 11 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ13' => ['type' => 'qs','id' => 11 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB13' => ['type' => 'qs','id' => 11 ,'key' => 'HEAL_ID'],
        'MZFS13' => ['type' => 'qs','id' => 11 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS13' => ['type' => 'qs','id' => 11 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM13' => ['type' => 'qs','id' => 11 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH13' => ['type' => 'qs','id' => 11 ,'key' => 'HOCUS_MAN'],
        'MZFJ13' => ['type' => 'qs','id' => 11 ,'key' => ''],
        'SSCXSJ13' => ['type' => 'qs','id' => 11 ,'key' => 'es'],
        'SSJCZBM14' => ['type' => 'qs','id' => 12 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ14' => ['type' => 'qs','id' => 12 ,'key' => 'OPE_DATE'],
        'SSJCZMC14' => ['type' => 'qs','id' => 12 ,'key' => 'ICD9_NAME'],
        'SSJB14' => ['type' => 'qs','id' => 12 ,'key' => 'OPE_LEVEL'],
        'SSLX14' => ['type' => 'qs','id' => 12 ,'key' => 'OPE_TYPE'],
        'SZ14' => ['type' => 'qs','id' => 12 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH14' => ['type' => 'qs','id' => 12 ,'key' => 'OPE_MAN'],
        'SZBM14' => ['type' => 'qs','id' => 12 ,'key' => 'OPE_MAN_CODE'],
        'YZ14' => ['type' => 'qs','id' => 12 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH14' => ['type' => 'qs','id' => 12 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM14' => ['type' => 'qs','id' => 12 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ14' => ['type' => 'qs','id' => 12 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH14' => ['type' => 'qs','id' => 12 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM14' => ['type' => 'qs','id' => 12 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ14' => ['type' => 'qs','id' => 12 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB14' => ['type' => 'qs','id' => 12 ,'key' => 'HEAL_ID'],
        'MZFS14' => ['type' => 'qs','id' => 12 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS14' => ['type' => 'qs','id' => 12 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM14' => ['type' => 'qs','id' => 12 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH14' => ['type' => 'qs','id' => 12 ,'key' => 'HOCUS_MAN'],
        'MZFJ14' => ['type' => 'qs','id' => 12 ,'key' => ''],
        'SSCXSJ14' => ['type' => 'qs','id' => 12 ,'key' => 'es'],
        'SSJCZBM15' => ['type' => 'qs','id' => 13 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ15' => ['type' => 'qs','id' => 13 ,'key' => 'OPE_DATE'],
        'SSJCZMC15' => ['type' => 'qs','id' => 13 ,'key' => 'ICD9_NAME'],
        'SSJB15' => ['type' => 'qs','id' => 13 ,'key' => 'OPE_LEVEL'],
        'SSLX15' => ['type' => 'qs','id' => 13 ,'key' => 'OPE_TYPE'],
        'SZ15' => ['type' => 'qs','id' => 13 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH15' => ['type' => 'qs','id' => 13 ,'key' => 'OPE_MAN'],
        'SZBM15' => ['type' => 'qs','id' => 13 ,'key' => 'OPE_MAN_CODE'],
        'YZ15' => ['type' => 'qs','id' => 13 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH15' => ['type' => 'qs','id' => 13 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM15' => ['type' => 'qs','id' => 13 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ15' => ['type' => 'qs','id' => 13 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH15' => ['type' => 'qs','id' => 13 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM15' => ['type' => 'qs','id' => 13 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ15' => ['type' => 'qs','id' => 13 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB15' => ['type' => 'qs','id' => 13 ,'key' => 'HEAL_ID'],
        'MZFS15' => ['type' => 'qs','id' => 13 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS15' => ['type' => 'qs','id' => 13 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM15' => ['type' => 'qs','id' => 13 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH15' => ['type' => 'qs','id' => 13 ,'key' => 'HOCUS_MAN'],
        'MZFJ15' => ['type' => 'qs','id' => 13 ,'key' => ''],
        'SSCXSJ15' => ['type' => 'qs','id' => 13 ,'key' => 'es'],
        'SSJCZBM16' => ['type' => 'qs','id' => 14 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ16' => ['type' => 'qs','id' => 14 ,'key' => 'OPE_DATE'],
        'SSJCZMC16' => ['type' => 'qs','id' => 14 ,'key' => 'ICD9_NAME'],
        'SSJB16' => ['type' => 'qs','id' => 14 ,'key' => 'OPE_LEVEL'],
        'SSLX16' => ['type' => 'qs','id' => 14 ,'key' => 'OPE_TYPE'],
        'SZ16' => ['type' => 'qs','id' => 14 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH16' => ['type' => 'qs','id' => 14 ,'key' => 'OPE_MAN'],
        'SZBM16' => ['type' => 'qs','id' => 14 ,'key' => 'OPE_MAN_CODE'],
        'YZ16' => ['type' => 'qs','id' => 14 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH16' => ['type' => 'qs','id' => 14 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM16' => ['type' => 'qs','id' => 14 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ16' => ['type' => 'qs','id' => 14 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH16' => ['type' => 'qs','id' => 14 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM16' => ['type' => 'qs','id' => 14 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ16' => ['type' => 'qs','id' => 14 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB16' => ['type' => 'qs','id' => 14 ,'key' => 'HEAL_ID'],
        'MZFS16' => ['type' => 'qs','id' => 14 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS16' => ['type' => 'qs','id' => 14 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM16' => ['type' => 'qs','id' => 14 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH16' => ['type' => 'qs','id' => 14 ,'key' => 'HOCUS_MAN'],
        'MZFJ16' => ['type' => 'qs','id' => 14 ,'key' => ''],
        'SSCXSJ16' => ['type' => 'qs','id' => 14 ,'key' => 'es'],
        'SSJCZBM17' => ['type' => 'qs','id' => 15 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ17' => ['type' => 'qs','id' => 15 ,'key' => 'OPE_DATE'],
        'SSJCZMC17' => ['type' => 'qs','id' => 15 ,'key' => 'ICD9_NAME'],
        'SSJB17' => ['type' => 'qs','id' => 15 ,'key' => 'OPE_LEVEL'],
        'SSLX17' => ['type' => 'qs','id' => 15 ,'key' => 'OPE_TYPE'],
        'SZ17' => ['type' => 'qs','id' => 15 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH17' => ['type' => 'qs','id' => 15 ,'key' => 'OPE_MAN'],
        'SZBM17' => ['type' => 'qs','id' => 15 ,'key' => 'OPE_MAN_CODE'],
        'YZ17' => ['type' => 'qs','id' => 15 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH17' => ['type' => 'qs','id' => 15 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM17' => ['type' => 'qs','id' => 15 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ17' => ['type' => 'qs','id' => 15 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH17' => ['type' => 'qs','id' => 15 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM17' => ['type' => 'qs','id' => 15 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ17' => ['type' => 'qs','id' => 15 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB17' => ['type' => 'qs','id' => 15 ,'key' => 'HEAL_ID'],
        'MZFS17' => ['type' => 'qs','id' => 15 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS17' => ['type' => 'qs','id' => 15 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM17' => ['type' => 'qs','id' => 15 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH17' => ['type' => 'qs','id' => 15 ,'key' => 'HOCUS_MAN'],
        'MZFJ17' => ['type' => 'qs','id' => 15 ,'key' => ''],
        'SSCXSJ17' => ['type' => 'qs','id' => 15 ,'key' => 'es'],
        'SSJCZBM18' => ['type' => 'qs','id' => 16 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ18' => ['type' => 'qs','id' => 16 ,'key' => 'OPE_DATE'],
        'SSJCZMC18' => ['type' => 'qs','id' => 16 ,'key' => 'ICD9_NAME'],
        'SSJB18' => ['type' => 'qs','id' => 16 ,'key' => 'OPE_LEVEL'],
        'SSLX18' => ['type' => 'qs','id' => 16 ,'key' => 'OPE_TYPE'],
        'SZ18' => ['type' => 'qs','id' => 16 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH18' => ['type' => 'qs','id' => 16 ,'key' => 'OPE_MAN'],
        'SZBM18' => ['type' => 'qs','id' => 16 ,'key' => 'OPE_MAN_CODE'],
        'YZ18' => ['type' => 'qs','id' => 16 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH18' => ['type' => 'qs','id' => 16 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM18' => ['type' => 'qs','id' => 16 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ18' => ['type' => 'qs','id' => 16 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH18' => ['type' => 'qs','id' => 16 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM18' => ['type' => 'qs','id' => 16 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ18' => ['type' => 'qs','id' => 16 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB18' => ['type' => 'qs','id' => 16 ,'key' => 'HEAL_ID'],
        'MZFS18' => ['type' => 'qs','id' => 16 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS18' => ['type' => 'qs','id' => 16 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM18' => ['type' => 'qs','id' => 16 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH18' => ['type' => 'qs','id' => 16 ,'key' => 'HOCUS_MAN'],
        'MZFJ18' => ['type' => 'qs','id' => 16 ,'key' => ''],
        'SSCXSJ18' => ['type' => 'qs','id' => 16 ,'key' => 'es'],
        'SSJCZBM19' => ['type' => 'qs','id' => 17 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ19' => ['type' => 'qs','id' => 17 ,'key' => 'OPE_DATE'],
        'SSJCZMC19' => ['type' => 'qs','id' => 17 ,'key' => 'ICD9_NAME'],
        'SSJB19' => ['type' => 'qs','id' => 17 ,'key' => 'OPE_LEVEL'],
        'SSLX19' => ['type' => 'qs','id' => 17 ,'key' => 'OPE_TYPE'],
        'SZ19' => ['type' => 'qs','id' => 17 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH19' => ['type' => 'qs','id' => 17 ,'key' => 'OPE_MAN'],
        'SZBM19' => ['type' => 'qs','id' => 17 ,'key' => 'OPE_MAN_CODE'],
        'YZ19' => ['type' => 'qs','id' => 17 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH19' => ['type' => 'qs','id' => 17 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM19' => ['type' => 'qs','id' => 17 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ19' => ['type' => 'qs','id' => 17 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH19' => ['type' => 'qs','id' => 17 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM19' => ['type' => 'qs','id' => 17 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ19' => ['type' => 'qs','id' => 17 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB19' => ['type' => 'qs','id' => 17 ,'key' => 'HEAL_ID'],
        'MZFS19' => ['type' => 'qs','id' => 17 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS19' => ['type' => 'qs','id' => 17 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM19' => ['type' => 'qs','id' => 17 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH19' => ['type' => 'qs','id' => 17 ,'key' => 'HOCUS_MAN'],
        'MZFJ19' => ['type' => 'qs','id' => 17 ,'key' => ''],
        'SSCXSJ19' => ['type' => 'qs','id' => 17 ,'key' => 'es'],
        'SSJCZBM20' => ['type' => 'qs','id' => 18 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ20' => ['type' => 'qs','id' => 18 ,'key' => 'OPE_DATE'],
        'SSJCZMC20' => ['type' => 'qs','id' => 18 ,'key' => 'ICD9_NAME'],
        'SSJB20' => ['type' => 'qs','id' => 18 ,'key' => 'OPE_LEVEL'],
        'SSLX20' => ['type' => 'qs','id' => 18 ,'key' => 'OPE_TYPE'],
        'SZ20' => ['type' => 'qs','id' => 18 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH20' => ['type' => 'qs','id' => 18 ,'key' => 'OPE_MAN'],
        'SZBM20' => ['type' => 'qs','id' => 18 ,'key' => 'OPE_MAN_CODE'],
        'YZ20' => ['type' => 'qs','id' => 18 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH20' => ['type' => 'qs','id' => 18 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM20' => ['type' => 'qs','id' => 18 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ20' => ['type' => 'qs','id' => 18 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH20' => ['type' => 'qs','id' => 18 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM20' => ['type' => 'qs','id' => 18 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ20' => ['type' => 'qs','id' => 18 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB20' => ['type' => 'qs','id' => 18 ,'key' => 'HEAL_ID'],
        'MZFS20' => ['type' => 'qs','id' => 18 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS20' => ['type' => 'qs','id' => 18 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM20' => ['type' => 'qs','id' => 18 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH20' => ['type' => 'qs','id' => 18 ,'key' => 'HOCUS_MAN'],
        'MZFJ20' => ['type' => 'qs','id' => 18 ,'key' => ''],
        'SSCXSJ20' => ['type' => 'qs','id' => 18 ,'key' => 'es'],
        'SSJCZBM21' => ['type' => 'qs','id' => 19 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ21' => ['type' => 'qs','id' => 19 ,'key' => 'OPE_DATE'],
        'SSJCZMC21' => ['type' => 'qs','id' => 19 ,'key' => 'ICD9_NAME'],
        'SSJB21' => ['type' => 'qs','id' => 19 ,'key' => 'OPE_LEVEL'],
        'SSLX21' => ['type' => 'qs','id' => 19 ,'key' => 'OPE_TYPE'],
        'SZ21' => ['type' => 'qs','id' => 19 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH21' => ['type' => 'qs','id' => 19 ,'key' => 'OPE_MAN'],
        'SZBM21' => ['type' => 'qs','id' => 19 ,'key' => 'OPE_MAN_CODE'],
        'YZ21' => ['type' => 'qs','id' => 19 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH21' => ['type' => 'qs','id' => 19 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM21' => ['type' => 'qs','id' => 19 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ21' => ['type' => 'qs','id' => 19 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH21' => ['type' => 'qs','id' => 19 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM21' => ['type' => 'qs','id' => 19 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ21' => ['type' => 'qs','id' => 19 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB21' => ['type' => 'qs','id' => 19 ,'key' => 'HEAL_ID'],
        'MZFS21' => ['type' => 'qs','id' => 19 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS21' => ['type' => 'qs','id' => 19 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM21' => ['type' => 'qs','id' => 19 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH21' => ['type' => 'qs','id' => 19 ,'key' => 'HOCUS_MAN'],
        'MZFJ21' => ['type' => 'qs','id' => 19 ,'key' => ''],
        'SSCXSJ21' => ['type' => 'qs','id' => 19 ,'key' => 'es'],
        'SSJCZBM22' => ['type' => 'qs','id' => 20 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ22' => ['type' => 'qs','id' => 20 ,'key' => 'OPE_DATE'],
        'SSJCZMC22' => ['type' => 'qs','id' => 20 ,'key' => 'ICD9_NAME'],
        'SSJB22' => ['type' => 'qs','id' => 20 ,'key' => 'OPE_LEVEL'],
        'SSLX22' => ['type' => 'qs','id' => 20 ,'key' => 'OPE_TYPE'],
        'SZ22' => ['type' => 'qs','id' => 20 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH22' => ['type' => 'qs','id' => 20 ,'key' => 'OPE_MAN'],
        'SZBM22' => ['type' => 'qs','id' => 20 ,'key' => 'OPE_MAN_CODE'],
        'YZ22' => ['type' => 'qs','id' => 20 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH22' => ['type' => 'qs','id' => 20 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM22' => ['type' => 'qs','id' => 20 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ22' => ['type' => 'qs','id' => 20 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH22' => ['type' => 'qs','id' => 20 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM22' => ['type' => 'qs','id' => 20 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ22' => ['type' => 'qs','id' => 20 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB22' => ['type' => 'qs','id' => 20 ,'key' => 'HEAL_ID'],
        'MZFS22' => ['type' => 'qs','id' => 20 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS22' => ['type' => 'qs','id' => 20 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM22' => ['type' => 'qs','id' => 20 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH22' => ['type' => 'qs','id' => 20 ,'key' => 'HOCUS_MAN'],
        'MZFJ22' => ['type' => 'qs','id' => 20 ,'key' => ''],
        'SSCXSJ22' => ['type' => 'qs','id' => 20 ,'key' => 'es'],
        'SSJCZBM23' => ['type' => 'qs','id' => 21 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ23' => ['type' => 'qs','id' => 21 ,'key' => 'OPE_DATE'],
        'SSJCZMC23' => ['type' => 'qs','id' => 21 ,'key' => 'ICD9_NAME'],
        'SSJB23' => ['type' => 'qs','id' => 21 ,'key' => 'OPE_LEVEL'],
        'SSLX23' => ['type' => 'qs','id' => 21 ,'key' => 'OPE_TYPE'],
        'SZ23' => ['type' => 'qs','id' => 21 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH23' => ['type' => 'qs','id' => 21 ,'key' => 'OPE_MAN'],
        'SZBM23' => ['type' => 'qs','id' => 21 ,'key' => 'OPE_MAN_CODE'],
        'YZ23' => ['type' => 'qs','id' => 21 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH23' => ['type' => 'qs','id' => 21 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM23' => ['type' => 'qs','id' => 21 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ23' => ['type' => 'qs','id' => 21 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH23' => ['type' => 'qs','id' => 21 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM23' => ['type' => 'qs','id' => 21 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ23' => ['type' => 'qs','id' => 21 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB23' => ['type' => 'qs','id' => 21 ,'key' => 'HEAL_ID'],
        'MZFS23' => ['type' => 'qs','id' => 21 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS23' => ['type' => 'qs','id' => 21 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM23' => ['type' => 'qs','id' => 21 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH23' => ['type' => 'qs','id' => 21 ,'key' => 'HOCUS_MAN'],
        'MZFJ23' => ['type' => 'qs','id' => 21 ,'key' => ''],
        'SSCXSJ23' => ['type' => 'qs','id' => 21 ,'key' => 'es'],
        'SSJCZBM24' => ['type' => 'qs','id' => 22 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ24' => ['type' => 'qs','id' => 22 ,'key' => 'OPE_DATE'],
        'SSJCZMC24' => ['type' => 'qs','id' => 22 ,'key' => 'ICD9_NAME'],
        'SSJB24' => ['type' => 'qs','id' => 22 ,'key' => 'OPE_LEVEL'],
        'SSLX24' => ['type' => 'qs','id' => 22 ,'key' => 'OPE_TYPE'],
        'SZ24' => ['type' => 'qs','id' => 22 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH24' => ['type' => 'qs','id' => 22 ,'key' => 'OPE_MAN'],
        'SZBM24' => ['type' => 'qs','id' => 22 ,'key' => 'OPE_MAN_CODE'],
        'YZ24' => ['type' => 'qs','id' => 22 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH24' => ['type' => 'qs','id' => 22 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM24' => ['type' => 'qs','id' => 22 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ24' => ['type' => 'qs','id' => 22 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH24' => ['type' => 'qs','id' => 22 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM24' => ['type' => 'qs','id' => 22 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ24' => ['type' => 'qs','id' => 22 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB24' => ['type' => 'qs','id' => 22 ,'key' => 'HEAL_ID'],
        'MZFS24' => ['type' => 'qs','id' => 22 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS24' => ['type' => 'qs','id' => 22 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM24' => ['type' => 'qs','id' => 22 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH24' => ['type' => 'qs','id' => 22 ,'key' => 'HOCUS_MAN'],
        'MZFJ24' => ['type' => 'qs','id' => 22 ,'key' => ''],
        'SSCXSJ24' => ['type' => 'qs','id' => 22 ,'key' => 'es'],
        'SSJCZBM25' => ['type' => 'qs','id' => 23 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ25' => ['type' => 'qs','id' => 23 ,'key' => 'OPE_DATE'],
        'SSJCZMC25' => ['type' => 'qs','id' => 23 ,'key' => 'ICD9_NAME'],
        'SSJB25' => ['type' => 'qs','id' => 23 ,'key' => 'OPE_LEVEL'],
        'SSLX25' => ['type' => 'qs','id' => 23 ,'key' => 'OPE_TYPE'],
        'SZ25' => ['type' => 'qs','id' => 23 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH25' => ['type' => 'qs','id' => 23 ,'key' => 'OPE_MAN'],
        'SZBM25' => ['type' => 'qs','id' => 23 ,'key' => 'OPE_MAN_CODE'],
        'YZ25' => ['type' => 'qs','id' => 23 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH25' => ['type' => 'qs','id' => 23 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM25' => ['type' => 'qs','id' => 23 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ25' => ['type' => 'qs','id' => 23 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH25' => ['type' => 'qs','id' => 23 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM25' => ['type' => 'qs','id' => 23 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ25' => ['type' => 'qs','id' => 23 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB25' => ['type' => 'qs','id' => 23 ,'key' => 'HEAL_ID'],
        'MZFS25' => ['type' => 'qs','id' => 23 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS25' => ['type' => 'qs','id' => 23 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM25' => ['type' => 'qs','id' => 23 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH25' => ['type' => 'qs','id' => 23 ,'key' => 'HOCUS_MAN'],
        'MZFJ25' => ['type' => 'qs','id' => 23 ,'key' => ''],
        'SSCXSJ25' => ['type' => 'qs','id' => 23 ,'key' => 'es'],
        'SSJCZBM26' => ['type' => 'qs','id' => 24 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ26' => ['type' => 'qs','id' => 24 ,'key' => 'OPE_DATE'],
        'SSJCZMC26' => ['type' => 'qs','id' => 24 ,'key' => 'ICD9_NAME'],
        'SSJB26' => ['type' => 'qs','id' => 24 ,'key' => 'OPE_LEVEL'],
        'SSLX26' => ['type' => 'qs','id' => 24 ,'key' => 'OPE_TYPE'],
        'SZ26' => ['type' => 'qs','id' => 24 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH26' => ['type' => 'qs','id' => 24 ,'key' => 'OPE_MAN'],
        'SZBM26' => ['type' => 'qs','id' => 24 ,'key' => 'OPE_MAN_CODE'],
        'YZ26' => ['type' => 'qs','id' => 24 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH26' => ['type' => 'qs','id' => 24 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM26' => ['type' => 'qs','id' => 24 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ26' => ['type' => 'qs','id' => 24 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH26' => ['type' => 'qs','id' => 24 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM26' => ['type' => 'qs','id' => 24 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ26' => ['type' => 'qs','id' => 24 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB26' => ['type' => 'qs','id' => 24 ,'key' => 'HEAL_ID'],
        'MZFS26' => ['type' => 'qs','id' => 24 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS26' => ['type' => 'qs','id' => 24 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM26' => ['type' => 'qs','id' => 24 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH26' => ['type' => 'qs','id' => 24 ,'key' => 'HOCUS_MAN'],
        'MZFJ26' => ['type' => 'qs','id' => 24 ,'key' => ''],
        'SSCXSJ26' => ['type' => 'qs','id' => 24 ,'key' => 'es'],
        'SSJCZBM27' => ['type' => 'qs','id' => 25 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ27' => ['type' => 'qs','id' => 25 ,'key' => 'OPE_DATE'],
        'SSJCZMC27' => ['type' => 'qs','id' => 25 ,'key' => 'ICD9_NAME'],
        'SSJB27' => ['type' => 'qs','id' => 25 ,'key' => 'OPE_LEVEL'],
        'SSLX27' => ['type' => 'qs','id' => 25 ,'key' => 'OPE_TYPE'],
        'SZ27' => ['type' => 'qs','id' => 25 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH27' => ['type' => 'qs','id' => 25 ,'key' => 'OPE_MAN'],
        'SZBM27' => ['type' => 'qs','id' => 25 ,'key' => 'OPE_MAN_CODE'],
        'YZ27' => ['type' => 'qs','id' => 25 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH27' => ['type' => 'qs','id' => 25 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM27' => ['type' => 'qs','id' => 25 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ27' => ['type' => 'qs','id' => 25 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH27' => ['type' => 'qs','id' => 25 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM27' => ['type' => 'qs','id' => 25 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ27' => ['type' => 'qs','id' => 25 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB27' => ['type' => 'qs','id' => 25 ,'key' => 'HEAL_ID'],
        'MZFS27' => ['type' => 'qs','id' => 25 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS27' => ['type' => 'qs','id' => 25 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM27' => ['type' => 'qs','id' => 25 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH27' => ['type' => 'qs','id' => 25 ,'key' => 'HOCUS_MAN'],
        'MZFJ27' => ['type' => 'qs','id' => 25 ,'key' => ''],
        'SSCXSJ27' => ['type' => 'qs','id' => 25 ,'key' => 'es'],
        'SSJCZBM28' => ['type' => 'qs','id' => 26 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ28' => ['type' => 'qs','id' => 26 ,'key' => 'OPE_DATE'],
        'SSJCZMC28' => ['type' => 'qs','id' => 26 ,'key' => 'ICD9_NAME'],
        'SSJB28' => ['type' => 'qs','id' => 26 ,'key' => 'OPE_LEVEL'],
        'SSLX28' => ['type' => 'qs','id' => 26 ,'key' => 'OPE_TYPE'],
        'SZ28' => ['type' => 'qs','id' => 26 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH28' => ['type' => 'qs','id' => 26 ,'key' => 'OPE_MAN'],
        'SZBM28' => ['type' => 'qs','id' => 26 ,'key' => 'OPE_MAN_CODE'],
        'YZ28' => ['type' => 'qs','id' => 26 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH28' => ['type' => 'qs','id' => 26 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM28' => ['type' => 'qs','id' => 26 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ28' => ['type' => 'qs','id' => 26 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH28' => ['type' => 'qs','id' => 26 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM28' => ['type' => 'qs','id' => 26 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ28' => ['type' => 'qs','id' => 26 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB28' => ['type' => 'qs','id' => 26 ,'key' => 'HEAL_ID'],
        'MZFS28' => ['type' => 'qs','id' => 26 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS28' => ['type' => 'qs','id' => 26 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM28' => ['type' => 'qs','id' => 26 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH28' => ['type' => 'qs','id' => 26 ,'key' => 'HOCUS_MAN'],
        'MZFJ28' => ['type' => 'qs','id' => 26 ,'key' => ''],
        'SSCXSJ28' => ['type' => 'qs','id' => 26 ,'key' => 'es'],
        'SSJCZBM29' => ['type' => 'qs','id' => 27 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ29' => ['type' => 'qs','id' => 27 ,'key' => 'OPE_DATE'],
        'SSJCZMC29' => ['type' => 'qs','id' => 27 ,'key' => 'ICD9_NAME'],
        'SSJB29' => ['type' => 'qs','id' => 27 ,'key' => 'OPE_LEVEL'],
        'SSLX29' => ['type' => 'qs','id' => 27 ,'key' => 'OPE_TYPE'],
        'SZ29' => ['type' => 'qs','id' => 27 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH29' => ['type' => 'qs','id' => 27 ,'key' => 'OPE_MAN'],
        'SZBM29' => ['type' => 'qs','id' => 27 ,'key' => 'OPE_MAN_CODE'],
        'YZ29' => ['type' => 'qs','id' => 27 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH29' => ['type' => 'qs','id' => 27 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM29' => ['type' => 'qs','id' => 27 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ29' => ['type' => 'qs','id' => 27 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH29' => ['type' => 'qs','id' => 27 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM29' => ['type' => 'qs','id' => 27 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ29' => ['type' => 'qs','id' => 27 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB29' => ['type' => 'qs','id' => 27 ,'key' => 'HEAL_ID'],
        'MZFS29' => ['type' => 'qs','id' => 27 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS29' => ['type' => 'qs','id' => 27 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM29' => ['type' => 'qs','id' => 27 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH29' => ['type' => 'qs','id' => 27 ,'key' => 'HOCUS_MAN'],
        'MZFJ29' => ['type' => 'qs','id' => 27 ,'key' => ''],
        'SSCXSJ29' => ['type' => 'qs','id' => 27 ,'key' => 'es'],
        'SSJCZBM30' => ['type' => 'qs','id' => 28 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ30' => ['type' => 'qs','id' => 28 ,'key' => 'OPE_DATE'],
        'SSJCZMC30' => ['type' => 'qs','id' => 28 ,'key' => 'ICD9_NAME'],
        'SSJB30' => ['type' => 'qs','id' => 28 ,'key' => 'OPE_LEVEL'],
        'SSLX30' => ['type' => 'qs','id' => 28 ,'key' => 'OPE_TYPE'],
        'SZ30' => ['type' => 'qs','id' => 28 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH30' => ['type' => 'qs','id' => 28 ,'key' => 'OPE_MAN'],
        'SZBM30' => ['type' => 'qs','id' => 28 ,'key' => 'OPE_MAN_CODE'],
        'YZ30' => ['type' => 'qs','id' => 28 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH30' => ['type' => 'qs','id' => 28 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM30' => ['type' => 'qs','id' => 28 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ30' => ['type' => 'qs','id' => 28 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH30' => ['type' => 'qs','id' => 28 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM30' => ['type' => 'qs','id' => 28 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ30' => ['type' => 'qs','id' => 28 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB30' => ['type' => 'qs','id' => 28 ,'key' => 'HEAL_ID'],
        'MZFS30' => ['type' => 'qs','id' => 28 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS30' => ['type' => 'qs','id' => 28 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM30' => ['type' => 'qs','id' => 28 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH30' => ['type' => 'qs','id' => 28 ,'key' => 'HOCUS_MAN'],
        'MZFJ30' => ['type' => 'qs','id' => 28 ,'key' => ''],
        'SSCXSJ30' => ['type' => 'qs','id' => 28 ,'key' => 'es'],
        'SSJCZBM31' => ['type' => 'qs','id' => 29 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ31' => ['type' => 'qs','id' => 29 ,'key' => 'OPE_DATE'],
        'SSJCZMC31' => ['type' => 'qs','id' => 29 ,'key' => 'ICD9_NAME'],
        'SSJB31' => ['type' => 'qs','id' => 29 ,'key' => 'OPE_LEVEL'],
        'SSLX31' => ['type' => 'qs','id' => 29 ,'key' => 'OPE_TYPE'],
        'SZ31' => ['type' => 'qs','id' => 29 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH31' => ['type' => 'qs','id' => 29 ,'key' => 'OPE_MAN'],
        'SZBM31' => ['type' => 'qs','id' => 29 ,'key' => 'OPE_MAN_CODE'],
        'YZ31' => ['type' => 'qs','id' => 29 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH31' => ['type' => 'qs','id' => 29 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM31' => ['type' => 'qs','id' => 29 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ31' => ['type' => 'qs','id' => 29 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH31' => ['type' => 'qs','id' => 29 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM31' => ['type' => 'qs','id' => 29 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ31' => ['type' => 'qs','id' => 29 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB31' => ['type' => 'qs','id' => 29 ,'key' => 'HEAL_ID'],
        'MZFS31' => ['type' => 'qs','id' => 29 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS31' => ['type' => 'qs','id' => 29 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM31' => ['type' => 'qs','id' => 29 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH31' => ['type' => 'qs','id' => 29 ,'key' => 'HOCUS_MAN'],
        'MZFJ31' => ['type' => 'qs','id' => 29 ,'key' => ''],
        'SSCXSJ31' => ['type' => 'qs','id' => 29 ,'key' => 'es'],
        'SSJCZBM32' => ['type' => 'qs','id' => 30 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ32' => ['type' => 'qs','id' => 30 ,'key' => 'OPE_DATE'],
        'SSJCZMC32' => ['type' => 'qs','id' => 30 ,'key' => 'ICD9_NAME'],
        'SSJB32' => ['type' => 'qs','id' => 30 ,'key' => 'OPE_LEVEL'],
        'SSLX32' => ['type' => 'qs','id' => 30 ,'key' => 'OPE_TYPE'],
        'SZ32' => ['type' => 'qs','id' => 30 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH32' => ['type' => 'qs','id' => 30 ,'key' => 'OPE_MAN'],
        'SZBM32' => ['type' => 'qs','id' => 30 ,'key' => 'OPE_MAN_CODE'],
        'YZ32' => ['type' => 'qs','id' => 30 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH32' => ['type' => 'qs','id' => 30 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM32' => ['type' => 'qs','id' => 30 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ32' => ['type' => 'qs','id' => 30 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH32' => ['type' => 'qs','id' => 30 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM32' => ['type' => 'qs','id' => 30 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ32' => ['type' => 'qs','id' => 30 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB32' => ['type' => 'qs','id' => 30 ,'key' => 'HEAL_ID'],
        'MZFS32' => ['type' => 'qs','id' => 30 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS32' => ['type' => 'qs','id' => 30 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM32' => ['type' => 'qs','id' => 30 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH32' => ['type' => 'qs','id' => 30 ,'key' => 'HOCUS_MAN'],
        'MZFJ32' => ['type' => 'qs','id' => 30 ,'key' => ''],
        'SSCXSJ32' => ['type' => 'qs','id' => 30 ,'key' => 'es'],
        'SSJCZBM33' => ['type' => 'qs','id' => 31 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ33' => ['type' => 'qs','id' => 31 ,'key' => 'OPE_DATE'],
        'SSJCZMC33' => ['type' => 'qs','id' => 31 ,'key' => 'ICD9_NAME'],
        'SSJB33' => ['type' => 'qs','id' => 31 ,'key' => 'OPE_LEVEL'],
        'SSLX33' => ['type' => 'qs','id' => 31 ,'key' => 'OPE_TYPE'],
        'SZ33' => ['type' => 'qs','id' => 31 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH33' => ['type' => 'qs','id' => 31 ,'key' => 'OPE_MAN'],
        'SZBM33' => ['type' => 'qs','id' => 31 ,'key' => 'OPE_MAN_CODE'],
        'YZ33' => ['type' => 'qs','id' => 31 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH33' => ['type' => 'qs','id' => 31 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM33' => ['type' => 'qs','id' => 31 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ33' => ['type' => 'qs','id' => 31 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH33' => ['type' => 'qs','id' => 31 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM33' => ['type' => 'qs','id' => 31 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ33' => ['type' => 'qs','id' => 31 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB33' => ['type' => 'qs','id' => 31 ,'key' => 'HEAL_ID'],
        'MZFS33' => ['type' => 'qs','id' => 31 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS33' => ['type' => 'qs','id' => 31 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM33' => ['type' => 'qs','id' => 31 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH33' => ['type' => 'qs','id' => 31 ,'key' => 'HOCUS_MAN'],
        'MZFJ33' => ['type' => 'qs','id' => 31 ,'key' => ''],
        'SSCXSJ33' => ['type' => 'qs','id' => 31 ,'key' => 'es'],
        'SSJCZBM34' => ['type' => 'qs','id' => 32 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ34' => ['type' => 'qs','id' => 32 ,'key' => 'OPE_DATE'],
        'SSJCZMC34' => ['type' => 'qs','id' => 32 ,'key' => 'ICD9_NAME'],
        'SSJB34' => ['type' => 'qs','id' => 32 ,'key' => 'OPE_LEVEL'],
        'SSLX34' => ['type' => 'qs','id' => 32 ,'key' => 'OPE_TYPE'],
        'SZ34' => ['type' => 'qs','id' => 32 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH34' => ['type' => 'qs','id' => 32 ,'key' => 'OPE_MAN'],
        'SZBM34' => ['type' => 'qs','id' => 32 ,'key' => 'OPE_MAN_CODE'],
        'YZ34' => ['type' => 'qs','id' => 32 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH34' => ['type' => 'qs','id' => 32 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM34' => ['type' => 'qs','id' => 32 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ34' => ['type' => 'qs','id' => 32 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH34' => ['type' => 'qs','id' => 32 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM34' => ['type' => 'qs','id' => 32 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ34' => ['type' => 'qs','id' => 32 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB34' => ['type' => 'qs','id' => 32 ,'key' => 'HEAL_ID'],
        'MZFS34' => ['type' => 'qs','id' => 32 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS34' => ['type' => 'qs','id' => 32 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM34' => ['type' => 'qs','id' => 32 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH34' => ['type' => 'qs','id' => 32 ,'key' => 'HOCUS_MAN'],
        'MZFJ34' => ['type' => 'qs','id' => 32 ,'key' => ''],
        'SSCXSJ34' => ['type' => 'qs','id' => 32 ,'key' => 'es'],
        'SSJCZBM35' => ['type' => 'qs','id' => 33 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ35' => ['type' => 'qs','id' => 33 ,'key' => 'OPE_DATE'],
        'SSJCZMC35' => ['type' => 'qs','id' => 33 ,'key' => 'ICD9_NAME'],
        'SSJB35' => ['type' => 'qs','id' => 33 ,'key' => 'OPE_LEVEL'],
        'SSLX35' => ['type' => 'qs','id' => 33 ,'key' => 'OPE_TYPE'],
        'SZ35' => ['type' => 'qs','id' => 33 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH35' => ['type' => 'qs','id' => 33 ,'key' => 'OPE_MAN'],
        'SZBM35' => ['type' => 'qs','id' => 33 ,'key' => 'OPE_MAN_CODE'],
        'YZ35' => ['type' => 'qs','id' => 33 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH35' => ['type' => 'qs','id' => 33 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM35' => ['type' => 'qs','id' => 33 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ35' => ['type' => 'qs','id' => 33 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH35' => ['type' => 'qs','id' => 33 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM35' => ['type' => 'qs','id' => 33 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ35' => ['type' => 'qs','id' => 33 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB35' => ['type' => 'qs','id' => 33 ,'key' => 'HEAL_ID'],
        'MZFS35' => ['type' => 'qs','id' => 33 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS35' => ['type' => 'qs','id' => 33 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM35' => ['type' => 'qs','id' => 33 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH35' => ['type' => 'qs','id' => 33 ,'key' => 'HOCUS_MAN'],
        'MZFJ35' => ['type' => 'qs','id' => 33 ,'key' => ''],
        'SSCXSJ35' => ['type' => 'qs','id' => 33 ,'key' => 'es'],
        'SSJCZBM36' => ['type' => 'qs','id' => 34 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ36' => ['type' => 'qs','id' => 34 ,'key' => 'OPE_DATE'],
        'SSJCZMC36' => ['type' => 'qs','id' => 34 ,'key' => 'ICD9_NAME'],
        'SSJB36' => ['type' => 'qs','id' => 34 ,'key' => 'OPE_LEVEL'],
        'SSLX36' => ['type' => 'qs','id' => 34 ,'key' => 'OPE_TYPE'],
        'SZ36' => ['type' => 'qs','id' => 34 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH36' => ['type' => 'qs','id' => 34 ,'key' => 'OPE_MAN'],
        'SZBM36' => ['type' => 'qs','id' => 34 ,'key' => 'OPE_MAN_CODE'],
        'YZ36' => ['type' => 'qs','id' => 34 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH36' => ['type' => 'qs','id' => 34 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM36' => ['type' => 'qs','id' => 34 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ36' => ['type' => 'qs','id' => 34 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH36' => ['type' => 'qs','id' => 34 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM36' => ['type' => 'qs','id' => 34 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ36' => ['type' => 'qs','id' => 34 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB36' => ['type' => 'qs','id' => 34 ,'key' => 'HEAL_ID'],
        'MZFS36' => ['type' => 'qs','id' => 34 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS36' => ['type' => 'qs','id' => 34 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM36' => ['type' => 'qs','id' => 34 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH36' => ['type' => 'qs','id' => 34 ,'key' => 'HOCUS_MAN'],
        'MZFJ36' => ['type' => 'qs','id' => 34 ,'key' => ''],
        'SSCXSJ36' => ['type' => 'qs','id' => 34 ,'key' => 'es'],
        'SSJCZBM37' => ['type' => 'qs','id' => 35 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ37' => ['type' => 'qs','id' => 35 ,'key' => 'OPE_DATE'],
        'SSJCZMC37' => ['type' => 'qs','id' => 35 ,'key' => 'ICD9_NAME'],
        'SSJB37' => ['type' => 'qs','id' => 35 ,'key' => 'OPE_LEVEL'],
        'SSLX37' => ['type' => 'qs','id' => 35 ,'key' => 'OPE_TYPE'],
        'SZ37' => ['type' => 'qs','id' => 35 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH37' => ['type' => 'qs','id' => 35 ,'key' => 'OPE_MAN'],
        'SZBM37' => ['type' => 'qs','id' => 35 ,'key' => 'OPE_MAN_CODE'],
        'YZ37' => ['type' => 'qs','id' => 35 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH37' => ['type' => 'qs','id' => 35 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM37' => ['type' => 'qs','id' => 35 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ37' => ['type' => 'qs','id' => 35 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH37' => ['type' => 'qs','id' => 35 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM37' => ['type' => 'qs','id' => 35 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ37' => ['type' => 'qs','id' => 35 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB37' => ['type' => 'qs','id' => 35 ,'key' => 'HEAL_ID'],
        'MZFS37' => ['type' => 'qs','id' => 35 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS37' => ['type' => 'qs','id' => 35 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM37' => ['type' => 'qs','id' => 35 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH37' => ['type' => 'qs','id' => 35 ,'key' => 'HOCUS_MAN'],
        'MZFJ37' => ['type' => 'qs','id' => 35 ,'key' => ''],
        'SSCXSJ37' => ['type' => 'qs','id' => 35 ,'key' => 'es'],
        'SSJCZBM38' => ['type' => 'qs','id' => 36 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ38' => ['type' => 'qs','id' => 36 ,'key' => 'OPE_DATE'],
        'SSJCZMC38' => ['type' => 'qs','id' => 36 ,'key' => 'ICD9_NAME'],
        'SSJB38' => ['type' => 'qs','id' => 36 ,'key' => 'OPE_LEVEL'],
        'SSLX38' => ['type' => 'qs','id' => 36 ,'key' => 'OPE_TYPE'],
        'SZ38' => ['type' => 'qs','id' => 36 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH38' => ['type' => 'qs','id' => 36 ,'key' => 'OPE_MAN'],
        'SZBM38' => ['type' => 'qs','id' => 36 ,'key' => 'OPE_MAN_CODE'],
        'YZ38' => ['type' => 'qs','id' => 36 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH38' => ['type' => 'qs','id' => 36 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM38' => ['type' => 'qs','id' => 36 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ38' => ['type' => 'qs','id' => 36 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH38' => ['type' => 'qs','id' => 36 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM38' => ['type' => 'qs','id' => 36 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ38' => ['type' => 'qs','id' => 36 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB38' => ['type' => 'qs','id' => 36 ,'key' => 'HEAL_ID'],
        'MZFS38' => ['type' => 'qs','id' => 36 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS38' => ['type' => 'qs','id' => 36 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM38' => ['type' => 'qs','id' => 36 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH38' => ['type' => 'qs','id' => 36 ,'key' => 'HOCUS_MAN'],
        'MZFJ38' => ['type' => 'qs','id' => 36 ,'key' => ''],
        'SSCXSJ38' => ['type' => 'qs','id' => 36 ,'key' => 'es'],
        'SSJCZBM39' => ['type' => 'qs','id' => 37 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ39' => ['type' => 'qs','id' => 37 ,'key' => 'OPE_DATE'],
        'SSJCZMC39' => ['type' => 'qs','id' => 37 ,'key' => 'ICD9_NAME'],
        'SSJB39' => ['type' => 'qs','id' => 37 ,'key' => 'OPE_LEVEL'],
        'SSLX39' => ['type' => 'qs','id' => 37 ,'key' => 'OPE_TYPE'],
        'SZ39' => ['type' => 'qs','id' => 37 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH39' => ['type' => 'qs','id' => 37 ,'key' => 'OPE_MAN'],
        'SZBM39' => ['type' => 'qs','id' => 37 ,'key' => 'OPE_MAN_CODE'],
        'YZ39' => ['type' => 'qs','id' => 37 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH39' => ['type' => 'qs','id' => 37 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM39' => ['type' => 'qs','id' => 37 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ39' => ['type' => 'qs','id' => 37 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH39' => ['type' => 'qs','id' => 37 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM39' => ['type' => 'qs','id' => 37 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ39' => ['type' => 'qs','id' => 37 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB39' => ['type' => 'qs','id' => 37 ,'key' => 'HEAL_ID'],
        'MZFS39' => ['type' => 'qs','id' => 37 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS39' => ['type' => 'qs','id' => 37 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM39' => ['type' => 'qs','id' => 37 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH39' => ['type' => 'qs','id' => 37 ,'key' => 'HOCUS_MAN'],
        'MZFJ39' => ['type' => 'qs','id' => 37 ,'key' => ''],
        'SSCXSJ39' => ['type' => 'qs','id' => 37 ,'key' => 'es'],
        'SSJCZBM40' => ['type' => 'qs','id' => 38 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ40' => ['type' => 'qs','id' => 38 ,'key' => 'OPE_DATE'],
        'SSJCZMC40' => ['type' => 'qs','id' => 38 ,'key' => 'ICD9_NAME'],
        'SSJB40' => ['type' => 'qs','id' => 38 ,'key' => 'OPE_LEVEL'],
        'SSLX40' => ['type' => 'qs','id' => 38 ,'key' => 'OPE_TYPE'],
        'SZ40' => ['type' => 'qs','id' => 38 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH40' => ['type' => 'qs','id' => 38 ,'key' => 'OPE_MAN'],
        'SZBM40' => ['type' => 'qs','id' => 38 ,'key' => 'OPE_MAN_CODE'],
        'YZ40' => ['type' => 'qs','id' => 38 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH40' => ['type' => 'qs','id' => 38 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM40' => ['type' => 'qs','id' => 38 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ40' => ['type' => 'qs','id' => 38 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH40' => ['type' => 'qs','id' => 38 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM40' => ['type' => 'qs','id' => 38 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ40' => ['type' => 'qs','id' => 38 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB40' => ['type' => 'qs','id' => 38 ,'key' => 'HEAL_ID'],
        'MZFS40' => ['type' => 'qs','id' => 38 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS40' => ['type' => 'qs','id' => 38 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM40' => ['type' => 'qs','id' => 38 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH40' => ['type' => 'qs','id' => 38 ,'key' => 'HOCUS_MAN'],
        'MZFJ40' => ['type' => 'qs','id' => 38 ,'key' => ''],
        'SSCXSJ40' => ['type' => 'qs','id' => 38 ,'key' => 'es'],
        'SSJCZBM41' => ['type' => 'qs','id' => 39 ,'key' => 'ICD9_ID1'],
        'SSJCZRQ41' => ['type' => 'qs','id' => 39 ,'key' => 'OPE_DATE'],
        'SSJCZMC41' => ['type' => 'qs','id' => 39 ,'key' => 'ICD9_NAME'],
        'SSJB41' => ['type' => 'qs','id' => 39 ,'key' => 'OPE_LEVEL'],
        'SSLX41' => ['type' => 'qs','id' => 39 ,'key' => 'OPE_TYPE'],
        'SZ41' => ['type' => 'qs','id' => 39 ,'key' => 'OPE_MAN_NAME'],
        'SZSFZH41' => ['type' => 'qs','id' => 39 ,'key' => 'OPE_MAN'],
        'SZBM41' => ['type' => 'qs','id' => 39 ,'key' => 'OPE_MAN_CODE'],
        'YZ41' => ['type' => 'qs','id' => 39 ,'key' => 'FRIST_ASSISTANT_NAME'],
        'YZSFZH41' => ['type' => 'qs','id' => 39 ,'key' => 'FRIST_ASSISTANT'],
        'YZBM41' => ['type' => 'qs','id' => 39 ,'key' => 'FRIST_ASSISTANT_CODE'],
        'EZ41' => ['type' => 'qs','id' => 39 ,'key' => 'SECOND_ASSISTANT_NAME'],
        'EZSFZH41' => ['type' => 'qs','id' => 39 ,'key' => 'SECOND_ASSISTANT'],
        'EZBM41' => ['type' => 'qs','id' => 39 ,'key' => 'SECOND_ASSISTANT_CODE'],
        'QKDJ41' => ['type' => 'qs','id' => 39 ,'key' => 'INCISION_GRADE_ID'],
        'QKYHLB41' => ['type' => 'qs','id' => 39 ,'key' => 'HEAL_ID'],
        'MZFS41' => ['type' => 'qs','id' => 39 ,'key' => 'HOCUS_MAN_NAME'],
        'MZYS41' => ['type' => 'qs','id' => 39 ,'key' => 'HOCUS_WAY_ID'],
        'MZYSBM41' => ['type' => 'qs','id' => 39 ,'key' => 'HOCUS_MAN_CODE'],
        'MZYSSFZH41' => ['type' => 'qs','id' => 39 ,'key' => 'HOCUS_MAN'],
        'MZFJ41' => ['type' => 'qs','id' => 39 ,'key' => ''],
        'SSCXSJ41' => ['type' => 'qs','id' => 39 ,'key' => 'es'],
        'RJQK' => 'LCLJ',
        'WCQK' => 'WCQK',
        'BYQK' => 'BYQK',
        'LYFS' => 'AEM01C',
        'YZZY_YLJG' => 'YZZY_YLJG',
        'WSY_YLJG' => 'WSY_YLJG',
        'SFZZYJH' => 'AEM03C',
        'MD' => 'AEM04',
        'RYQ_T' => 'AEJ01',
        'RYQ_XS' => 'AEJ02',
        'RYQ_F' => 'AEJ03',
        'RYH_T' => 'AEJ04',
        'RYH_XS' => 'AEJ05',
        'RYH_F' => 'AEJ06',
        'ZFY' => 'ADA01',
        'ZFJE' => 'ADA0101',
        'YLFUF' => 'D11',
        'ZLCZF' => 'D12',
        'HLF' => 'D13',
        'QTFY' => 'D14',
        'BLZDF' => 'D15',
        'SYSZDF' => 'D16',
        'YXXZDF' => 'D17',
        'LCZDXMF' => 'D18',
        'FSSZLXMF' => 'D19',
        'WLZLF' => 'D19X01',
        'SSZLF' => 'D20',
        'MAF' => 'D20X01',
        'SSF' => 'D20X02',
        'KFF' => 'D21',
        'ZYZLF' => 'D22',
        'XYF' => 'D23',
        'KJYWF' => 'D23X01',
        'ZCYF' => 'D24',
        'ZCYF1' => 'D25',
        'XF' => 'D26',
        'BDBLZPF' => 'D27',
        'QDBLZPF' => 'D28',
        'NXYZLZPF' => 'D29',
        'XBYZLZPF' => 'D30',
        'HCYYCLF' => 'D31',
        'YYCLF' => 'D32',
        'YCXYYCLF' => 'D33',
        'QTF' => 'D34'
    ]
];
